### ISSUE TITLE
请问这个BetterNCM使用之后，pc网易云音乐界面没有私人FM怎么办？

### ISSUE THREAD

**Issue by famudd** [MicroCBer/BetterNCM#1]
我使用了一键安装的方式，使用后发现没有私人FM了；后来我在您的最新版本（0.1.3）中的README.md中看到您的界面是有私人FM的，并且我也尝试了您的安装方法，没有成功。所以想问问您该如何操作。

**Comment by BecodReyes** [comment]
找到并删除

```
.nav .firstlist>*:nth-child(6) {
    display: none;
}
```

**Comment by famudd** [comment]
> 找到并删除
> 
> ```
> .nav .firstlist>*:nth-child(6) {
>     display: none;
> }
> ```

**Comment by famudd** [comment]
> 找到并删除
> 
> ```
> .nav .firstlist>*:nth-child(6) {
>     display: none;
> }
> ```

非常感谢

**Comment by famudd** [comment]
> 找到并删除
> 
> ```
> .nav .firstlist>*:nth-child(6) {
>     display: none;
> }
> ```

 已经成功显示私人FM了，可是我点击之后底部的播放栏会显示回原来的主题色，请问这个有解决办法吗

**Comment by BecodReyes** [comment]
> 已经成功显示私人FM了，可是我点击之后底部的播放栏会显示回原来的主题色，请问这个有解决办法吗

改css
暂时没找到调出devtool的方法

**Comment by famudd** [comment]
好的，非常感谢

**Comment by MicroCBer** [comment]
> > 已经成功显示私人FM了，可是我点击之后底部的播放栏会显示回原来的主题色，请问这个有解决办法吗
> 
> 改css 有devtool会方便很多 但是暂时没找到调出devtool的方法
> 
> 可以拆原版的ntpk，目前并未加密，只是在软件里做了验证而已

插件debugger提供了类似inspector找到鼠标指针下元素路径的功能

打开插件后按p会将元素路径复制到剪贴板

其实补齐devtools文件以后可以把他打开，只是找不到那么老版本的devtools文件，就没整
