### ISSUE TITLE
求助，装完主题字都看不清

### ISSUE THREAD

**Issue by HuanLinMaster** [MicroCBer/BetterNCM#10]
![image](https://user-images.githubusercontent.com/94176676/183847461-2fc048a7-bb05-4562-890d-c6fbbe39ed54.png)
如图，我不理解

**Comment by MicroCBer** [comment]
为什么你要把背景设成纯白的呢……

**Comment by HuanLinMaster** [comment]
> 

在哪调背景呢（

**Comment by HuanLinMaster** [comment]
> 为什么你要把背景设成纯白的呢……

调成黑色的，黑字看不见，白色看不见白字，而且为啥配置里的对象直接被解析成了[Object Object]（直接toString了)

**Comment by MicroCBer** [comment]
...?你装了个什么版本的betterncm
这是新版css配置和老版loader混合才会出现的现象、
把主题改成官方黑色

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/185219569-4953700d-bf72-4574-9a0b-c417827e8688.png)
v2新增了字体颜色调节
