### ISSUE TITLE
BNCM又无了

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#103]
没发现BNCM标志 退出后报错
![image](https://user-images.githubusercontent.com/104675168/203468448-851ac7ed-77cd-4d22-8567-9870de03f296.png)

**Comment by Ds1nk** [comment]
无法重装
![image](https://user-images.githubusercontent.com/104675168/203468741-88bb79f0-94c1-4811-b6d7-d46f37484064.png)
一直在下载

**Comment by Ds1nk** [comment]
再重装后没好

**Comment by MicroCBer** [comment]
F12有弹窗吗

**Comment by Ds1nk** [comment]
有
![image](https://user-images.githubusercontent.com/104675168/204074131-2a70f789-e46a-4ec9-a7a8-b3d948e05714.png)

**Comment by Ds1nk** [comment]
![image](https://user-images.githubusercontent.com/104675168/204074311-4cf6c152-292e-42cd-95e8-b34404e7824a.png)
e

**Comment by Ds1nk** [comment]
所以我重装了一下网易云
然后什么都没发生

**Comment by Ds1nk** [comment]
重启后修复
