### ISSUE TITLE
obs捕捉点歌姬窗口失败

### ISSUE THREAD

**Issue by zuilemt** [MicroCBer/BetterNCM#104]
1、obs捕捉点歌姬窗口会显示白屏或者被捕捉后画面无法持续更新
2、点歌姬窗口歌曲播放时间获取不到（同时网易云音乐播放音乐时进度条不动
![UIFDDMASG7@YHE 0($D)1~C](https://user-images.githubusercontent.com/53639376/203662723-67749ddb-256c-434c-ac1d-de0bc8d1e43a.png)

**Comment by MicroCBer** [comment]
在捕捉选项内使用`Bitblt`模式即可

进度条不动的问题后面修
