### ISSUE TITLE
一些关于MoTheme的问题和改进建议

### ISSUE THREAD

**Issue by CarlSkyCoding** [MicroCBer/BetterNCM#105]
![image](https://user-images.githubusercontent.com/79088785/203523394-51f2226e-bda3-458b-be70-952279118299.png)
希望可以把这里转换时候的页面切换做的更美观一些，而不是先重合再消失

二是希望添加主窗口圆角

**Comment by MicroCBer** [comment]
@mo-jinran

**Comment by mo-jinran** [comment]
知道了嗷 下次一定

**Comment by mo-jinran** [comment]
就这个样子吧
https://user-images.githubusercontent.com/66980784/204129079-a1fa742d-6aea-4e20-aca1-d621fc691359.mp4

**Comment by mo-jinran** [comment]
https://user-images.githubusercontent.com/66980784/204129139-fbbf75b2-7be7-44d3-9c7a-8c29f92005f3.mp4

**Comment by CarlSkyCoding** [comment]
大佬厉害！！
很流畅！！~

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/204434556-b77dd375-86f7-4a5f-9ff6-fd15a6eb0cd3.png)
可以关闭这issue了

**Comment by CarlSkyCoding** [comment]
好的好的
