### ISSUE TITLE
最新版找不到解灰功能，是去掉了吗？

### ISSUE THREAD

**Issue by diyudule** [MicroCBer/BetterNCM#107]
![QQ截图20221127152256](https://user-images.githubusercontent.com/29426186/204123969-536583c9-7db3-4a0c-9fad-a8c80b70af08.png)

**Comment by Kylin2021** [comment]
同问

**Comment by shixiangxi** [comment]
官方睁一只眼闭一只眼，闹大了容易被叫走

**Comment by zhuzixuan2019241** [comment]
[UnblockCloudMusic_0.1.7.zip](https://github.com/MicroCBer/BetterNCM/files/10399271/UnblockCloudMusic_0.1.7.zip)
