### ISSUE TITLE
关于RefinedNowPlaying的一些问题

### ISSUE THREAD

**Issue by WorldSansha** [MicroCBer/BetterNCM#108]
首先说明已装插件列表，网易云版本为2.10.6，BetterNCM版本为v0.2.5：
![image](https://user-images.githubusercontent.com/37899975/204136554-638fc0f3-ee7b-448e-987c-6d427235bb18.png)
以下是本人遇到的Bug
在第一次打开网易云时展开播放界面会有背景残留，但重新再进入就恢复正常，如图：
![image](https://user-images.githubusercontent.com/37899975/204136611-31fc88cb-5f9b-48f3-be9b-d0eb2879cb8d.png)
在播放试听歌曲时会与歌曲标题冲突，如图：
![image](https://user-images.githubusercontent.com/37899975/204136656-3de6f495-08ad-4076-a03b-8efa49c6c502.png)
在进入全屏纯享模式时会导致只有背景，卸载RefinedNowPlaying后正常，如图：
![image](https://user-images.githubusercontent.com/37899975/204136916-adfa56bf-dfa6-4ca3-ae4e-778a0eb8f5df.png)
以下是功能性建议
可以将歌词右侧的竖条隐藏，更美观一些，如图
![image](https://user-images.githubusercontent.com/37899975/204137043-289f8c83-f5f1-4fa1-a426-0571d26cc54d.png)
可以将全屏纯享界面与播放界面保持一致，以及自定义歌词字体

非常感谢solstice大佬可以提供一个美观的播放页面，自从更新网易云2.10.6以来就因为新的播放页面导致一直停留在2.10.5，因为新版的播放界面真的很不习惯
这是更新前
![5FIN{MKJD(6FX$K0~DN6EJI](https://user-images.githubusercontent.com/37899975/204137591-2c817570-0d26-4821-bc19-d2271a932c3e.jpg)
这是更新后
![7UGEO5LLYD`M{_UN9}{(5OA](https://user-images.githubusercontent.com/37899975/204137560-30382ce4-b718-48f2-a49e-8a6569ce2fd3.jpg)
新手第一次提issue，如果有什么说得不好还请多指教

**Comment by solstice23** [comment]
> 在第一次打开网易云时展开播放界面会有背景残留
> 在进入全屏纯享模式时会导致只有背景

已修复
