### ISSUE TITLE
分离 BetterNCM 的注入器和其他部分

### ISSUE THREAD

**Issue by Remik1r3n** [MicroCBer/BetterNCM#109]
目前 BetterNCM 的每次更新（无论更改了什么）都需要更改网易云程序目录的 DLL。

这带来了一些小问题（例如，Program Files 目录的权限问题），以及对于 MSIX 用户来说每次更新都需要重新打包整个程序。

故，建议将 BetterNCM 拆分成两个部分。一个部分作为注入器，放置于网易云程序目录，并使其代码尽可能的精简（仅仅做它必须做的事情），之后的工作（例如载入插件和某些 API 等）则转交配置目录中另一个部分。

这使得没有更改注入部分的代码时，自更新较为方便。

虽然目前这个改变可能意义还是比较小，不过我相信在 BetterNCM 日趋成熟之后，这个改变会更加有用。

**Comment by MicroCBer** [comment]
请使用：https://github.com/acidicoala/Koaloader
