### ISSUE TITLE
自修改点歌姬，新增功能

### ISSUE THREAD

**Issue by HuanLinMaster** [MicroCBer/BetterNCM#11]
代码：https://airportal.cn/515300/YFtqXZNbGn 复制链接到浏览器打开
新增功能：弹幕发送“切歌 换歌 ch”时，可以切换到下一首歌曲，并且新增设置（对应localStorage的__lsp__live__room__owner）房主，只有此人可以切歌
目前计划开学前把弹幕回复功能码出来， ~~我就是BetterNCM单推人（（~~

**Comment by HuanLinMaster** [comment]
计划有变，感觉自带的弹幕姬不太好用（指不单独分出去一个窗口），~~所以打算自己码一个干掉自带的~~

**Comment by MicroCBer** [comment]
单独分出去一个窗口之前的api不太好做，建议等v2

**Comment by HuanLinMaster** [comment]
> 单独分出去一个窗口之前的api不太好做，建议等v2
哥们，window.open()了解一下
还能实现两个窗口互相bb
var demo = window.open("demo.html")
父窗口->子窗口 demo.postMessage("F**k")
子窗口->父窗口 opener.postMessgae("F**k")

**Comment by MicroCBer** [comment]
> > 单独分出去一个窗口之前的api不太好做，建议等v2
> > 哥们，window.open()了解一下
> > 还能实现两个窗口互相bb
> > var demo = window.open("demo.html")
> > 父窗口->子窗口 demo.postMessage("F**k")
> > 子窗口->父窗口 opener.postMessgae("F**k")

生成demo.html不麻烦吗，虽然我已经在操作增强里面这么干过一次了

**Comment by HuanLinMaster** [comment]
> > > 单独分出去一个窗口之前的api不太好做，建议等v2
> > > 哥们，window.open()了解一下
> > > 还能实现两个窗口互相bb
> > > var demo = window.open("demo.html")
> > > 父窗口->子窗口 demo.postMessage("F**k")
> > > 子窗口->父窗口 opener.postMessgae("F**k")
> 
> 生成demo.html不麻烦吗，虽然我已经在操作增强里面这么干过一次了

你别说还真不是很麻烦，实在不行你可以用https://c.runoob.com/front-end/846/ 把html转js 然后open("javascript:;"),但只建议用在production

**Comment by MicroCBer** [comment]
> > > > 单独分出去一个窗口之前的api不太好做，建议等v2
> > > > 哥们，window.open()了解一下
> > > > 还能实现两个窗口互相bb
> > > > var demo = window.open("demo.html")
> > > > 父窗口->子窗口 demo.postMessage("F**k")
> > > > 子窗口->父窗口 opener.postMessgae("F**k")
> > 
> > 
> > 生成demo.html不麻烦吗，虽然我已经在操作增强里面这么干过一次了
> 
> 你别说还真不是很麻烦，实在不行你可以用https://c.runoob.com/front-end/846/ 把html转js 然后open("javascript:;"),但只建议用在production

你写前端都不分文件的？甚至NBundle我都不觉得是个好东西，只是权宜之计

**Comment by MicroCBer** [comment]
所以现在v2直接是压缩包发布了

**Comment by HuanLinMaster** [comment]
> > > > > 单独分出去一个窗口之前的api不太好做，建议等v2
> > > > > 哥们，window.open()了解一下
> > > > > 还能实现两个窗口互相bb
> > > > > var demo = window.open("demo.html")
> > > > > 父窗口->子窗口 demo.postMessage("F**k")
> > > > > 子窗口->父窗口 opener.postMessgae("F**k")
> > > 
> > > 
> > > 生成demo.html不麻烦吗，虽然我已经在操作增强里面这么干过一次了
> > 
> > 
> > 你别说还真不是很麻烦，实在不行你可以用https://c.runoob.com/front-end/846/ 把html转js 然后open("javascript:;"),但只建议用在production
> 
> 你写前端都不分文件的？甚至NBundle我都不觉得是个好东西，只是权宜之计

都说了 用于production 没说生产环境用这玩意啊，看着不得犯迷糊

**Comment by HuanLinMaster** [comment]
> 所以现在v2直接是压缩包发布了

要不咱加QQ吧，感觉你这项目要是再不定个规范，迟早变狮山

**Comment by HuanLinMaster** [comment]
> 

我感觉，怼着网易云的狮山客户端改不是办法，还不如自己写一个
这里有网易云的api，能直接方法调用的npm包
https://github.com/Lizhooh/NeteaseMusicApi

**Comment by MicroCBer** [comment]
1. 工程量太大 难得搞
2. 已经有很多类似的 如lyric ease，yesmusic
3. webapi很不稳定，我这经常播一半断掉
4. betterncm现在基本上可以很容易的向上兼容，网易云就算改API我也不用大改

**Comment by MicroCBer** [comment]
可以去看看Acrylic的解析
