### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by misaka12543** [MicroCBer/BetterNCM#110]
启动时界面闪烁，随后提示：Failed to load plugins!Attempted for 3 times
在设置界面点击Reload plugins情况复现，console里的log如下：
[bug_report.txt](https://github.com/MicroCBer/BetterNCM/files/10104323/bug_report.txt)

**Comment by MicroCBer** [comment]
这种情况需用管理员打开，下个版本或许会加入自动用管理员打开重试
