### ISSUE TITLE
安装后启动白屏或黑屏 可以点击和播放 但无画面

### ISSUE THREAD

**Issue by IBs-Official** [MicroCBer/BetterNCM#112]
如题，重装系统之后就无法正常使用，起初认为是个人问题便重装网易云和插件，但试了多次之后还是不行，希望解决一下问题

**Comment by MicroCBer** [comment]
你的配置？

**Comment by IBs-Official** [comment]
> 你的配置？

i3-3110 GT630 win10x64专业版 1903 网易云2.10.6(build:200601)(patch:1:94d46ef)

**Comment by Ds1nk** [comment]
> > 你的配置？
> 
> i3-3110 GT630 win10x64专业版 1903 网易云2.10.6(build:200601)(patch:1:94d46ef)

update windows plzzzzzzz

**Comment by MicroCBer** [comment]
> > 你的配置？
> 
> i3-3110 GT630 win10x64专业版 1903 网易云2.10.6(build:200601)(patch:1:94d46ef)

应该是配置过旧的原因，推荐更换配置或放弃插件

（如果采用网易云本身CPU渲染的方式，基本上无法使现在的插件流畅运行）
