### ISSUE TITLE
RefinedNowPlaying歌词样式

### ISSUE THREAD

**Issue by Amhertx** [MicroCBer/BetterNCM#113]
如图，期望可以以完整的单词换行，而不是以字符换行
![Snipaste_2022-11-29_12-27-48](https://user-images.githubusercontent.com/46993971/204439149-f6f1c08f-f3cc-4183-94c4-6b44e1dbb4a2.png)

**Comment by solstice23** [comment]
Completed in https://github.com/solstice23/refined-now-playing-netease/commit/56129f247f8c2e57986f58857edddcfe4b4e531d

![image](https://user-images.githubusercontent.com/23134847/205044353-8d90633e-2875-465e-8042-e31837f1e9dc.png)

**Comment by Amhertx** [comment]
、

> Completed in [solstice23/refined-now-playing-netease@56129f2](https://github.com/solstice23/refined-now-playing-netease/commit/56129f247f8c2e57986f58857edddcfe4b4e531d)
> 
> ![image](https://user-images.githubusercontent.com/23134847/205044353-8d90633e-2875-465e-8042-e31837f1e9dc.png)

这个插件是不是没有在ncm插件库里更新呢，没有检测到更新，而且比git上面的截图少了几个操作按钮
![Snipaste_2022-12-02_14-50-48](https://user-images.githubusercontent.com/46993971/205232995-81f9a47c-5c43-464c-b13a-a351c47b3b6a.png)
![Snipaste_2022-12-02_14-52-15](https://user-images.githubusercontent.com/46993971/205233177-67a45a2a-8496-482c-8339-f94f8abc0b72.png)

**Comment by Amhertx** [comment]
> Completed in [solstice23/refined-now-playing-netease@56129f2](https://github.com/solstice23/refined-now-playing-netease/commit/56129f247f8c2e57986f58857edddcfe4b4e531d)
> 
> ![image](https://user-images.githubusercontent.com/23134847/205044353-8d90633e-2875-465e-8042-e31837f1e9dc.png)

然后我试了下按照你的readme去做，也是只有我上面的截图那样，并没有readme截图里面那么多选项，而且我这边只有plugins_runtime文件夹

**Comment by rainyorange** [comment]
> > Completed in [solstice23/refined-now-playing-netease@56129f2](https://github.com/solstice23/refined-now-playing-netease/commit/56129f247f8c2e57986f58857edddcfe4b4e531d)
> > ![image](https://user-images.githubusercontent.com/23134847/205044353-8d90633e-2875-465e-8042-e31837f1e9dc.png)
> 
> 然后我试了下按照你的readme去做，也是只有我上面的截图那样，并没有readme截图里面那么多选项，而且我这边只有plugins_runtime文件夹

你得去插件文件夹把旧版本的全部删除才行 至于文件夹，新建一个就好

**Comment by Amhertx** [comment]
> > > Completed in [solstice23/refined-now-playing-netease@56129f2](https://github.com/solstice23/refined-now-playing-netease/commit/56129f247f8c2e57986f58857edddcfe4b4e531d)
> > > ![image](https://user-images.githubusercontent.com/23134847/205044353-8d90633e-2875-465e-8042-e31837f1e9dc.png)
> > 
> > 
> > 然后我试了下按照你的readme去做，也是只有我上面的截图那样，并没有readme截图里面那么多选项，而且我这边只有plugins_runtime文件夹
> 
> 你得去插件文件夹把旧版本的全部删除才行 至于文件夹，新建一个就好

这倒是可以了，但是如果不小心点到插件库的更新就得重新删一次文件夹，而且一般放dev代表这个还没上线吧，还是要作者大大修改并且发版才行

![image](https://user-images.githubusercontent.com/46993971/205479700-cde0f360-dd00-48a5-bf49-1c47b554d569.png)
