### ISSUE TITLE
底部音乐栏浮窗样式问题

### ISSUE THREAD

**Issue by Amhertx** [MicroCBer/BetterNCM#114]
如图，播放到vip歌曲的时候会有一个背景色块，鼠标对音乐栏进行任意操作后会消失
![Snipaste_2022-11-29_13-08-31](https://user-images.githubusercontent.com/46993971/204444427-ffa61a09-2b18-4c15-a9cb-3ed283f1bfa1.png)

在播放页面的某些歌曲中，将鼠标滑过音乐栏，音乐栏的一些按钮会出现色块
![动画](https://user-images.githubusercontent.com/46993971/204444430-5ac6d122-0ac5-4f40-9277-a5365f08a9ce.gif)

这是已安装的插件
![Snipaste_2022-11-29_13-16-37](https://user-images.githubusercontent.com/46993971/204444996-a3625e5d-89fb-4421-a94a-dfd8c988b485.png)

**Comment by solstice23** [comment]
Fixed in https://github.com/solstice23/refined-now-playing-netease/commit/cbe95cd41bebe1ab4cf2e52ee265e982798d7a3a

**Comment by Amhertx** [comment]
> Fixed in [solstice23/refined-now-playing-netease@cbe95cd](https://github.com/solstice23/refined-now-playing-netease/commit/cbe95cd41bebe1ab4cf2e52ee265e982798d7a3a)

牛啊，没想到这玩意居然是html，居然用的是electron😂
