### ISSUE TITLE
[功能请求] RefinedNowPlaying加入可自定义的音频可视化

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#115]
如题

**Comment by solstice23** [comment]
https://github.com/solstice23/refined-now-playing-netease/pull/1#issuecomment-1327978272

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/212483996-d9802e14-ca3d-426a-81af-2fed474ff1f9.png)

功能已可实现 请在对应仓库下发issue
