### ISSUE TITLE
播放界面能不能自己加CSS进去呢

### ISSUE THREAD

**Issue by SLi-Man** [MicroCBer/BetterNCM#116]
播放界面能不能自己加CSS进去呢
![image](https://user-images.githubusercontent.com/33563304/204746697-adb9e56f-a7cf-475a-9755-ca8708e31024.png)

想自己稍微改一下样式

**Comment by MicroCBer** [comment]
**[开发文档](https://github.com/MicroCBer/BetterNCM/wiki/%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3)**
