### ISSUE TITLE
[功能请求] 防止页面变灰插件

### ISSUE THREAD

**Issue by ReOracle** [MicroCBer/BetterNCM#117]
强制变灰多少有点😶

**Comment by Marce1ek** [comment]
+1

**Comment by Bulb1734** [comment]
+1

**Comment by Marce1ek** [comment]
![QQ图片20221201130045](https://user-images.githubusercontent.com/99329516/204969566-60a05af9-7391-4859-a742-b37a9d99bed9.png)
F12 删掉`f-gray`然后回车

**Comment by kasuganosoras** [comment]
插件在这，需要自取
https://github.com/kasuganosoras/NoGrey
