### ISSUE TITLE
NCM has not changed after installing the simple plug-in 

### ISSUE THREAD

**Issue by Tianseen** [MicroCBer/BetterNCM#12]
Current version:

NCM:2.9.10(Build:200061)(Patch:1:5241321)

BetterNCM:0.1.9

**Comment by MicroCBer** [comment]
都是国人，不用说英语（

现在我最老版本测试支持到`2.10.2`，可能是版本太老了，更新下网易云看看

**Comment by lijingbo666** [comment]
我之前版本是2.9.10然后下载软件后双击安装没反应   更新到2.10.3之后双击安装还是没反应

**Comment by lijingbo666** [comment]
管理员身份运行也不行
