### ISSUE TITLE
关于Motheme和RefinedNowPlaying混用时出现的一点小问题

### ISSUE THREAD

**Issue by rainyorange** [MicroCBer/BetterNCM#120]
![image](https://user-images.githubusercontent.com/36807368/205466239-c48ad5e2-a9be-44f9-81f3-449e18e14555.png)
应该是沉浸主题选项的问题，修改了红心和音量悬浮小圆球的颜色

**Comment by rainyorange** [comment]
@solstice23

**Comment by MicroCBer** [comment]
已修复

**Comment by rainyorange** [comment]
![image](https://user-images.githubusercontent.com/36807368/207551114-14722970-7cdb-4112-b825-a3518dcbbb01.png)
未修复啊

**Comment by rainyorange** [comment]
哦更新未上传（）确实已修复
