### ISSUE TITLE
点歌姬突然寄了

### ISSUE THREAD

**Issue by CSSZYF** [MicroCBer/BetterNCM#122]
一直用的好好的 0.25 网易云2.10.6版本 这两天突然寄了 卸载重装网易云和插件都不行 
![uTools_1670141773919](https://user-images.githubusercontent.com/63802741/205480885-0a37c4c4-15ee-4fde-b684-0f39261cd0fb.png)
不知道有没有关系

**Comment by MicroCBer** [comment]
B站修改了弹幕格式，将在下个版本修复

**Comment by MicroCBer** [comment]
已于`0.1.5`中修复
