### ISSUE TITLE
BetterNCM不显示

### ISSUE THREAD

**Issue by InkNight-DedNET** [MicroCBer/BetterNCM#123]
如题，安装了BetterNCM后在网易云音乐的设置顶端不显示BetterNCM的设置选项。任务管理器也确实有CMD进程。
![NCM](https://user-images.githubusercontent.com/66107082/205504476-31afa586-e7d4-481a-af2f-7462a440360b.png)

**Comment by InkNight-DedNET** [comment]
![image](https://user-images.githubusercontent.com/66107082/206963979-d1f85fca-e1e6-43fe-9e2c-9e3f5477c0fb.png)
是这个么

**Comment by MicroCBer** [comment]
如果有空可以在QQ私聊我debug，日志看不出什么问题

**Comment by InkNight-DedNET** [comment]
很抱歉 但这个Bug我之前测试出个问题 强制重启整个电脑就有一定可能修复 现在已经好了 😂现在应该是不行了

**Comment by MicroCBer** [comment]
![LK{`19ZXC1H6 IB$ 5S{(`H](https://user-images.githubusercontent.com/66859419/207336113-4c49af4e-d249-4a93-a571-90d25ab23f42.png)
原因：[Windows 10 端口被 Hyper-V 随机保留（占用）的问题](https://zhaoji.wang/solve-the-problem-of-windows-10-ports-being-randomly-reserved-occupied-by-hyper-v/)

感谢 @果てしない運命 的耐心配合与帮助

~~真够阴间~~
