### ISSUE TITLE
安装BetterNCM后网易云内“更改歌曲下载目录”功能失效

### ISSUE THREAD

**Issue by laorentou666** [MicroCBer/BetterNCM#125]
https://user-images.githubusercontent.com/89732460/206134823-a27fc933-070e-4409-b59e-2decfc61793e.mp4

如视频所示，更改下载目录后网易云不重启
操作平台：Windows11 Pro
网易云版本：2.10.6

**Comment by MicroCBer** [comment]
已复现，原因未知

**Comment by laorentou666** [comment]
2023.1.6
在设置代理时重启也会出现类似的情况
推测所有需重启的行为都会触发？

**Comment by MicroCBer** [comment]
duplicated #211
