### ISSUE TITLE
管理员打开弹窗失败

### ISSUE THREAD

**Issue by DXXbaby** [MicroCBer/BetterNCM#128]
win11,装上插件直接就打不开网易云，直接放到根目录以及安装包的形式都试过了，还是打不开！只要去除插件，直接就打开！

**Comment by MicroCBer** [comment]
这并不是win11的问题...我开发机就是win11

应该是已知问题，"需管理员权限打开"弹窗失败，预计会在下个版本修复

**Comment by DXXbaby** [comment]
ok，谢谢

**Comment by DXXbaby** [comment]
hello，大哥。我今天win10，点击安装鑫插件，界面直接白了，必须结束任务重开才有用。。。

**Comment by MicroCBer** [comment]
#130

**Comment by MicroCBer** [comment]
验证完毕，已修复
