### ISSUE TITLE
关于qiankun和RefinedNowPlaying的一些小问题（？

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#129]
1.qiankun插件已安装但pluginmarket中提示未安装（下图为已安装插件列表）
![image](https://user-images.githubusercontent.com/119386507/206841923-252096e1-cabe-48fe-bd5c-60c5b2d886f0.png)
![image](https://user-images.githubusercontent.com/119386507/206841967-8f316d1f-e6de-47ab-b100-27a7fa37eaa2.png)
2.RefinedNowPlaying无法正常展开
![image](https://user-images.githubusercontent.com/119386507/206842096-070db23c-cedf-4b5f-8766-7bb01874990a.png)

**Comment by ConCose** [comment]
好了又出来了（不是
![image](https://user-images.githubusercontent.com/119386507/206842239-664d7ca0-5f9c-4be1-83f5-a794fb833f4e.png)
![image](https://user-images.githubusercontent.com/119386507/206842256-9f5f802d-8df8-4917-bd10-58f0773781a5.png)

**Comment by ConCose** [comment]
目测应该是因为cpu荷载过高（？
但是我后面两张图截图时cpu占用在50%左右（控制台不蹦error只蹦404warning）
reload plugin以后就变成纯白
![image](https://user-images.githubusercontent.com/119386507/206842322-f08594f5-ac2f-444a-9ff4-0271b1a2e008.png)

**Comment by MicroCBer** [comment]
> 目测应该是因为cpu荷载过高（？ 但是我后面两张图截图时cpu占用在50%左右（控制台不蹦error只蹦404warning） reload plugin以后就变成纯白 ![image](https://user-images.githubusercontent.com/119386507/206842322-f08594f5-ac2f-444a-9ff4-0271b1a2e008.png)

该问题已在 98c7cedc226a051e383220b7be2961b261105874 中修复

**Comment by MicroCBer** [comment]
qiankun已下架（
