### ISSUE TITLE
安装插件后白屏

### ISSUE THREAD

**Issue by whoisfancy** [MicroCBer/BetterNCM#130]
win11 21H2，最新版的NCM和betterNCM，任务管理器一切正常，F12提示  orpheus://orpheus/miku-plugin/style#/m/setting/:1 Failed to load resource: the server responded with a status of 404 (Not Found)

![image](https://user-images.githubusercontent.com/51506435/206851089-8d022f87-76e0-443c-9e9f-9c78d24c7714.png)

**Comment by whoisfancy** [comment]
![image](https://user-images.githubusercontent.com/51506435/206851119-dbbbd4c0-7a39-4348-af11-4cf4bc49dc74.png)

**Comment by MicroCBer** [comment]
miku-plugin的问题

**Comment by MicroCBer** [comment]
已在 98c7cedc226a051e383220b7be2961b261105874 间接修复，建议使用TinyNCM
![image](https://user-images.githubusercontent.com/66859419/206863709-9661f76e-7cc0-4997-9ff3-7fd2143ac58f.png)
