### ISSUE TITLE
UI 建议

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [MicroCBer/BetterNCM#138]
如果可行 建议将插件设置都做成标签页的形式
设置的高度会随着插件数量的增多而拉长 且大多数无法折叠

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/208082130-6b83a350-8bd2-49b8-8c57-6858b7021be2.png)

**Comment by WOSHIZHAZHA120** [comment]
![图片](https://user-images.githubusercontent.com/52521836/208082378-6db1fa91-fcb0-442e-8419-973a1c4f12ec.png)

在哪里开启呢 我这目前是这样的
