### ISSUE TITLE
解灰插件兼哪些版本？NCM未来是否会向之前的老版本兼容？

### ISSUE THREAD

**Issue by windy1021** [MicroCBer/BetterNCM#142]
![uTools_1671505487357](https://user-images.githubusercontent.com/62731276/208571991-a20cfc30-fd81-4cfa-a0ad-a5de02a83ed7.png)

2.10.6版本在安装解灰插件后下载歌曲会出现上图提示，在讨论区看到有人说2.10.3可以但我试了还是出现这样的提示。请问是插件的问题还是我设置操作上有什么失误？
之前一直在用2.9.5，那个版本我自己使用的一些软件可以解灰，但是升级后就不能了，NCM能否向上兼容一下旧版本？
感谢回答

**Comment by MicroCBer** [comment]
1. 插件不可能也不打算兼容老版本，2.10.2版本做出重大改动，使得插件完全不可能兼容老版本
2. 下载失败是解灰软件老版本的问题。目前解灰插件下载的软件版本是固定的，可能会在下个版本做出修改。
