### ISSUE TITLE
Show Console点开之后关闭Show Console会连着网易云音乐一起关闭。

### ISSUE THREAD

**Issue by fengziyun** [MicroCBer/BetterNCM#145]
> BetterNCM 0.2.5
> 网易云音乐 2.10.6（Build:200601）
> OBS 28.1.2

# OBS无法捕获
![image](https://user-images.githubusercontent.com/28677290/209465348-5837e19f-093f-4f92-b9c8-f0eb80e89f40.png)

OBS采用管理员打开也是一样无法捕获。
**LiveSongPlayer**插件因为BetterNCM，导致该插件也无法被OBS捕获。
卸载BetterNCM后恢复正常

# Show Console 关闭会连带 网易云音乐进程一起关闭
没有任何按钮可以隐藏该控制台，重复点击Show Console按钮也无法隐藏或关闭该控制台。希望后续可以优化！

**Comment by MicroCBer** [comment]
关于obs无法捕获：在obs的窗口采集选项中选择bitblt模式即可

**Comment by fengziyun** [comment]
> OBS 28.1.2 没有这种采集模式啊，并且我多种模式都是用过了，兼容模式也不起效果。

**Comment by gongfuture** [comment]
> > OBS 28.1.2
> 
> 没有这种采集模式，并且我多种模式都是用过了，兼容模式也不起效果。

![image](https://user-images.githubusercontent.com/60888755/212312809-b7351ade-499f-4a91-87b3-49a54cada0cd.png)
可以捕获，使用win10采集模式

**Comment by gongfuture** [comment]
> > > OBS 28.1.2
> > 
> > 
> > 没有这种采集模式，并且我多种模式都是用过了，兼容模式也不起效果。
> 
> ![image](https://user-images.githubusercontent.com/60888755/212312809-b7351ade-499f-4a91-87b3-49a54cada0cd.png) 可以捕获，使用win10采集模式

截图看起来有点过曝，实际曝光正常

**Comment by MicroCBer** [comment]
哦 看来是改名了 改成win10采集模式了（
