### ISSUE TITLE
网易云版本2.10.6 (Build:200601) (Patch:1:e5842f1)，安装插件开启提示插件加载失败

### ISSUE THREAD

**Issue by LLLisheng** [MicroCBer/BetterNCM#150]
![RHGFN3 X~)HL@U9GA2N60F4](https://user-images.githubusercontent.com/115356048/209624254-27d4d674-6b97-4c7c-a287-c50d3217c630.png)
![1OZA3G~4RNYJE2U)6KQO{M3](https://user-images.githubusercontent.com/115356048/209624261-1ef83ccc-4b49-4c23-8972-c4e893215bd3.png)

**Comment by heroboy** [comment]
我猜因为你的用户名是中文的。

**Comment by MicroCBer** [comment]
理论上应该已经修复，需要进行测试

**Comment by LLLisheng** [comment]
如何测试？需要我配合你吗？

**Comment by sforman2861597** [comment]
无论是使用管理员身份打开，还是使用那个以msix方式安装的网易云，都会出现这种情况

**Comment by MicroCBer** [comment]
> 无论是使用管理员身份打开，还是使用那个以msix方式安装的网易云，都会出现这种情况

是之前中文用户名的遗留问题

如果有空的话可以在群里私信我todesk控制码 调试一下

**Comment by sforman2861597** [comment]
为啥把用户名改成中文还是不好使😢

**Comment by MicroCBer** [comment]
> 为啥把用户名改成中文还是不好使😢

为什么要把用户名改成中文...

这个问题是 之前不支持windows用户名含有中文的用户使用

**Comment by sforman2861597** [comment]
打错字了.........
把网易云的用户名改成了英文发现不能用
windows用户名是吧
我试试😂😂

**Comment by sforman2861597** [comment]
改了一下个人文件夹的用户名，可以正常使用了
感谢大佬😁

**Comment by MicroCBer** [comment]
已确认修复
