### ISSUE TITLE
插件不能正常加载

### ISSUE THREAD

**Issue by sforman2861597** [MicroCBer/BetterNCM#151]
管理员模式打开也一样，使用msix那个安装也一样
![image](https://user-images.githubusercontent.com/121373973/210055659-fe4cdb97-f690-4ebd-8f9c-66efe460e7fc.png)
![image](https://user-images.githubusercontent.com/121373973/210055707-cc32ab64-ffbe-4e71-9530-1f951683f128.png)

**Comment by MicroCBer** [comment]
duplicated #150
