### ISSUE TITLE
安装后发现无法打开网易云

### ISSUE THREAD

**Issue by Blanchot-satou** [MicroCBer/BetterNCM#159]
下载应用安装后网易云无法正常打开

**Comment by Blanchot-satou** [comment]
BetterNCM II v0.2.5依然可用，最新的v1.0.0安装后无法正常运行网易云

**Comment by SeeYouTomm** [comment]
同样的问题..尝试删除C:\\betterncm 文件夹也没有效果

**Comment by SeeYouTomm** [comment]
一样的问题，将c:\\betterncm 和betterncm.dll 删掉重装之后就可以用了，供参考。

**Comment by Yefori-Go** [comment]
> 

有用，感谢

**Comment by Yefori-Go** [comment]
> 一样的问题，将c:\betterncm 和betterncm.dll 删掉重装之后就可以用了，供参考。

有用，感谢

**Comment by YuriBrightan** [comment]
> 一样的问题，将c:\betterncm 和betterncm.dll 删掉重装之后就可以用了，供参考。

测试有效 感谢

**Comment by Hi-FishU** [comment]
> 一样的问题，将c:\betterncm 和betterncm.dll 删掉重装之后就可以用了，供参考。

找不到c:\betterncm这个目录来着

**Comment by Hi-FishU** [comment]
> 

在用户目录下
