### ISSUE TITLE
优化进程占用

### ISSUE THREAD

**Issue by CheongSzesuen** [MicroCBer/BetterNCM#162]
BetterNCM的CPU占用太高了，希望可以优化一下，做的更好！

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/211401038-86ce6d75-fb17-4649-aec7-aca9f4c68ca5.png)
huh

**Comment by Cheong-Szesuen** [comment]
啧，My fault. 今天又加了BetterNCM看了下，加油加油，做得很好！
