### ISSUE TITLE
BGEnhanced在Win11下无法正常设置背景

### ISSUE THREAD

**Issue by dontknowhy** [MicroCBer/BetterNCM#165]
BGEnhanced除了底色能改之外全部无法调节（包括透明度
系统：Win11 22621.1037
比较罕见的是我的Win11圆角插件不在，也找不到（
有时BGEnhanced确实能工作，但实时模糊没有，背景错乱并且正常状态下没什么可能打开

**Comment by dontknowhy** [comment]
PS:我从Action下载了最新的BetterNCM，没效果

**Comment by MicroCBer** [comment]
> BGEnhanced除了底色能改之外全部无法调节（包括透明度 系统：Win11 22621.1037 比较罕见的是我的Win11圆角插件不在，也找不到（ 有时BGEnhanced确实能工作，但实时模糊没有，背景错乱并且正常状态下没什么可能打开

不是很能看懂……

**Comment by dontknowhy** [comment]
就是说BGEnhanced不工作了，就这么简单
________________________________
发件人: MicroBlock ***@***.***>
发送时间: 2023年1月12日 0:00
收件人: MicroCBer/BetterNCM ***@***.***>
抄送: dontknowhy ***@***.***>; Author ***@***.***>
主题: Re: [MicroCBer/BetterNCM] BGEnhanced在Win11下无法正常设置背景 (Issue #165)


BGEnhanced除了底色能改之外全部无法调节（包括透明度 系统：Win11 22621.1037 比较罕见的是我的Win11圆角插件不在，也找不到（ 有时BGEnhanced确实能工作，但实时模糊没有，背景错乱并且正常状态下没什么可能打开

不是很能看懂……

―

**Comment by MicroCBer** [comment]
请尝试最新版 BGEnhanced，检查问题是否已修复
