### ISSUE TITLE
播放中和主界面的不一致

### ISSUE THREAD

**Issue by KJH-x** [MicroCBer/BetterNCM#167]
![截图_20230105093228](https://user-images.githubusercontent.com/53437291/210681418-f7cdb51b-6a0b-4e0b-ab69-cba2abf124f2.png)
![截图_20230105093420](https://user-images.githubusercontent.com/53437291/210681692-da84f9eb-da64-4b3a-89e7-44201cf540f8.png)
感谢优秀的插件加载器以及插件

如图，如题，想问下【播放页面】的【底部播放条】样式是受哪个插件控制，我好去对应插件下反馈，目前切换时样式割裂感严重。

使用的插件：
- PluginMarket
- Apple Music-like ...
- Material You
- ~~StyleSnippet(未修改)~~
- TinyNCM
- HideScrollbar

**Comment by MicroCBer** [comment]
material you目前未完成播放页面的制作

你可以选择在material you的设置中关闭 *在播放页禁用主题* 然后使用stylesnippets中的修改进度条位置功能

**Comment by KJH-x** [comment]
好的，感谢回复
