### ISSUE TITLE
无设置选项

### ISSUE THREAD

**Issue by Faneter** [MicroCBer/BetterNCM#168]
![image](https://user-images.githubusercontent.com/46913596/210681768-03883d89-f2db-4b29-b313-b024800dad84.png)

控制台报错如图
![屏幕截图_20230105_093314](https://user-images.githubusercontent.com/46913596/210681841-e82e3019-bda0-4b34-81f9-23585b2b159d.png)

[已按照该链接处理端口，但无效果](https://github.com/MicroCBer/BetterNCM/issues/123)

疑似CORS跨域问题

**Comment by MicroCBer** [comment]
新版设置页面换位置了.. 不在这了
