### ISSUE TITLE
卸载material you后配色错乱

### ISSUE THREAD

**Issue by laorentou666** [MicroCBer/BetterNCM#172]
![image](https://user-images.githubusercontent.com/89732460/211141206-ee9491ad-06f4-43fd-b84c-9850b3e89f78.png)
![image](https://user-images.githubusercontent.com/89732460/211141216-089106be-ab91-4ba4-9833-753c2e5db2d7.png)
插件列表：
![image](https://user-images.githubusercontent.com/89732460/211141246-e509a983-ee5c-4547-a88c-f90f1eb8e766.png)

**Comment by laorentou666** [comment]
安装MoTheme解决了 可以Close了

**Comment by MicroCBer** [comment]
其实只是bgenhanced需要安装任意主题
