### ISSUE TITLE
[功能请求]专辑内歌曲衔接功能

### ISSUE THREAD

**Issue by feng716** [MicroCBer/BetterNCM#178]
某些专辑内歌曲在安卓客户端可以自动衔接（对于某些可衔接专辑来说，如AVB的76） 但此功能在PC上没有  
是否可以实现类似的功能

**Comment by MicroCBer** [comment]
歌曲的播放是在cpp端进行的 有点难度

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/224485071-19566dc0-9528-4355-a2fe-6bc41c96fe25.png)
