### ISSUE TITLE
[功能改进] 希望已安装插件侧边栏页面能看到插件版本以及当前最新版本, 便于更新插件

### ISSUE THREAD

**Issue by achieve-dream1221** [MicroCBer/BetterNCM#179]
![image](https://user-images.githubusercontent.com/57209087/211191951-344e18f7-4801-4a13-ba31-129b021892f8.png)

# [bug] Material You主题已经安装, 但是插件商店仍显示下载, 已安装页面也没有Material You
![image](https://user-images.githubusercontent.com/57209087/211192059-1d883ec9-acb2-41fd-965b-c886e21dc26b.png)
## 并且版本为最新版
![image](https://user-images.githubusercontent.com/57209087/211192176-87d1b391-b95e-4fca-9e0a-6e77b1fb3483.png)
![image](https://user-images.githubusercontent.com/57209087/211192217-d4b559eb-578a-4278-8e5c-16c334c22ace.png)

**Comment by achieve-dream1221** [comment]
# 更新过后的插件, 希望能删除之前版本的插件, 虽说不大, 但是当插件更新多时, 文件会产生冗余
![image](https://user-images.githubusercontent.com/57209087/211192375-948bab5a-ee41-444e-b5d3-b67be2814a6b.png)

**Comment by MicroCBer** [comment]
@solstice23

**Comment by solstice23** [comment]
@achieve-dream1221 能否提供 F12 控制台 loadedPlugins 展开后的截图

**Comment by achieve-dream1221** [comment]
> 
@solstice23 
![image](https://user-images.githubusercontent.com/57209087/211192738-e1c9147c-a4e0-444b-81e2-c0f2eea403ff.png)

**Comment by solstice23** [comment]
尝试使用最新版本，https://github.com/MicroCBer/BetterNCM/commit/2f708a5bfebd4a3873843211cb1b8194b6789827 这个 commit 用 slug 作为键值了

**Comment by achieve-dream1221** [comment]
> 尝试使用最新版本，从 [2f708a5](https://github.com/MicroCBer/BetterNCM/commit/2f708a5bfebd4a3873843211cb1b8194b6789827) 这个 commit 开始就用 slug 作为键值了

可是我就是用的1.0.0 pre1最新版
