### ISSUE TITLE
切换歌曲时歌曲缩略图会变红

### ISSUE THREAD

**Issue by Si-Jiu49** [MicroCBer/BetterNCM#18]
每次切换歌曲时缩略图会变红再变回去 详见：「2022-08-21_12-44-27.mkv」https://www.aliyundrive.com/s/zJ3Es5mgJTN 提取码: 1ru2

**Comment by mo-jinran** [comment]
小问题。等待下个版本我把这些细节都搞好

**Comment by han-1112** [comment]
挺不错的，原来那个只能用用纯色背景，现在挺好看的

**Comment by mo-jinran** [comment]
> 每次切换歌曲时缩略图会变红再变回去 详见：「2022-08-21_12-44-27.mkv」https://www.aliyundrive.com/s/zJ3Es5mgJTN 提取码: 1ru2

修复了，在插件商店内更新

**Comment by Si-Jiu49** [comment]
在我的电脑上变红问题仍然存在
