### ISSUE TITLE
正在播放页面的背景没了。（只安装了Material you主题）

### ISSUE THREAD

**Issue by luobr233** [MicroCBer/BetterNCM#184]
正在播放页面的背景没了。
只安装了Material you主题和UnblockNeteaseMusic插件（没启用）

- BetterNCM界面：

![image](https://user-images.githubusercontent.com/58586966/211490757-5e2caaab-4f1e-4d1b-a017-b838c19023ce.png)

- 主界面：

![image](https://user-images.githubusercontent.com/58586966/211490641-7da43de4-7830-459c-ba94-c803f04661c2.png)

- 正在播放页面：

![image](https://user-images.githubusercontent.com/58586966/211490689-809ce9a5-18a9-4597-a9a6-ef2dc542fd40.png)

- 控制台：

![image](https://user-images.githubusercontent.com/58586966/211492744-6d1a804c-5860-4bfe-84fe-a1d86d1271f4.png)

- BetterNCM版本：1.0.0

- 网易云音乐版本：2.10.6(Build:200601)(Patch:1:d3fe8dd)

- Windows 规格：

版本	Windows 10 企业版 LTSC
版本号	21H2
操作系统内部版本	19044.2364

**Comment by zhuzixuan2019241** [comment]
可以尝试在Material You设置中关闭：在正在播放页面中不应用主题
![image](https://user-images.githubusercontent.com/68471692/211723415-6eb82394-0912-4bb6-9878-f88358ab73dc.png)

**Comment by luobr233** [comment]
我按照这个方法尝试了一下，好像还是不太行。
![image](https://user-images.githubusercontent.com/58586966/211754710-702a3ee1-2cef-4161-8c9d-4b992ed8a537.png)

我尝试重新安装网易云音乐、BetterNCM和Material you主题，更奇怪的问题出现了。

- 主界面：

![image](https://user-images.githubusercontent.com/58586966/211757168-a03b0551-1dfb-4779-b807-527839763c64.png)

- 正在播放页面：

![image](https://user-images.githubusercontent.com/58586966/211757281-782abf63-a59c-4b2b-be9d-9182982d7180.png)

虽然不知道是什么问题，但重新启动了4次网易云音乐，主界面就恢复正常了。可是原本的问题还是没有得到解决。

- 正在播放页面（启用了“在正在播放页面中不应用主题”）：

![image](https://user-images.githubusercontent.com/58586966/211758409-0fa99044-168b-4950-bf3e-c276a8c5b4e2.png)

- 正在播放页面（关闭了“在正在播放页面中不应用主题”）：

![image](https://user-images.githubusercontent.com/58586966/211758988-ed0ae210-db28-4a69-b7e8-a190d14c8882.png)

**Comment by luobr233** [comment]
我用BetterNCM Installer 1.0.2卸载了BetterNCM 1.0.0装了0.2.5，问题还是没有解决。

**Comment by MicroCBer** [comment]
@solstice23

**Comment by solstice23** [comment]
无法复现

**Comment by luobr233** [comment]
是的，是2.10.6(Build:200601)(Patch:1:d3fe8dd)
![image](https://user-images.githubusercontent.com/58586966/211792033-f997fb34-0eff-4ab2-8af4-0679c3678fad.png)

**Comment by luobr233** [comment]
这是我遇到的情况：
（这是我上传的一个1.75MB大小的视频）
（Github直连加载缓慢，可能需要用梯子。）
https://user-images.githubusercontent.com/58586966/211798255-4f8ec7b0-1099-4e3d-a42d-a2b77ef8b7e3.mp4

**Comment by solstice23** [comment]
能远程吗

**Comment by luobr233** [comment]
要怎么联系你？
