### ISSUE TITLE
安装了最新版的插件后发现插件市场没有解灰那个了

### ISSUE THREAD

**Issue by Aspirin2002** [MicroCBer/BetterNCM#185]
安装了最新版的插件后发现插件市场没有解灰那个了，这个是什么情况

**Comment by Steve-xmh** [comment]
自己研究，不做叙述

**Comment by Aspirin2002** [comment]
> 自己研究，不做说说

自己搭建的解灰老是出问题，后来一直都用的插件市场里的，我更新完发现没了，方便的话可以教一下吗

**Comment by Cccc-owo** [comment]
> > 自己研究，不做说说
> 
> 自己搭建的解灰老是出问题，后来一直都用的插件市场里的，我更新完发现没了，方便的话可以教一下吗

可以考虑使用[这个以Qt构建的解灰](https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic/releases)，支持开机自启

**Comment by MicroCBer** [comment]
[UnblockCloudMusic_0.1.7.zip](https://github.com/MicroCBer/BetterNCM/files/10392366/UnblockCloudMusic_0.1.7.zip)

自行研究用法

**Comment by HUGOSAMA1121** [comment]
> [UnblockCloudMusic_0.1.7.zip](https://github.com/MicroCBer/BetterNCM/files/10392366/UnblockCloudMusic_0.1.7.zip)
> 
> 自行研究用法

感谢！
