### ISSUE TITLE
点此更新无法更新

### ISSUE THREAD

**Issue by wy164519317** [MicroCBer/BetterNCM#189]
点此更新后，网易云会重启，但无法更新成功。

**Comment by wy164519317** [comment]
![image](https://user-images.githubusercontent.com/51292769/212008267-df7010dd-dc06-4a5a-8505-8b9571df4165.png)

**Comment by feng716** [comment]
用Installer卸载后安装可能可以

**Comment by wy164519317** [comment]
> 用Installer卸载后安装可能可以

感谢解答

**Comment by MicroCBer** [comment]
旧版就不用发issue说了……
