### ISSUE TITLE
MoTheme插件功能窗口模式下功能显示不全

### ISSUE THREAD

**Issue by wy164519317** [MicroCBer/BetterNCM#190]
窗口：
![image](https://user-images.githubusercontent.com/51292769/212049083-b47e034e-654a-4e25-8a68-69de50741144.png)
全屏：
![image](https://user-images.githubusercontent.com/51292769/212049140-4cdd49f6-4671-4201-801e-ac7d208bdc09.png)

**Comment by Thesouth-EricWang** [comment]
目前我发现不光MoTheme有问题，即使卸载主题插件窗口模式下功能依旧会显示不全

**Comment by mo-jinran** [comment]
这不是主题问题，这是Apple Music-like插件问题

**Comment by mo-jinran** [comment]
@Steve-xmh 快出来修

**Comment by Steve-xmh** [comment]
> @Steve-xmh 快出来修

https://github.com/Steve-xmh/applemusic-like-lyrics/issues/16
https://github.com/Steve-xmh/applemusic-like-lyrics/issues/15
https://github.com/Steve-xmh/applemusic-like-lyrics/releases/tag/v1.5.2
