### ISSUE TITLE
重载插件后, 正在播放按钮变为暂停, 但是仍然在播放

### ISSUE THREAD

**Issue by achieve-dream1221** [MicroCBer/BetterNCM#191]
# 版本: 1.0 pre-2
# 重载前
![image](https://user-images.githubusercontent.com/57209087/212076043-90065e09-4ede-408d-8f41-3ff77726c07b.png)
# 重载后
![image](https://user-images.githubusercontent.com/57209087/212074913-0e8367cb-2621-48da-a64f-464ccfa4ed23.png)
# 预期效果
歌曲仍然播放, 并且播放按钮不变

**Comment by MicroCBer** [comment]
网易云自身问题 后面看看怎么给他修一下

**Comment by MicroCBer** [comment]
对用户体验影响不大 先不打算修了
