### ISSUE TITLE
2.10.6版本会出现点击当前播放列表点一下出来一下，随后消失的情况。

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#192]
详细版本号为2.10.6（build:200601）(patch:1:d3fe8dd)
具体情况为点击播放列表，点一下出来一下，随即消失。
另外，无法正常更新新版本。

**Comment by MicroCBer** [comment]
无法正常更新新版本?

**Comment by luotianyiismywife** [comment]
是的，我录了一个视频。

https://user-images.githubusercontent.com/81459639/212136499-5938ba64-b778-467b-972b-656f8f0e13d5.mp4

**Comment by MicroCBer** [comment]
0.2.5已不再维护

**Comment by luotianyiismywife** [comment]
emmmm，那我手动更新一下吧

**Comment by luotianyiismywife** [comment]
更新之后问题依旧存在。
