### ISSUE TITLE
安装MoTheme插件之后渲染出现问题，有大量的黑色色块

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#193]
如题，视频如下，卸载后恢复正常

https://user-images.githubusercontent.com/81459639/212141929-650a80ab-2f48-4f06-b8ee-af180140371b.mp4

**Comment by luotianyiismywife** [comment]
播放列表消失的情况依旧存在。

**Comment by MicroCBer** [comment]
@mo-jinran

**Comment by mo-jinran** [comment]
看起来并没有安装MoTheme主题，而这种情况一般是由于只安装了BGEnhanced插件所导致。BGEnhanced需要安装主题才可正常使用

**Comment by MicroCBer** [comment]
似乎确实是 BGEnhanced 在不添加背景时默认显示黑色的问题，请等待重写或摸黑添加背景

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
已修复，BGEnhanced默认背景色不再是黑色
