### ISSUE TITLE
安装插件之后，在设置中更换了下载目录重启时无法正常重启

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#194]
想要更新一下下载目录，更换路径之后提示需要重启，在不安装插件的情况下可以正常重启，但是安装了插件之后程序自己关闭自己之后就无法自动打开了，手动打开之后发现更改的其他设置项目也没有保存。

**Comment by MicroCBer** [comment]
duplicated #211
