### ISSUE TITLE
MoTheme插件存在无法正确保存背景图片的情况

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#195]
![图片](https://user-images.githubusercontent.com/81459639/212147386-ae082a6b-56cc-4e65-83bf-3fc781481279.png)
在这里设置了背景图片之后退出软件，再次打开的时候背景图片设置失效。但是在temp里还是有
![图片](https://user-images.githubusercontent.com/81459639/212147660-86bb7134-0896-43fd-b224-dac4921af4ef.png)

**Comment by luotianyiismywife** [comment]
目前已排除图片过大导致的加载时间问题

**Comment by cow-your-sister** [comment]
我也遇到了这个问题 ，在BetterNCM1.0.0pre版本上

**Comment by luotianyiismywife** [comment]
![图片](https://user-images.githubusercontent.com/81459639/212148422-9ef58791-95ce-4750-862c-dcbbfae22840.png)

**Comment by cow-your-sister** [comment]
> ![图片](https://user-images.githubusercontent.com/81459639/212148422-9ef58791-95ce-4750-862c-dcbbfae22840.png)

对，每次重启后就会变成默认的url，但是也没有加载这个url指向的图片

**Comment by zuilemt** [comment]
用BGEnhanced插件 主题内的背景不再支持 
作者原话
![image](https://user-images.githubusercontent.com/53639376/212464363-e0238f11-e0bb-4441-a450-4d025f1d0cff.png)

链接：https://github.com/MicroCBer/BetterNCM/issues/174
