### ISSUE TITLE
使用ActionEnhancement插件将鼠标放在音量图标上使用滚轮调节音量时音量条无法正确的移动

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#196]
将鼠标放在音量图标上使用滚轮调节音量时音量可以变大变小，但是变化不均匀。
如果使用鼠标拖动音量条则向上托音量增加，向下滑音量降低。但是滑块会回到原来的位置
eg

https://user-images.githubusercontent.com/81459639/212156880-9fd0330a-face-4a49-8433-f40ee3f1afe3.mp4
鼠标不动且悬停在音量图标时为在尝试使用滚轮调整音量。

**Comment by MicroCBer** [comment]
fixed
