### ISSUE TITLE
RefinedNoPlaying插件进入歌词界面过程中底部音乐栏会闪烁

### ISSUE THREAD

**Issue by QingmingHaruaki** [MicroCBer/BetterNCM#199]
![image](https://user-images.githubusercontent.com/122613083/212318871-adf5074a-4f73-49b4-b04c-4c076f3a4635.png)
弹出过程中的截图为上（截了好几次终于给我卡上了

**Comment by Marce1ek** [comment]
+1

**Comment by MicroCBer** [comment]
@solstice23
