### ISSUE TITLE
一些主题问题（bug）

### ISSUE THREAD

**Issue by Alirea10** [MicroCBer/BetterNCM#20]
![image](https://user-images.githubusercontent.com/111880868/186164216-0390ee2f-acab-49b9-8808-8d2a5a284559.png)
如图所示，这是私人FM界面，使用插件为unbounded去模糊版主题。
![image](https://user-images.githubusercontent.com/111880868/186164580-1857f208-6bd5-41d7-a7aa-467e232784e8.png)
![image](https://user-images.githubusercontent.com/111880868/186164631-dceca7e3-91bf-4a8e-85c6-2887fa1a4218.png)
然后就是stykesheetloader插件的字体颜色切换还是不能把很多文字改变为黑色，这可能是主题的适配问题亦或是wyy的问题，一并提交看看

**Comment by MicroCBer** [comment]
已修复，请更新至Unbounded 0.1.1
