### ISSUE TITLE
歌单滚动问题

### ISSUE THREAD

**Issue by KeeLee2005** [MicroCBer/BetterNCM#200]
最大化时，在歌单中，无论是用鼠标还是滑动滚动条，滚动总会在某些地方跳一下，而且也无法滚动到最底端。
这个问题似乎跟歌单的数量无关，无论是一百多首还是四百多首都会触发。
最易于描述的直观的现象就是总有一个地方滚动条到不了，要么闪到前面，要么闪到后面；当列表为最底端时滚动条和列表反复横跳。
向下还原后列表可划到最底端，另一个问题依然存在。
[2023-01-13 21-49-11 - Trim(1).webm](https://user-images.githubusercontent.com/92454987/212336446-eb3552de-359e-4022-966e-38df1cc21872.webm)
如视频所示，右侧滚动条
我安装的插件似乎有点多，也不太方便定位问题所在。

感谢作者的付出！

**Comment by KeeLee2005** [comment]
网易云版本2.10.6
BetterNCM版本BetterNCM 1.0.0 Pre2
已安装的插件有
ActionEnhancement-0.1.4
Apple-Musiclike-lyrics-1.5.2
BGEnhanced-0.1.9
FluentProgressBar-0.1.3
InfLink-0.1.5
MikuPlugin-0.1.1
MoTheme-1.1.10
RoundCornerNCM-0.1.1
StyleSnippet-0.1.0
VisualRecord-1.0.1
What-is-the-cover-of-this-music-2.0.1

因为这个问题不是很影响使用，只是整理歌单的时候比较麻烦。我也没遇到其他问题，正式版和测试版都很稳定。

**Comment by solstice23** [comment]
因为插件更改了歌单列表每一行的高度，网易云为了性能会把溢出屏幕的部分隐藏并用空白块占位，空白块的高度是用之前的高度计算的，所以会跳
Material You 主题已经解决了这个问题
