### ISSUE TITLE
在白色主题下无法正常切换黑色字体

### ISSUE THREAD

**Issue by zuilemt** [MicroCBer/BetterNCM#202]
如题 白色主题下无法正常显示切换黑色字体
![微信截图_20230114165000](https://user-images.githubusercontent.com/53639376/212464227-69d72fe7-34f8-4110-8750-fd870d93d955.png)
![微信截图_20230114165844](https://user-images.githubusercontent.com/53639376/212464434-88c48067-695b-4847-b3ea-f7e13b310623.png)
 
上为白色主题 黑字
![微信截图_20230114165015](https://user-images.githubusercontent.com/53639376/212464228-b14cc6c8-1218-40df-8df0-b10b2c34bd47.png)
上为黑色主题 白字

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/229214454-32595d99-50f3-4e95-bf2c-a478de6fb4d6.png)
