### ISSUE TITLE
启用LibFrontendPlay插件后音乐无法正常播放（无法播放

### ISSUE THREAD

**Issue by QingmingHaruaki** [MicroCBer/BetterNCM#205]
![image](https://user-images.githubusercontent.com/122613083/212520907-11dcb81c-cd30-4d7c-a808-f5e53dd44564.png)
如上，音乐无法播放，将启用选项关掉后就可以正常播放了，这个不知道是我的问题还是插件的问题

**Comment by MicroCBer** [comment]
libfrontendplay不支持播放本地.ncm格式的歌曲

**Comment by MicroCBer** [comment]
libfrontendplay不支持播放本地.ncm格式的歌曲

**Comment by QingmingHaruaki** [comment]
好的，也请标注在插件内进行提示
