### ISSUE TITLE
应该是RefinedNowPlaying插件和什么冲突了导致全屏错误

### ISSUE THREAD

**Issue by QingmingHaruaki** [MicroCBer/BetterNCM#206]
![image](https://user-images.githubusercontent.com/122613083/212521549-3a19023f-2806-49a8-9414-9626631f2333.png)
如上

**Comment by MicroCBer** [comment]
@solstice23

**Comment by FKcrown** [comment]
![image](https://user-images.githubusercontent.com/79238509/212800986-26b6bac9-ba89-4870-b97c-86593f8556d3.png)
应该是和这个选项冲突了
