### ISSUE TITLE
【特性反馈】一些显示问题

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#208]
已安装插件列表：
![image](https://user-images.githubusercontent.com/119386507/212527569-6d439390-be8e-43c9-9314-355c49148261.png)

第一个是BGEnchanced和Meterial You插件冲突（卸载BGEnchanced后正常）
![image](https://user-images.githubusercontent.com/119386507/212527542-9fc24a30-69f0-4bea-9762-779690d380c3.png)
以及和其一并变明显的小显示问题
![image](https://user-images.githubusercontent.com/119386507/212527896-ef57c0a0-afa3-436e-8419-a5f60ddaecca.png)

然后就是apple Music-Like Lyrics和SimpleAudioVisualizer的覆盖（十分奇妙）
https://user-images.githubusercontent.com/119386507/212527763-4abb50f3-d586-4053-a4af-ee924ba62765.mp4
以及一个更令我f费解的问题
https://user-images.githubusercontent.com/119386507/212527969-95fb6dbf-16f6-4d78-a84b-a7ea838f6b8a.mp4
plugins 文件夹正常
![image](https://user-images.githubusercontent.com/119386507/212527986-00771813-723d-466c-bbcf-0a21e71ed43f.png)
给我人都整不会了

**Comment by ConCose** [comment]
上文剃刀的最后一个问题在重启Betterncm以后正常（

**Comment by MicroCBer** [comment]
第二个：每个 HTMLMediaElement 只能绑定到唯一一个 MediaElementSourceNode 上，功能重叠了不打算修，后面可能改成 LibFrontendPlay 直接提供相关回调函数

**Comment by MicroCBer** [comment]
第一个：
![image](https://user-images.githubusercontent.com/66859419/212528508-8ff3dc35-c6d5-4ba0-ad8b-9b080a568c01.png)
默认会覆盖 main-player 样式，加个渐变

现在已提供了设置项
![image](https://user-images.githubusercontent.com/66859419/212528528-48ac3efb-3254-4d39-a5ea-77aa8867292d.png)

**Comment by MicroCBer** [comment]
(应该) 已修复 94cf3c
