### ISSUE TITLE
[ 功能建议 ] 云音乐整体字体大小更改

### ISSUE THREAD

**Issue by Satan123231** [MicroCBer/BetterNCM#209]
橘子能不能搞个**更改云音乐整体字体大小**的，原版对字体的大小只有部分字体用起来还算合适，当用自己喜欢的一些手写字体或者如行楷、楷体等就有点太小了看不清。如果可以**更改整体**或者**自定义局部字体大小**就好了~

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215687346-71cf5732-4852-48d8-9833-77e421ebdaf9.png)
