### ISSUE TITLE
在最小化后过一段时间，恢复窗口后界面卡死

### ISSUE THREAD

**Issue by mo-jinran** [MicroCBer/BetterNCM#212]
CPU占用率很高，内存占用率感觉在缓慢上升
然后等了一会，窗口开始有反应
但是界面的某些地方会有问题

**Comment by HanEric666** [comment]
我也遇到了这个情况，音量啥的调整不了，要按f12f5重载才能恢复正常:(

**Comment by Steve-xmh** [comment]
补充一下，在卡死的时候恢复窗口会卡死，但是久置一会之后就会从卡死状态恢复，但是仍然有卡顿出现
尝试使用 Performance 做性能监视的时候崩溃了所以没有获取到什么有价值的信息。

**Comment by misaka10032w** [comment]
一样问题，我是如果播放时候息屏了，两首歌之间会间隔好几分钟，唤醒之后会卡死几分钟无法操作

**Comment by MicroCBer** [comment]
使用
https://microblock.lanzouy.com/iMwxT13j0kze
