### ISSUE TITLE
底部排版错乱

### ISSUE THREAD

**Issue by laorentou666** [MicroCBer/BetterNCM#217]
底部排版错乱

![image](https://user-images.githubusercontent.com/89732460/213472352-481f10fa-32cf-428f-bb16-1e4cae9e0574.png)
![image](https://user-images.githubusercontent.com/89732460/213472444-3c7b42f3-bd58-4b3f-93a7-20d5ab6d1423.png)

**Comment by laorentou666** [comment]
删除SimpleAudioVisualizer解决了

**Comment by MicroCBer** [comment]
请将该选项关闭
![image](https://user-images.githubusercontent.com/66859419/213538165-e8bbb525-76d5-45d9-8716-7c245f8651d6.png)

（若已关闭则开启后重新关闭）
