### ISSUE TITLE
增加低版本兼容 ＞ 2.9.10

### ISSUE THREAD

**Issue by kikozz** [MicroCBer/BetterNCM#22]
网易云在 ＞ 2.9.10 版本时无法使用 UnblockNeteaseMusic (据开发者说是因为高版本修改了API导致 UnblockNeteaseMusic 无法兼容 ＞2.9.10 版本) , UnblockNeteaseMusic和BetterNCM同时都想使用 , 有没有让BetterNCM兼容低版本的想法?

**Comment by MicroCBer** [comment]
没有，技术上很难实现，目前版本很多功能基于高版本chrome实现 

不过有个自动下载灰色歌曲并下载到云盘的想法，目前还没开始做

**Comment by MicroCBer** [comment]
一个是Chrome31的cef头文件我没找到，还有一个是代码很多不支持（这个倒是可以通过babel解决）

**Comment by mo-jinran** [comment]
> 网易云在 ＞ 2.9.10 版本时无法使用 UnblockNeteaseMusic (据开发者说是因为高版本修改了API导致 UnblockNeteaseMusic 无法兼容 ＞2.9.10 版本) , UnblockNeteaseMusic和BetterNCM同时都想使用 , 有没有让BetterNCM兼容低版本的想法?

使用https://github.com/UnblockNeteaseMusic/server
