### ISSUE TITLE
Apple Music-like lyrics和SimpleAudioVisualizer不兼容

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#225]
SimpleAudioVisualizer没有起作用

**Comment by MicroCBer** [comment]
AudioContext只允许一对一流

**Comment by MicroCBer** [comment]
![image](http://koi.microblock.cc:5140//files/55e082ddca951e6a203eb43fa75e8a039e3435bb-cd60b970e3131c73cfc32b96f0110ef0.image)![image](http://koi.microblock.cc:5140//files/e1ac7e0d7eda5659f18da46a520bf5cb4bd9d52b-520ae9638b940725a2e344966a7b60bc.image) 只能二选一

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
