### ISSUE TITLE
插件更新失败

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#226]
在插件点击更新且重新加载后插件市场显示没有更新
已知解决方法：先卸载要更新的插件再安装

**Comment by MicroCBer** [comment]
BetterNCM版本?

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Ds1nk** [comment]
1.0.0

**Comment by Ds1nk** [comment]
1.0.0

**Comment by MicroCBer** [comment]
是哪个插件更新失败

**Comment by Ds1nk** [comment]
所有插件都无法更新

**Comment by MicroCBer** [comment]
在更新后文件夹内是否同时出现新老两个插件

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Ds1nk** [comment]
没注意，看什么插件有更新再说

**Comment by QingmingHaruaki** [comment]
更新插件的时候多等一会，然后打开控制台再关掉控制台也可以，无意间发现的

**Comment by Ds1nk** [comment]
不知道为什么修好了qwq
