### ISSUE TITLE
无法使用杜比全景音

### ISSUE THREAD

**Issue by github-tang** [MicroCBer/BetterNCM#227]
启用betterncm之后，如果打开 杜比全景音 就会卡住无法播放（网易云音乐本身运行正常，只是听不了歌）

 - BetterNCM 版本：1.0.0 
 - 网易云音乐版本：2.10.6
 - 网易云音乐 Patch 版本：5ad43a6

**Comment by MicroCBer** [comment]
有没有安装 LibFrontendPlay

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by github-tang** [comment]
有安装，是这个插件的问题吗？我去看一下。

**Comment by github-tang** [comment]
确实是这个插件的问题

**Comment by MicroCBer** [comment]
正常现象，不修
libfrontendplay没法支持各种音效，杜比什么的

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
