### ISSUE TITLE
Material You改进建议

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#228]
1：侧边栏上面的圆角在没安装RoundCornerNCM时隐藏
![image](https://user-images.githubusercontent.com/104675168/213733086-dd7c127b-33ad-4847-8419-99e481c2f7c6.png)
2：歌单里的歌曲显示部分背景在使用BGEnhanced时显示透明
![image](https://user-images.githubusercontent.com/104675168/213733434-2a1aac0d-cc0c-4344-a015-a1af9cb0eadf.png)

**Comment by MicroCBer** [comment]
为什么不用 issue 模板
（那样你就会看到这行字）
### 注意：我们建议您尽可能地在插件 repo 下提交与插件相关的问题报告。但是，如果一个插件没有自己的插件 repo，或您不清楚是哪个插件出了问题，您可以在此提交。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Ds1nk** [comment]
好的
