### ISSUE TITLE
[ Plugin Bug ]网易云启动音量问题

### ISSUE THREAD

**Issue by int-PP** [MicroCBer/BetterNCM#229]
不知道是具体哪个插件的bug，但是重新启动网易云会出现音量不匹配问题。网易云右下角显示的音量是之前保存退出时的音量，但是实际的音量却是100%，每次都需要重新调节。
![QQ截图20230121000213](https://user-images.githubusercontent.com/105854929/213746182-37f36441-96b8-4b34-9f51-4de56e7e4614.png)
这是安装的插件列表。

**Comment by MicroCBer** [comment]
是 libfrontendplay 的问题，这个插件还没支持重新开启后还原音量设置
（很好的提issue方式，爱来自中国）

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by int-PP** [comment]
好的，有后续更新吗？
![%~$W FNBS OH@_I 9{`75Z6](https://user-images.githubusercontent.com/105854929/213862795-ab6daebf-8887-4128-8e3e-06987db1806c.gif)

**Comment by MicroCBer** [comment]
下次更新修一下，现在在倒腾其他的

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by int-PP** [comment]
还有个小建议，因为自定义背景会导致过暗或者过亮，所以会有字体看不清。能不能改成像win桌面那种字体效果，字体后面有点黑色的背景？
![$2DNGAT1 9VNSUZZR~42%HP](https://user-images.githubusercontent.com/105854929/213863208-f188c459-effa-4a33-b393-b911cefcb763.png)

**Comment by MicroCBer** [comment]
请另外发FR（这样发下次要做插件的时候是肯定看不到的……）

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by int-PP** [comment]
草，好的hhh

**Comment by MicroCBer** [comment]
fixed
