### ISSUE TITLE
[功能请求]加入本地实时歌曲API功能

### ISSUE THREAD

**Issue by XiaoMouz** [MicroCBer/BetterNCM#23]
### 功能描述
提供一个正在播放的歌曲、歌手信息、目前播放到的歌词、播放进度、上一句歌词和下一句歌词的本地API接口

### 请求原因
在使用 Wallpaper Engine 壁纸：[哔哩哔哩音频响应壁纸](https://steamcommunity.com/sharedfiles/filedetails/?id=1551961057) 时遇到自带的歌词显示功能失效的情况，如果能提供一个接口搭配使用就好了），只要能够提供相关API我转换一次给壁纸就好了！万分感谢 ！

**Comment by MicroCBer** [comment]
歌曲、歌手信息、播放进度可以直接从点歌姬里面抄

歌词相关的我还在想办法整

**Comment by XiaoMouz** [comment]
> 歌曲、歌手信息、播放进度可以直接从点歌姬里面抄
> 
> 歌词相关的我还在想办法整

好的~
还是苦恼实时歌词，麻烦您了

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/189351178-b729469d-29c2-4f8b-9832-b654c4835f19.png)

**Comment by XiaoMouz** [comment]
> ![image](https://user-images.githubusercontent.com/66859419/189351178-b729469d-29c2-4f8b-9832-b654c4835f19.png)

我的超人！

**Comment by MicroCBer** [comment]
已加入`MoreHooks`

示例代码：
```js
__MOREHOOKS__.events.listeners["lrctimeupdate"]||=[]
__MOREHOOKS__.events.listeners["lrctimeupdate"].push((arguments,result)=>{
    console.log(arguments,result)
})
```

（需要先安装MoreHooks）

**Comment by XiaoMouz** [comment]
> 已加入`MoreHooks`
> 
> 示例代码：
> ```js
> __MOREHOOKS__.events.listeners["lrctimeupdate"]||=[]
> __MOREHOOKS__.events.listeners["lrctimeupdate"].push((arguments,result)=>{
>     console.log(arguments,result)
> })
> ```
> 
> （需要先安装MoreHooks）

非常感谢！

**Comment by MicroCBer** [comment]
可以直接在 https://gitee.com/microblock/better-ncm-v2-data/tree/master/plugin_market 下载 MoreHooks.plugin 并放入插件文件夹
