### ISSUE TITLE
[ FR ] 一个字体的建议

### ISSUE THREAD

**Issue by int-PP** [MicroCBer/BetterNCM#230]
因为有自定义背景功能，背景会出现过亮或者过暗导致字体无法看到，所以提个修改的建议。可不可以像windows桌面的图标字体一样，在字体后面增加黑色的效果，或者有什么其他的替代方案（暂时只想到这一种）。
例如：
网易云音乐在高亮地方字体四周有一点黑色使字体更容易看到
![image](https://user-images.githubusercontent.com/105854929/213863442-fa950fa1-6a9f-4ce7-bf26-2fd0907f13e6.png)

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215687180-1a83e78d-cdd1-4c1d-9a3e-8732dfc90f7f.png)

已在 stylesnippets 中实现

**Comment by int-PP** [comment]
好的，感谢更新
