### ISSUE TITLE
[ Plugin Bug ]

### ISSUE THREAD

**Issue by MMMMMoris** [MicroCBer/BetterNCM#233]
为什么插件的安装目录直接放在C盘的根目录？
强迫症表示无法接受
同时material you这个主题有个问题是左边的侧边栏拉伸调整宽度时，右边的主界面不会跟随调整，而是直接被侧边栏覆盖

**Comment by Steve-xmh** [comment]
多个问题请多开 Issues，不要挤在一个 Issue 里面

只有 C 盘的根路径才是最稳定的
如果需要可以修改 `BETTERNCM_PROFILE` 环境变了来修改插件文件目录。

Material You 插件是有仓库的，可以[在这里找到](https://github.com/solstice23/material-you-theme-netease)

**Comment by MicroCBer** [comment]
1. 这不是 bug 这应该算 FR ( Feature Request )…… 而且 这个功能已经有了 你可以通过修改 BETTERNCM_PROFILE 来修改插件数据路径。
2. Material You 主题的问题你应该在 Material You 主题的 repo 下发 issue，而不是在这，在模板里说的很清楚：
 注意：我们建议您尽可能地在插件 repo 下提交与插件相关的问题报告。但是，如果一个插件没有自己的插件 repo，或您不清楚是哪个插件出了问题，您可以在此提交。

3. 多个问题请开多个 Issue，不然会非常混乱

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
4. 你应该以恰当的方式书写标题 而不是 [ Plugin Bug ] , 这样才能便于开发人员管理，定位问题

**Comment by MicroCBer** [comment]
( duplicated #27 )
