### ISSUE TITLE
与网易云右上角的账户详细信息和通知栏交互后界面闪一下消失

### ISSUE THREAD

**Issue by Alirea10** [MicroCBer/BetterNCM#235]
**Bug 描述**
在点击头像后出现的相关信息或通知图标后相应的界面闪一下就消失了（见图，图中所框的界面瞬间消失，这个图截得很极限）
![image](https://user-images.githubusercontent.com/111880868/213898003-0fbaa550-9370-4b52-a209-f51183d3cce9.png)

**复现步骤**
就...直接点

**相关信息:**
（请完成以下表格的填写）
 - BetterNCM 版本：[  1.0.0 ]
 - 网易云音乐版本：[ 2.10.6 ]
 - 网易云音乐 Patch 版本：[ 5ad43a6 ]
 - 你所装的所有插件列表：![image](https://user-images.githubusercontent.com/111880868/213898056-18606af8-beb3-4c9c-aba6-4583b67b80f5.png)

**Comment by feng-or** [comment]
在StylesheetLoader中切换一下字体颜色应该就可以解决，这个插件是主题自带的，在商店中没有

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Alirea10** [comment]
> 

已解决，感谢
