### ISSUE TITLE
占用CPU过大

### ISSUE THREAD

**Issue by XilyFeAAAA** [MicroCBer/BetterNCM#236]
暗夜精灵7 i7-11800H cpu占用基本在15%
![image](https://user-images.githubusercontent.com/114482179/213904238-94b4c874-6eb3-40f6-8fbd-65c24dee65e6.png)

**Comment by MicroCBer** [comment]
插件列表？

**Comment by XilyFeAAAA** [comment]
> 插件列表？

![image](https://user-images.githubusercontent.com/114482179/214055021-2e3bb5f7-25b9-4945-ad5e-7c5712491896.png)

**Comment by zhuzixuan2019241** [comment]
同样问题
![image](https://user-images.githubusercontent.com/68471692/214081390-e4636faa-b793-47f9-97bb-ba30e6c69ffc.png)
i5-8265U，开了超频，占用一直在25%以上

**Comment by feng-or** [comment]
material you版本多少，卸载之后会不会降低

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by XilyFeAAAA** [comment]
> 

material you版本是2.0.1，卸载之后没有降低。我把插件都重装了一遍，删除StylesheetLoader之后，cpu占用稳定在1-3%，使用RefinedNowPlaying之后拉起播放页，占用会增加到11%左右

**Comment by feng-or** [comment]
StylesheetLoader卸载之后主题部分主题没法正常运行， 在RefinedNowPlaying播放页是占用提高正常

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Steve-xmh** [comment]
这边建议运行性能解析器，方便我们找出卡顿的来源，具体可以以下操作：

（注：建议在 CPU 占用高的时候测试，比较容易捕获到问题）

1. 打开网易云，按下 `F12` 打开开发者工具窗口。
2. 在开发者窗口上方的选项卡中找到 `Performance` 选项卡，点击进入，此时应该长这样：
<img width="930" alt="image" src="https://user-images.githubusercontent.com/39523898/214208452-400a736d-14fb-4068-b37a-88412d6769d3.png">
3. 点击左上角的 `Record` 按钮，开始录制性能解析（电脑可能会有所卡顿，是正常现象）：
<img width="263" alt="image" src="https://user-images.githubusercontent.com/39523898/214208674-02ce7aa8-4104-4679-9849-e422d3292508.png">
4. 大概只需要录制几秒即可，之后点击 `Stop` 按钮停止录制，等待解析器解析数据：
<img width="930" alt="image" src="https://user-images.githubusercontent.com/39523898/214208894-241f2073-8f26-485c-ba0e-734ed7ce1603.png">
5. 完成后会显示解析数据页面，之后点击左上角的 `Save Profile...` 按钮（图标是向下的箭头）保存解析数据：
<img width="930" alt="截屏2023-01-24 11 53 48" src="https://user-images.githubusercontent.com/39523898/214209158-5de22c20-6d0a-48c0-99c1-7a89cdff0bd2.png">
6. 把保存好的解析数据发送给我们，网盘或者链接都可以，这样就可以更好的解决问题了。

**Comment by zhuzixuan2019241** [comment]
> 这边建议运行性能解析器，方便我们找出卡顿的来源，具体可以以下操作：
> 
> （注：建议在 CPU 占用高的时候测试，比较容易捕获到问题）
> 
> 1. 打开网易云，按下 `F12` 打开开发者工具窗口。
> 2. 在开发者窗口上方的选项卡中找到 `Performance` 选项卡，点击进入，此时应该长这样：
> 
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/39523898/214208452-400a736d-14fb-4068-b37a-88412d6769d3.png">
> 
> 3. 点击左上角的 `Record` 按钮，开始录制性能解析（电脑可能会有所卡顿，是正常现象）：
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/39523898/214208674-02ce7aa8-4104-4679-9849-e422d3292508.png">
> 
> 4. 大概只需要录制几秒即可，之后点击 `Stop` 按钮停止录制，等待解析器解析数据：
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/39523898/214208894-241f2073-8f26-485c-ba0e-734ed7ce1603.png">
> 
> 5. 完成后会显示解析数据页面，之后点击左上角的 `Save Profile...` 按钮（图标是向下的箭头）保存解析数据：
> <img alt="截屏2023-01-24 11 53 48" width="930" src="https://user-images.githubusercontent.com/39523898/214209158-5de22c20-6d0a-48c0-99c1-7a89cdff0bd2.png">
> 
> 6. 把保存好的解析数据发送给我们，网盘或者链接都可以，这样就可以更好的解决问题了。
[logs.zip](https://github.com/MicroCBer/BetterNCM/files/10496315/logs.zip)
里面的3个log文件不光复现了cpu占用率超高，还有占有率高带来的卡顿、不加载的问题

**Comment by zhuzixuan2019241** [comment]
卸载BetterNCM后cpu使用率稳定在25%以下，安装后稳定大于40%，时不时超过50%

**Comment by MicroCBer** [comment]
请暂时卸载所有插件，观察卸载后还能复现吗

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by zhuzixuan2019241** [comment]
> material you版本多少，卸载之后会不会降低
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).
卸载之后降低5%左右，不显著

**Comment by zhuzixuan2019241** [comment]
猜测可能与
![image](https://user-images.githubusercontent.com/68471692/214487035-b3870d0d-6501-4986-9648-75b5980cf2e8.png)
有关。关闭此选项后卡顿有一定缓解

**Comment by Steve-xmh** [comment]
> 猜测可能与 ![image](https://user-images.githubusercontent.com/68471692/214487035-b3870d0d-6501-4986-9648-75b5980cf2e8.png) 有关。关闭此选项后卡顿有一定缓解

这个沉浸主题色会计算专辑图片的主要颜色，计算时长会因专辑图片大小而指数增长。
可以通过关闭它或调小专辑图大小来缓解切换歌曲时的卡顿问题。
虽然这个应该是造成卡顿的原因之一，但是刚刚看了一遍你上传的性能日志，可能不止是这个功能的问题，具体还要再分析一下。

**Comment by zhuzixuan2019241** [comment]
> > 猜测可能与 ![image](https://user-images.githubusercontent.com/68471692/214487035-b3870d0d-6501-4986-9648-75b5980cf2e8.png) 有关。关闭此选项后卡顿有一定缓解
> 
> 这个沉浸主题色会计算专辑图片的主要颜色，计算时长会因专辑图片大小而指数增长。 可以通过关闭它或调小专辑图大小来缓解切换歌曲时的卡顿问题。 虽然这个应该是造成卡顿的原因之一，但是刚刚看了一遍你上传的性能日志，可能不止是这个功能的问题，具体还要再分析一下。

ok辛苦了

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/214514957-d18e94f5-9390-4478-979e-bf47523381e8.png)

昨天更新的版本 该选项会预先压缩图片

**Comment by zhuzixuan2019241** [comment]
> 

那可能就是别的问题了，我今天测试之前先把它更到了最新
![image](https://user-images.githubusercontent.com/68471692/214515926-f48d7dfc-de56-441b-998a-00b90fe3e5b9.png)

**Comment by zhuzixuan2019241** [comment]
所有的测试和log都基于最新版的BetterNCM和插件

**Comment by zhuzixuan2019241** [comment]
这是我今天用最新的1.20版本的占用，发现相比1.10占用变高了，请问能分析一下问题吗？
[Performance 23.5.20.zip](https://github.com/MicroCBer/BetterNCM/files/11521707/Performance.23.5.20.zip)
![image](https://github.com/MicroCBer/BetterNCM/assets/68471692/247dae7a-42d3-4251-a073-f1e091d5d813)

**Comment by MicroCBer** [comment]
使用
https://microblock.lanzouy.com/iMwxT13j0kze

**Comment by zhuzixuan2019241** [comment]
> 使用 https://microblock.lanzouy.com/iMwxT13j0kze

旧版wyy2.10.xx能用吗？
3.0插件适配太少了
