### ISSUE TITLE
BGEnhanced无法显示视频背景

### ISSUE THREAD

**Issue by DaysMatter** [MicroCBer/BetterNCM#238]
### Bug 描述

最近更新BGEnhanced插件的新UI版本后就无法显示视频背景了，以前的版本是可以显示的，另外其他插件没有动过也没有新安装有冲突的。

### 复现步骤

添加视频不显示

### 期望行为

希望修复一下，谢谢。

### 屏幕截图

![屏幕截图_20230124_071610](https://user-images.githubusercontent.com/123423959/214175995-c73acc4b-fd2c-4cc7-90d8-a9456392b8fd.png)
![屏幕截图_20230124_072703](https://user-images.githubusercontent.com/123423959/214176003-e2dc6f2c-3a50-41be-ab54-fa383db61ac0.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![屏幕截图_20230124_072703](https://user-images.githubusercontent.com/123423959/214176056-e566f1de-f2ef-4243-9146-dd454a3ac4df.png)

**Comment by feng-or** [comment]
视频路径不能有中文，包括文件名

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by DaysMatter** [comment]
> 视频路径不能有中文，包括文件名
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

原来如此，谢谢。

**Comment by MicroCBer** [comment]
中文路径的问题已经在新版 betterncm 修复了，可以安装 nightly 版本试试

**Comment by Cheisse** [comment]
如果只适配1.0.0版本，可以把图片放在桌面加载完了再删除
![屏幕截图_20230128_081917](https://user-images.githubusercontent.com/123783786/215229298-b1200cd1-f903-480d-b725-f1f62eff6016.png)
