### ISSUE TITLE
[ Bug ] 重载插件时正在播放的音乐会丢失进度条状态

### ISSUE THREAD

**Issue by Puiching-Memory** [MicroCBer/BetterNCM#239]
### Bug 描述

以下描述该BUG产生后导致的现象及行为，这些行为的产生与BUG有直接关系，不代表这些行为是全部需要修复的

- 重载插件时不会停止正在播放的音乐(如果这是正常行为的话当我没说)
- 重载完成后正在播放的音乐进度条丢失信息(播放时间/结束时间/播放控件复位)
- 重载完成后音乐会继续播放(中间没有停顿)
- 该首音乐播放完成后不会自动播放下一首(即使设置允许)
- 点击开始按钮后会从头开始播放音乐(此时进度条恢复)

### 复现步骤

1. 播放任意歌曲
2. 转到BetterNCM界面
3. 点击“重载插件”按钮
4. 完成后可见此BUG

### 期望行为

-  重载插件时应暂停播放音乐(这可能导致诸多问题)
- 重载后音乐进度条信息保持（虽然我不知道如何实现）

### 屏幕截图

<img width="426" alt="1674534924088" src="https://user-images.githubusercontent.com/83509039/214212994-01ada2b9-c0c6-4a02-bf0c-9b8810b45b32.png">

注:此时音乐正在播放，但进度条没有

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 补充

on windows11

**Comment by MicroCBer** [comment]
#191 这是个网易云自带的 bug
