### ISSUE TITLE
功能建议：自制滚动歌词

### ISSUE THREAD

**Issue by met-tk** [MicroCBer/BetterNCM#24]
现在的播放器都没法本地自制滚动歌词，除了千千静听，但也效果一般，很喜欢您的UI风格，希望能实现这个功能。

**Comment by MicroCBer** [comment]
https://github.com/MicroCBer/BetterNCM/issues/70#issuecomment-1336130063

**Comment by MicroCBer** [comment]
在设计中了

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
