### ISSUE TITLE
[ Bug ] 前台/后台CPU占用过高

### ISSUE THREAD

**Issue by GuaiJieYo** [MicroCBer/BetterNCM#241]
### Bug 描述

前台/后台CPU占用过高<br>
大部分时间占用为10%-20%<br>
![待机](https://user-images.githubusercontent.com/73426727/214217353-45d85c1e-7656-460f-883d-99a5344d597e.png)<br>
有些时候会跑到40%-60%（例如重载插件）<br>
![](https://user-images.githubusercontent.com/73426727/214217479-d8172983-2e5b-418f-9b86-6013f85b96a9.png)<br>

这是后台的占用情况(正在播放音乐)<br>
![](https://user-images.githubusercontent.com/73426727/214220546-8ac186cb-efad-423d-8585-95185afa106a.png)

插件列表<br>
1. [BetterMoTheme](https://github.com/GuaiJieYo/BetterMoTheme) （自己修改的Motheme）<br>
2. [MikuPlugin](https://github.com/miku3333/miku-plugin)<br>
3. stylesheetLoader<br>
4. [actionenhancement](https://github.com/BetterNCM/ActionEnhancement)<br>
5. [BGEnhanced](https://github.com/BetterNCM/BGEnhanced)<br>

网易云开启了***禁用GPU加速***

### 复现步骤

启动软件

### 期望行为

说明修复方法或者说明原因并尽快发布新的版本

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 补充

DevTools里的performance报告（由于GitHub的issue不能上传json 所以下载后请自行把后缀改为json 或者直接导入devtools）
[Profile-20230124T132226.txt](https://github.com/MicroCBer/BetterNCM/files/10486575/Profile-20230124T132226.txt)

**Comment by MicroCBer** [comment]
禁用gpu加速后渲染进程cpu占用偏好属正常现象。你相当于在用纯cpu算高斯模糊+视频解码。
