### ISSUE TITLE
[ Plugin Bug ] 关于Material You主题的各种bug

### ISSUE THREAD

**Issue by LingLing233** [MicroCBer/BetterNCM#242]
### Bug 描述

1、播放页面进度预备条露出
2、没有适配操作增强插件
3、整个主题操作逻辑不是很符合习惯，例如：在打开Material You主题设置面板时，点击其他区域无法自动关闭设置面板，必须按“打开/关闭”设置面板的按钮才能关闭

### 复现步骤

1. 安装操作增强插件，Material You主题，类AM操作插件等插件（下方有插件列表截图）
2. 打开播放页面
3. 点击开始按钮
4. 看到进度条的错误

### 期望行为

希望各个插件可以兼容

### 屏幕截图

![image](https://user-images.githubusercontent.com/107569515/214260663-5517d4a4-74f7-48ef-97b4-e05dced624d3.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![image](https://user-images.githubusercontent.com/107569515/214260900-18b7af72-d943-473c-9367-87e1b043f37c.png)

**Comment by feng-or** [comment]
进度条错误需要进入material you主题的菜单中关闭最下面的选项（如果不是就开启），操作增强是都没效果？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by LingLing233** [comment]
进度条错误时有时无的。我也不知道具体怎么触发，操作增强是真的都没有效果
