### ISSUE TITLE
[ Bug ] 1.0.2 检测不到 2.9.5 版本的网易云安装

### ISSUE THREAD

**Issue by NYDHRSY** [MicroCBer/BetterNCM#244]
### Bug 描述

![image](https://user-images.githubusercontent.com/56386116/214491805-13fb2cea-43ad-4892-9eb2-2915382087b1.png)
![image](https://user-images.githubusercontent.com/56386116/214491889-2eab808f-50d2-4b79-8650-b18087f22f87.png)
无法检测到已安装的网易云

### 复现步骤

未完成安装

### 期望行为

完成安装

### 屏幕截图

![image](https://user-images.githubusercontent.com/56386116/214491805-13fb2cea-43ad-4892-9eb2-2915382087b1.png)
![image](https://user-images.githubusercontent.com/56386116/214491889-2eab808f-50d2-4b79-8650-b18087f22f87.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.9.5

### 网易云音乐 Patch 版本

1:0f749b4

**Comment by MicroCBer** [comment]
BetterNCM v2 从来不适配也不会再适配 2.10.2 以前的旧版本。
