### ISSUE TITLE
[ Bug ] 重载插件时丢失部分插件，重启网易云后恢复

### ISSUE THREAD

**Issue by haima3** [MicroCBer/BetterNCM#245]
### Bug 描述

在插件商店安装插件后，重载，部分插件将不会显示。

### 复现步骤

1. 使用插件商店安装任意插件
2. 点击重载按钮

### 期望行为

重载后完整显示已安装的插件列表，可正常管理。

### 屏幕截图

![image](https://user-images.githubusercontent.com/59940054/214631456-5d703062-62ad-48af-b1a9-f7ab3ab4a406.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1:5ad43a6

### 补充

已尝试覆盖安装官网最新客户端，已尝试测试通道同样可复现。截至发布前复现成功率：100%

**Comment by MicroCBer** [comment]
请更新到 betterncm 1.0.0-nightly 尝试是否能复现

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by haima3** [comment]
> 请更新到 betterncm 1.0.0-nightly 尝试是否能复现
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

我已经尝试过了，可以复现。

**Comment by haima3** [comment]
> 请更新到 betterncm 1.0.0-nightly 尝试是否能复现
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

问题更严重了，重新下了一个Installer，装了测试通道，这次重载网易云直接卡死了

**Comment by haima3** [comment]
> > 请更新到 betterncm 1.0.0-nightly 尝试是否能复现
> > Generated by [koishi-plugin-github](https://github.koishi.chat/).
> 
> 问题更严重了，重新下了一个Installer，装了测试通道，这次重载网易云直接卡死了

补图：
![image](https://user-images.githubusercontent.com/59940054/214636074-673d4625-616c-457e-8a56-3417056f7f99.png)

**Comment by MicroCBer** [comment]
重新打开 这个是已知问题

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by haima3** [comment]
> 重新打开 这个是已知问题
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

我杀掉进程重新打开之后就变成安全模式了，BGEnhanced加载失败。再次重载插件还是会不显示哪些插件。

**Comment by MicroCBer** [comment]
截图失败提示

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by haima3** [comment]
> 截图失败提示
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

emmm只有卡死的时候结束进程才会触发安全模式的样子

下图是正常的安装的全部插件
![image](https://user-images.githubusercontent.com/59940054/214638672-5718de48-072b-4d48-983b-c93177cb6e9d.png)

一旦重载，就会变成一开始我开Issue时候的样子

**Comment by MicroCBer** [comment]
触发bug后查看betterncm/plugins_runtime文件夹下的文件？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by haima3** [comment]
> 触发bug后查看betterncm/plugins_runtime文件夹下的文件？
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

![image](https://user-images.githubusercontent.com/59940054/214647540-634fb176-d402-4601-a83f-e4274363f1fd.png)
![image](https://user-images.githubusercontent.com/59940054/214647620-1868a6dd-9b1e-4231-97ef-2a7c65685479.png)

是这样的
