### ISSUE TITLE
[ BGEnhanced ] 本地图片加载不了

### ISSUE THREAD

**Issue by cwl12** [MicroCBer/BetterNCM#246]
### Bug 描述

本地图片选择后无法显现。点击应用图片后显示为了默认主题背景。

### 复现步骤

1.点击图片功能按钮
2.选择本地图片，点击打开
3.本地图片为空白

### 期望行为

能够应用本地背景图片。

### 屏幕截图

![image](https://user-images.githubusercontent.com/46041110/214756860-e3b17cd5-fddb-4979-a8a2-cef959c421e3.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1:5ad43a6

### 已安装插件

1.Apple-Musiclike-lyrics-1.6.2
2.BGEnhanced-0.2.6
3.LibFrontendPlay-0.1.0
4.MoTheme-1.2.0
5.PluginMarket
6.SimpleAudioVisualizer-0.1.2
7.StylesheetLoader-0.1.1
8.TinyNCM-0.2.3

**Comment by feng-or** [comment]
检查文件路径是否有中文，此版本betterncm不能使用中文路径，可以去测试通道更新

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cwl12** [comment]
> 检查文件路径是否有中文，此版本betterncm不能使用中文路径，可以去测试通道更新
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

已解决，谢谢！
