### ISSUE TITLE
[ Bug ] 无法显示插件列表

### ISSUE THREAD

**Issue by DerekLLH** [MicroCBer/BetterNCM#247]

**Comment by DerekLLH** [comment]
尝试过更新到1.0.0-nightly，问题仍然存在

**Comment by DerekLLH** [comment]
灰屏就是[#212](https://github.com/MicroCBer/BetterNCM/issues/212)出现的问题

**Comment by xjr353171020** [comment]
评论栏comment按钮左边可以close已解决的issue

**Comment by MicroCBer** [comment]
都不知道怎么表达我此刻的无语
