### ISSUE TITLE
界面缩放不正常

### ISSUE THREAD

**Issue by Q-jun** [MicroCBer/BetterNCM#25]
![微信图片_20220825215023](https://user-images.githubusercontent.com/84129138/186682967-23b006af-3e45-4b3c-8c3c-7e3b1e232c8f.jpg)

**Comment by leijinbiao** [comment]
![Snipaste_2022-10-18_16-37-40](https://user-images.githubusercontent.com/81508974/196380653-8ff9f54c-c0d2-4ea0-8c60-38b090c58a7c.png)

**Comment by MicroCBer** [comment]
已取消强制禁止CPU渲染

**Comment by MicroCBer** [comment]
![ZSSOZ~2LV9U~T~TH_I9{@MU](https://user-images.githubusercontent.com/66859419/222940402-878b6b37-7238-41a6-b5b8-3d00f1cd6c73.jpg)
