### ISSUE TITLE
Material You主题导致网易云卡死无响应

### ISSUE THREAD

**Issue by windy1021** [MicroCBer/BetterNCM#250]
### Bug 描述

之前使用很少遇到，今晚网易云突然卡死点击哪里都没有反应，任务管理器重启后再打开网易云还是过几秒就卡死无响应，以为是插件冲突，但卸载重装后只剩一个Material You主题仍会卡死，安装其他插件则不会，故排查为该主题导致的bug

### 复现步骤

1.打开网易云

### 期望行为

修复bug不会因该插件导致卡死

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

- Material You

**Comment by Steve-xmh** [comment]
如果卡死不是指完全动不了的话，可以参考我这个回复操作，提供一下性能记录：https://github.com/MicroCBer/BetterNCM/issues/236#issuecomment-1401362539

**Comment by windy1021** [comment]
> 如果卡死不是指完全动不了的话，可以参考我这个回复操作，提供一下性能记录：[#236 (comment)](https://github.com/MicroCBer/BetterNCM/issues/236#issuecomment-1401362539)

win系统不太会弄呢...想问下哪里可以下载到旧版本的插件？我想试试是不是版本原因

**Comment by Steve-xmh** [comment]
> > 如果卡死不是指完全动不了的话，可以参考我这个回复操作，提供一下性能记录：[#236 (comment)](https://github.com/MicroCBer/BetterNCM/issues/236#issuecomment-1401362539)
> 
> win系统不太会弄呢...想问下哪里可以下载到旧版本的插件？我想试试是不是版本原因

不用在意我截图用的系统，这个是无关的，我说的步骤都是可以在 Windows 上操作的。

**Comment by windy1021** [comment]
> > > 如果卡死不是指完全动不了的话，可以参考我这个回复操作，提供一下性能记录：[#236 (comment)](https://github.com/MicroCBer/BetterNCM/issues/236#issuecomment-1401362539)
> > 
> > 
> > win系统不太会弄呢...想问下哪里可以下载到旧版本的插件？我想试试是不是版本原因
> 
> 不用在意我截图用的系统，这个是无关的，我说的步骤都是可以在 Windows 上操作的。

早上看到更新了2.0.3版本，安装后问题解决，看来是2.0.2版本的问题
