### ISSUE TITLE
BGEnhanced换完背景无法显示

### ISSUE THREAD

**Issue by CLXend** [MicroCBer/BetterNCM#251]
### Bug 描述

选择了视频和图片路径之后不显示

### 复现步骤

1. 转到BGEnhanced 
2. 点击视频
3. 选择相应路径
4. 选用后发现未显示

### 期望行为

修复显示bug

### 屏幕截图

![image](https://user-images.githubusercontent.com/116555247/214912046-978432ee-38c0-4b1b-8e66-7806a63760e3.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1:5ad43a6

### 已安装插件

BGEnhanced
Material You
RefinedNowPlaying
StylesheetLoader
TinyNCM
UnblockCloudMusic
VisualRecord
ActionEnhancement
FluenProgressBar
HideScrollbar
WHat is the cover of this music

**Comment by MicroCBer** [comment]
duplicated BetterNCM/BGEnhanced#8

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
