### ISSUE TITLE
[ Plugin Bug ] BGEnhanced插件图片导入无反应

### ISSUE THREAD

**Issue by HuYihe2008** [MicroCBer/BetterNCM#253]
### Bug 描述

导入图片后无法正常显示

### 复现步骤

转到插件管理页面
点击图片
导入图片
没了（

### 期望行为

有图片正确显示

### 屏幕截图

![image](https://user-images.githubusercontent.com/76118866/215250581-91f87602-fb25-4996-90ec-e733759f4ef6.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![image](https://user-images.githubusercontent.com/76118866/215250566-c5aaea0b-ec1f-4132-9433-f29d418ef849.png)

**Comment by MicroCBer** [comment]
duplicated BetterNCM/BGEnhanced#8

我求你们开 issue 之前先看下之前有没有好不好，这 issue id 我都背下来了
