### ISSUE TITLE
Apple Music-like lyrics 无法点击歌词跳转播放

### ISSUE THREAD

**Issue by windy1021** [MicroCBer/BetterNCM#255]
### Bug 描述

之前使用Apple Music-like lyrics的时候可以点击某行歌词跳转播放，但今天点击无效，以为是插件冲突，卸载后安装发现可以点击跳转，但装了别的插件之后，该功能就失效了，不论先后顺序都会失效

### 复现步骤

1.播放歌曲
2.点击歌词页面
3.点击某行歌词

### 期望行为

和其他插件兼容或者修复该bug

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

**例**:
- StylesheetLoader
- ActionEnhancement

### 补充

Apple Music-like lyrics
Material You
TinyNCM
ActionEnhancement
FluentProgressBar
RoundComerNCM
这首歌的封面是什么？

**Comment by MicroCBer** [comment]
@Steve-xmh

**Comment by Steve-xmh** [comment]
请将 Issue 另外发送到 [Apple Music-like Lyric 的开源仓库](https://github.com/Steve-xmh/applemusic-like-lyrics)内

**Comment by windy1021** [comment]
> 请将 Issue 另外发送到 [Apple Music-like Lyric 的开源仓库](https://github.com/Steve-xmh/applemusic-like-lyrics)内

好的
