### ISSUE TITLE
[ Bug ] 后台运行一段时间后前端卡顿

### ISSUE THREAD

**Issue by HanEric666** [MicroCBer/BetterNCM#256]
### Bug 描述

在网易云最小化，或者电脑屏幕锁屏一段时间（总之就是不动网易云客户端一段时间后），会导致前端卡顿，播放页歌词卡顿，用鼠标滚轮调整音量会卡住，不跟手，用鼠标和快捷键也调整不了音量。重载后就能解决，但是很不方便

### 复现步骤

1. 正常打开网易云音乐，开始播放
2. 最小化窗口或者锁屏一段时间（总之就是不动网易云客户端一段时间后）
3. 问题复现

### 期望行为

正常播放音乐，用鼠标滚轮调整音量

### 屏幕截图

![image](https://user-images.githubusercontent.com/66511146/215302499-0e4a14ae-bef6-4011-b808-e74cb954dc19.png)
![image](https://user-images.githubusercontent.com/66511146/215302508-3a9d4f87-12f8-48c4-9829-8ff5ec52c301.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 补充

1.0升级betterncm后问题出现
之前的老版本没有这个问题
单独留一个ActionEnhancement
插件，其余插件都卸载也有问题（排除插件过多导致）
音量无法调整如下：
https://user-images.githubusercontent.com/66511146/215302856-84c300f9-46db-4d2b-b5ad-431767c4dfd2.mp4

**Comment by MicroCBer** [comment]
duplicated #212

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by HanEric666** [comment]
> 重复#212
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

没有重复吧 问题好像有点不一样，我的状况是音乐不卡顿，但是音量有问题

**Comment by MicroCBer** [comment]
fixed
