### ISSUE TITLE
[ FR ] 可以让插件商店下载同插件的不同分支版本（稳定分支、测试分支、开发分支等）

### ISSUE THREAD

**Issue by Steve-xmh** [MicroCBer/BetterNCM#257]
### 描述你想要的功能

为了让一些希望尝鲜的用户使用插件的最新开发版本，减少安装难度（前往 Github Release 下载开发版本并手动安装等操作比较繁杂），同时帮助开发者在插件版本转正前尽可能修正潜在问题。
故希望提供一种下载分支功能，例如默认情况下下载 `stable` 稳定版本分支，然后有相对更新的 `beta` 分支或者最新开发版本分支 `nightly`。
同时也需要保证每个分支都能得到对应的插件更新通知。

**Comment by MicroCBer** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/66859419/a71ee99c-1f71-477b-8f18-5f1ff52fbbe7)
