### ISSUE TITLE
CPU占用不正常

### ISSUE THREAD

**Issue by hilphen** [MicroCBer/BetterNCM#26]
重装了系统之后CPU站奇高，Windows11 21H2(22000.918)，网易云：2.10.3(Build:200198)，BetterNCM：0.2.1
试过各种重装网易云，也试过从使用正常的笔记本上把安装好的网易云目录复制过来，结果都是一样
![image](https://user-images.githubusercontent.com/85595379/188267657-0b8bc7aa-eab3-4aa4-96ea-5cc1ab6fa301.png)

这是笔记本的，同样的Windows版本，网易云版本
![image](https://user-images.githubusercontent.com/85595379/188267646-09b93344-1748-40b7-ab11-56e00d0aa46f.png)

**Comment by MicroCBer** [comment]
按F12看看有没有什么报错呢

**Comment by hilphen** [comment]
有报错，不过另外一台正常的笔记本上也报这错误
![image](https://user-images.githubusercontent.com/85595379/188269971-bfbbe27a-7c3b-4533-b60f-92d8cba14e84.png)

**Comment by MicroCBer** [comment]
在CPU占用出现异常的机器上按F12，控制台中输入
```js
!(function hookChannelCall(){
    let origin_channel_call=channel.call;
    channel.call=function(...args){
        console.log(args[2])
        origin_channel_call.call(this,...args)
    }
})()
```
查看有无刷屏结果

**Comment by hilphen** [comment]
一片空白，没任何结果
![image](https://user-images.githubusercontent.com/85595379/188273180-6c05f66b-abea-4cec-b165-d293931a5ba2.png)

**Comment by MicroCBer** [comment]
不是在搜索框，在控制台

**Comment by hilphen** [comment]
![image](https://user-images.githubusercontent.com/85595379/188273465-bae79fc3-eadb-482d-ac59-b32d51fd0c4b.png)
![image](https://user-images.githubusercontent.com/85595379/188273470-d48e6404-1f9f-49a3-9d27-535810710500.png)

**Comment by MicroCBer** [comment]
只有用gdb调试一下了，比较麻烦

确认原版网易云CPU占用不会这样吗，还有GPU驱动是否装好（因为BetterNCM禁止网易云禁止GPU渲染，可能会造成一定影响）

**Comment by MicroCBer** [comment]
我这边暂时复现不了，等能复现了再看看吧

（另外如果不启用GPU渲染的话 在我的电脑上他大概也是吃20%左右的cpu）

**Comment by hilphen** [comment]
我把插件卸了是正常的，GPU驱动也是最新的，还有就是我的上一个系统是正常，现在能怀疑的大概率就是驱动问题了，我试试装个旧版的GPU驱动

**Comment by MicroCBer** [comment]
已取消强制禁止CPU渲染，尝试新版是否正常

**Comment by MicroCBer** [comment]
#236
