### ISSUE TITLE
[ 插件 Bug ] 就在刚刚又发现一个插件bug

### ISSUE THREAD

**Issue by cale044** [MicroCBer/BetterNCM#261]
### Bug 描述

BEGnhanced新版本上传视频（.mp4文件）不显示壁纸

### 复现步骤

例:
1. 打开BEGnhanced插件设置
2. 点击【视频】
3. 选择视频之后
4. 不显示壁纸，如下
![屏幕截图 2023-01-30 120727](https://user-images.githubusercontent.com/123907413/215386259-0515291a-5e98-4460-811e-3b3c186a61ad.png)
![屏幕截图 2023-01-30 120902](https://user-images.githubusercontent.com/123907413/215386275-4f49127c-02c9-4f58-ab27-df0674f80e45.png)

### 期望行为

希望早点修复一下谢谢

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

已安装插件如下
![屏幕截图 2023-01-30 065645](https://user-images.githubusercontent.com/123907413/215386327-d5e49717-cb4a-4513-8a5f-50bfaaeef39c.png)
![屏幕截图 2023-01-30 065751](https://user-images.githubusercontent.com/123907413/215386332-66d8d309-2438-428d-a18e-28c9a70c8315.png)

**Comment by feng-or** [comment]
文件路径不能有中文，或者使用betterncm installer测试通道更新

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by cale044** [comment]
> 文件路径不能有中文，或者使用betterncm installer测试通道更新
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

我试试看行不行

**Comment by MicroCBer** [comment]
BetterNCM/BGEnhanced#8

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215397248-6d9986c0-1e6d-4273-a94a-06bf85a5cf1c.png)

一个 issue duplicate 这么多次 没话说
