### ISSUE TITLE
[ Bug ] 关闭控制台导致网易云被关闭

### ISSUE THREAD

**Issue by Han0HanZero** [MicroCBer/BetterNCM#263]
### Bug 描述

关闭控制台时网易云也会一同被关闭

### 复现步骤

1. 打开网易云
2. 点击右上角进入BetterNCM设置页
3. 点击打开控制台
4. 手动关闭控制台

### 期望行为

关闭控制台时不关闭网易云

### 屏幕截图

[debug.log](https://github.com/MicroCBer/BetterNCM/files/10534337/debug.log)
网易云根目录找到的log文件

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by MicroCBer** [comment]
.link

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
#145 发 issue 之前能不能先搜一下啊

**Comment by Han0HanZero** [comment]
> #145 发 issue 之前能不能先搜一下啊

搜索时候忘了点closed，只搜了还在开放的。。。抱歉

**Comment by zrwkkd** [comment]
> #145 发 issue 之前能不能先搜一下啊

更新到测试版 1.0.1
网易云版本2.10.6
打开网易云，控制台都会自动开启，然后每次得进去插件“打开控制台”→“隐藏控制台”
能否默认打开隐藏控制台

**Comment by MicroCBer** [comment]
之前是 debug 编译默认显示控制台，release 编译默认隐藏控制台

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by zrwkkd** [comment]
> 之前是 debug 编译默认显示控制台，release 编译默认隐藏控制台
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

好的 谢谢
