### ISSUE TITLE
[ FR ] 侧边栏隐藏

### ISSUE THREAD

**Issue by cale044** [MicroCBer/BetterNCM#264]
### 你的功能请求是否与某个问题/需求有关？请描述

希望能做**侧边栏隐藏**做的跟LyricEase差不多就行
还有还有就是**收起音乐详情页**的图标改一下，改成LyricEase那样就行
下图为侧边栏
![屏幕截图 2023-01-30 122631](https://user-images.githubusercontent.com/123907413/215390918-96c2f783-d98a-4c22-996d-7a68c0ce9c85.png)
![屏幕截图 2023-01-30 122659](https://user-images.githubusercontent.com/123907413/215390923-2eeb9595-64b1-422d-b3f6-d1096e5c1fac.png)

### 描述你想要的解决方案

希望能做**侧边栏隐藏**做的跟LyricEase差不多就行
还有还有就是**收起音乐详情页**的图标改一下，改成LyricEase那样就行

**Comment by solstice23** [comment]
MD You 主题之后可能会支持

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215659499-c3e2cd8b-ccca-46a6-bac0-a5fe58ea5261.png)
