### ISSUE TITLE
[ Plugin Bug ] Taskbar-Lyrics更新后导致网易云无法启动

### ISSUE THREAD

**Issue by Yeah-le** [MicroCBer/BetterNCM#265]
### Bug 描述

今天更新Taskbar-Lyrics插件后，退出网易云，网易云无法启动，点击图标无反应，删除msing32.dll后可以正常启动，添加后仍然无法启动

### 复现步骤

更新Taskbar-Lyrics插件
退出网易云无法重新启动

### 期望行为

修复bug

### BetterNCM 版本

1.00

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

4ad43a6

### 已安装插件

**例**:
- StylesheetLoader
- ActionEnhancement
![Snipaste_2023-01-31_10-17-41](https://user-images.githubusercontent.com/76760776/215643463-862b5af3-bf01-43a0-aff0-0af7dec2abc8.png)

**Comment by feng-or** [comment]
这么说这个issue应该发到对应的仓库，我已经在群里@了等修吧

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by feng-or** [comment]
对应仓库应该有老版本，先用着吧

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by pscq0724** [comment]
我把C盘下的betterncm文件夹删除后，再次安装可以正常打开网易云音乐 @Yeah-le

**Comment by MicroCBer** [comment]
fixed
