### ISSUE TITLE
无法打开播放列表

### ISSUE THREAD

**Issue by ZYL0639** [MicroCBer/BetterNCM#267]
### Bug 描述

问题：点击打开播放列表按钮播放列表短时显示但是瞬间消失，目前出现时间最长不超过5s；目前测试过Material You主题及Mo Theme主题，问题复现

### 复现步骤

1.点击右下角的播放列表按钮
2.问题复现

### 期望行为

希望能正常打开作坊列表

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6 （Build：200601）官方版本

### 网易云音乐 Patch 版本

1:5ad43a6

### 补充

电脑系统版本：Windows 10 专业版22H2  操作系统内部版本：19045.2486

**Comment by feng-or** [comment]
在stylesheetloader插件里切换一下字体颜色就可以解决，发issue之前建议先查一下以前的issue，之前有人问过

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
duplicated #83
