### ISSUE TITLE
[ Plugin Bug ] SimpleAudioVisualizer导致的无法播放和界面错误

### ISSUE THREAD

**Issue by cow-your-sister** [MicroCBer/BetterNCM#268]
### Bug 描述

# 在使用了【SimpleAudioVisualizer】插件后，出现的【播放按钮变灰】以及【部分歌曲无法播放】等问题
表现为：
## 1
我喜欢的歌曲里面有的歌双击可以正常播放，有的就不可以，虽然加载了封面和进度条什么的，但就是没有声音，而且进度条也在走
## 2
无论播放什么歌曲，中间的播放/暂停按钮一律灰色，可以点击，有动画切换，但是没有实际效果。重载以后会恢复正常，但只要一播放歌曲就又变灰。
## 3
点击音量按钮，出现的音量条在50%的位置，但实际上是100%的音量
## 4
还有一点，全部快捷键无法使用。重新设置以后也没用
----
目前不确定是哪个插件造成的，有可能是那个把播放从后端换到前端的插件造成的

### 复现步骤

1. 装载【SimpleAudioVisualizer】插件，并且安装它的依赖插件
2. 重载BetterNCM
3. 随便双击播放一首歌

### BetterNCM 版本

1.0.0-91dbd0e pre-release

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

- StylesheetLoader
- RefinedNowPlaying
- MatrialYou
- SimpleAudioVisualizer
- LibEAPIRequest
- TinyNCM
- 【以上插件的依赖库】

**Comment by FlysoftBeta** [comment]
进入refindnowplaying设置界面把流体效果换成其他的

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cow-your-sister** [comment]
> 进入refindnowplaying设置界面把流体效果换成其他的
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

解决了，换用了MaterialYou，弃用MoTheme就好了（doge

**Comment by cow-your-sister** [comment]
刚刚验证了下，是那个音频可视化工具的问题

**Comment by MicroCBer** [comment]
播放按钮变灰：SAV也给播放按钮的 Opacity 上了跟随音频的效果
无法播放：
![image](https://user-images.githubusercontent.com/66859419/215709063-6d4212f3-db0b-4522-815e-a9c79a8197f1.png)
