### ISSUE TITLE
[ FR ] 可以提供一个Linux的release版吗

### ISSUE THREAD

**Issue by MuLeiSY2021** [MicroCBer/BetterNCM#269]
### 描述你想要的功能

希望能够有.deb的安装包

**Comment by MicroCBer** [comment]
BetterNCM 目前大规模使用 MS Detours 和 WinAPI，基本不可能直接编译到 Linux。且据了解 Linux 端前端几乎为 Deepin 方全盘重写，目前的插件也无法直接适配。

~~可以在此处投票 要是有 200 个我就去倒腾一下~~
