### ISSUE TITLE
[功能请求] 允许用户修改插件文件夹

### ISSUE THREAD

**Issue by Lapis-Apple** [MicroCBer/BetterNCM#27]
基于不同用户的不同需求和不同文件组织习惯，将插件的文件夹固定在 C:\Users\Username\betterncm 可能不是一个良好的方案。
建议允许用户对其进行修改。

**Comment by MicroCBer** [comment]
建议不要在issue发一些不雅言论

**Comment by MicroCBer** [comment]
现在可以通过设置环境变量 `BETTERNCM_PROFILE` 来设置插件文件夹了
