### ISSUE TITLE
[ Plugin Bug ] simpleAudioVisualizer 与 RefinedNowPlaying 存在冲突

### ISSUE THREAD

**Issue by AFKL-CUIT** [MicroCBer/BetterNCM#272]
### Bug 描述

当刚启动安装了插件的网易云后，进入播放页发现 RefinedNowPlaying 插件正常运行，但 simpleAudioVisualizer 未运行。
尝试重新配置 simpleAudioVisualizer 的配置选项后， 再次进入播放页，simpleAudioVisualizer 开始正常运作。

复现视频在最后。

### 复现步骤

1. 启动安装了插件的网易云，进入播放页
2. 进入播放页发现 RefinedNowPlaying 插件正常运行，但 simpleAudioVisualizer 未运行
3. 重新配置 simpleAudioVisualizer 的配置
4. 再次进入播放页，simpleAudioVisualizer 开始正常运作

### 期望行为

RefinedNowPlaying 与 simpleAudioVisualizer 可以同时运作

### 屏幕截图

https://user-images.githubusercontent.com/56114673/215812012-5af47e58-30c0-4f90-a87e-edc696db261d.mp4

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

- BGEnhanced-0.2.7.plugin
- LibEAPIRequest-1.6.2.plugin
- LibFrontendPlay-0.1.0.plugin
- MikuPlugin-0.1.1.plugin
- MoTheme-1.2.0.plugin
- PluginMarket.plugin
- RefinedNowPlaying-2.2.0.plugin
- RoundCornerNCM-0.1.2.plugin
- SimpleAudioVisualizer-0.1.2.plugin
- StylesheetLoader-0.1.1.plugin
- What-is-the-cover-of-this-music-2.0.4.plugin
- liblyric-1.0.0.plugin

**Comment by cale044** [comment]
我没有，怪哎

**Comment by AFKL-CUIT** [comment]
**补充**

更新 RefinedNowPlaying 插件后，将背景类型设置成“无”后可以看见正常运作的 simpleAudioVisualizer 

![图片](https://user-images.githubusercontent.com/56114673/216241988-f9a70488-817f-449e-8ba7-e5be1717c242.png)

**Comment by cale044** [comment]
> **补充**
> 
> 更新 RefinedNowPlay 插件后，将背景类型设置成“无”后可以看见正常运作的 simpleAudioVisualizer
> 
> ![图片](https://user-images.githubusercontent.com/56114673/216241988-f9a70488-817f-449e-8ba7-e5be1717c242.png)

我不用也会显示，怪
![image](https://user-images.githubusercontent.com/123907413/216446312-b7a49333-9752-4210-9fa8-d1c1b885f5b1.png)

**Comment by AFKL-CUIT** [comment]
RefinedNowPlaying 更新到2.3.4自动解决了= =
我先close了（
