### ISSUE TITLE
无法更新Apple Music-like lyrics1.7.1版本

### ISSUE THREAD

**Issue by windy1021** [MicroCBer/BetterNCM#273]
### Bug 描述

在插件市场点击更新一直在加载，卸载该插件重新安装仍显示加载无法安装，在作者release中下载最新版插件却显示1.7.0版本需要升级，已询问插件作者，他回复说是插件市场的问题

### 复现步骤

打开插件市场
点击更新Apple Music-like lyrics插件

### 期望行为

修复bug

### 屏幕截图

<img src="https://files.catbox.moe/ns0014.png"  />
<img src="https://files.catbox.moe/m2eh0d.png"  />

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by solstice23** [comment]
更新测试版

**Comment by windy1021** [comment]
> 更新测试版

谢谢，已解决
