### ISSUE TITLE
[ Plugin Bug ] StyleSnippet插件功能建议

### ISSUE THREAD

**Issue by cale044** [MicroCBer/BetterNCM#274]
### Bug 描述

**更大的网易云**大小可调节
**侧边栏折叠**私人FM折叠后显示**FM**而不是只有**半节字**关注折叠后显示**+**
发现音乐显示如图
![屏幕截图 2023-02-01 012714](https://user-images.githubusercontent.com/123907413/215837063-49bed100-9333-41e1-9fd4-e13fcdb64b76.png)

### 复现步骤

希望作者可以看到

### 期望行为

希望作者可以看到

### 屏幕截图

![image](https://user-images.githubusercontent.com/123907413/215837566-61310905-a5ce-4bca-bf70-ab9a005bb59a.png)
![image](https://user-images.githubusercontent.com/123907413/215837707-7391ae04-5f9d-4416-a75d-24e9fb503ed4.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![屏幕截图 2023-01-30 065645](https://user-images.githubusercontent.com/123907413/215838072-61da9f7c-a735-4bef-8169-9fddc7bd6af5.png)
![屏幕截图 2023-01-30 065751](https://user-images.githubusercontent.com/123907413/215838081-b395aa79-4f67-4ebc-a516-3747721b7373.png)

**Comment by MicroCBer** [comment]
更大的网易云大小再大一点就会导致一堆 layout 爆炸

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
> 更大的网易云大小再大一点就会导致一堆 layout 爆炸
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

但是我想让他小一点唉
ps：可以限制大小

**Comment by MicroCBer** [comment]
我可以去写一个更小一点的版本的

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
> 我可以去写一个更小一点的版本的
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

OK等你哦
ps：作者早点睡哦

**Comment by cale044** [comment]
> 我可以去写一个更小一点的版本的
> 
> 由[koishi-plugin-github](https://github.koishi.chat/)生成。

还有更大的网易云打开之后专辑图没了一节
![image](https://user-images.githubusercontent.com/123907413/215841774-868525d2-b08a-47e4-9350-579410ce2f81.png)

**Comment by cale044** [comment]
> > 我可以去写一个更小一点的版本的
> > 由[koishi-plugin-github](https://github.koishi.chat/)生成。
> 
> 还有更大的网易云打开之后专辑图没了一节 ![image](https://user-images.githubusercontent.com/123907413/215841774-868525d2-b08a-47e4-9350-579410ce2f81.png)

放大之后显示专辑图显示完整
![image](https://user-images.githubusercontent.com/123907413/215842180-f1cb0acc-b621-4a54-b157-a73877626e0e.png)

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215938991-5aeb1427-78af-4895-85f8-80ce421015de.png)
![image](https://user-images.githubusercontent.com/66859419/215939035-e171a740-ed98-459c-8c40-59da969fea7e.png)
