### ISSUE TITLE
[ Bug ] 无法正常安装BetterNCM

### ISSUE THREAD

**Issue by BillZhong2008** [MicroCBer/BetterNCM#277]
### Bug 描述

在使用BetterNCM Installer安装BetterNCM后无法正常使用网易云音乐。

### 复现步骤

1. 打开BetterNCM Installer
2. 单击"安装"按钮
3. 安装完成
4. 网易云无法启动

### 期望行为

网易云音乐在安装BetterNCM后应正常启动并可正常使用。

### 屏幕截图

https://user-images.githubusercontent.com/89178012/216049297-7c86ce11-8faa-4e4e-bdf2-c12bfc38b7a5.mp4

### BetterNCM 版本

1.0.0 and 1.0.0-nightly

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 补充

处理器	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
版本	Windows 11 专业版 22H2
操作系统版本	22621.1194
体验	Windows Feature Experience Pack 1000.22638.1000.0
显示卡 NVIDIA GeForce MX450

**Comment by MicroCBer** [comment]
2. (85.60%, ID:76)
        问: 安装后无法打开网易云客户端
        答: 1.
请检查网易云版本是否为最新版（若为否请升级）
2.
若为是，请移步到 C:\Users\(电脑用户名) 或 C:\ （新版以改到此位置...
        相关链接：https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#VOgcdaoycoG84ux2pwbcogkrnue

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by feng-or** [comment]
尝试手动安装，或先看上面的确定c盘或者用户目录有没有产生betterncm文件夹，如果没有可能是uac设置太高导致插件文件没法写入

**Comment by BillZhong2008** [comment]
![image](https://user-images.githubusercontent.com/89178012/216053310-48a50ddc-b5d5-4e92-a669-54a565509d5f.png)
C盘根目录与/Users/用户目录下未产生betterncm文件夹，系统UAC设置调整为最低"从不通知",问题未解决。

**Comment by MicroCBer** [comment]
检查网易云目录下 msimg32.dll 哈希和大小

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by BillZhong2008** [comment]
![image](https://user-images.githubusercontent.com/89178012/216054547-8f8a3ac4-b284-4fe8-b664-f53fc137cad9.png)
网易云音乐目录下未找到 msimg32.dll 文件

**Comment by MicroCBer** [comment]
那你根本没装上啊

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by feng-or** [comment]
在安装器的目录下应该会存有 BetterNCMII.dll的文件，或者从GitHub上下，手动改名为msimg32.dll拉入网易云安装目录

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by BillZhong2008** [comment]
![image](https://user-images.githubusercontent.com/89178012/216055576-70c2c7ee-0396-445e-bce5-b79a8bf57247.png)
安装BetterNCM后msimg32.dll大小693KB，哈希值b6d3659424a18d19d287e906228cbf99fc3d3b1f7b7008513f7ff27dc33842ed

**Comment by BillZhong2008** [comment]
替换msimg32.dll后问题照旧.

**Comment by MicroCBer** [comment]
你会使用调试器吗

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by BillZhong2008** [comment]
不会...

**Comment by MicroCBer** [comment]
明天群里找我远程看看吧

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by BillZhong2008** [comment]
okk

**Comment by wy0682109523** [comment]
@BillZhong2008 @MicroCBer 请问这个问题最后是如何解决的，我也出现这个问题l了，安装后，网易云就无法正常启动，C盘下没有betterncm目录，卸载插件后，网易云自行启动

**Comment by wy0682109523** [comment]
网易云版本：2.10.6（Build:200601）（Patch:1:aa07988）
都是今天最新下载的
<img width="613" alt="image" src="https://user-images.githubusercontent.com/13965665/230766673-72cdf34a-1c9f-4ef1-8450-024b789ddb69.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/13965665/230766696-52311dbe-efee-4a52-8c83-c1dd945de622.png">

**Comment by MicroCBer** [comment]
尝试使用安装器1.1.0（会显示为1.0.3）安装

**Comment by wy0682109523** [comment]
> 尝试使用安装器1.1.0（会显示为1.0.3）安装

@MicroCBer 可以了，谢谢！没发现已经更新新版本了QAQ
