### ISSUE TITLE
betterncm_installer中修改数据地址选项不可用

### ISSUE THREAD

**Issue by youlan2333** [MicroCBer/BetterNCM#278]
### Bug 描述

作者能否修改betterncm的数据文件存储于CloudMusic目录下，而不是c盘根目录下？

### 复现步骤

无

### 期望行为

数据文件存储于CloudMusic目录

### 屏幕截图

![QQ截图20230202163032](https://user-images.githubusercontent.com/64688148/216273611-3f9b3902-8cef-4427-9e0d-4700fbb7345d.png)

### BetterNCM 版本

1.0.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by feng-or** [comment]
可以用环境变量自行更改

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
可以自行使用环境变量修改。

**Comment by youlan2333** [comment]
电脑小白，请教作者如何使用环境变量修改呢？

**Comment by youlan2333** [comment]
> 可以用环境变量自行更改
> 电脑小白，请教作者如何使用环境变量修改呢？
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by youlan2333** [comment]
> 我看下能不能写教程吧
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

好的，感谢您

**Comment by feng-or** [comment]
https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#EUuudouWaog8iMx8WAGcBOC0n1b

**Comment by youlan2333** [comment]
> https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#EUuudouWaog8iMx8WAGcBOC0n1b

谢谢，我在环境变量里没有找到BETTERNCM_PROFILE，我新建之后解决了
