### ISSUE TITLE
[功能请求]是否可以增加自定义字体？

### ISSUE THREAD

**Issue by whoisfancy** [MicroCBer/BetterNCM#28]
网易云自带的字体选择不识别除了简中字库以外的其他字库（字库里包含其他语言也不行）

另外请问有无主题自定义手册/教程

**Comment by MicroCBer** [comment]
已加入todo list

你随便解压一个主题的.plugin文件就能看到源码了

顺便，安装`BetterNCM`后 按`F12`可以打开控制台 极大方便开发（只是有bug 关控制台会连着网易云一起关）

<sub><sup>~~开发文档啥时候有空写呢（叹气~~</sup></sub>

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/193533639-65839204-dd25-4817-90a6-6519727dacd9.png)
网易云这cef也是奇葩，document.fonts里面啥都没有

我写个noto sans吧

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/204073196-bdf12918-96df-4726-b1cb-50332eed70c1.png)

**Comment by whoisfancy** [comment]
> ![图像](https://user-images.githubusercontent.com/66859419/204073196-bdf12918-96df-4726-b1cb-50332eed70c1.png)

刚刚回来、、、看了一下不会弄emm

**Comment by whoisfancy** [comment]
> > ![图像](https://user-images.githubusercontent.com/66859419/204073196-bdf12918-96df-4726-b1cb-50332eed70c1.png)
> 
> 刚刚回来、、、看了一下不会弄emm

问题解决，重装插件和NCM之后有miku-plugin了（寄）
