### ISSUE TITLE
FluentProgressBar播放进度条异常

### ISSUE THREAD

**Issue by youlan2333** [MicroCBer/BetterNCM#282]
### Bug 描述

如图，安装之后，整个进度条一起动，卸载后一切正常

### 复现步骤

安装FluentProgressBar插件时
bug稳定复现

### 期望行为

无

### 屏幕截图

![QQ截图20230203104609](https://user-images.githubusercontent.com/64688148/216501255-5e08678f-f0a5-4ff2-a82f-2a33df93f529.png)
![QQ截图20230203104618](https://user-images.githubusercontent.com/64688148/216501259-287e8cdc-36d3-4359-9c5c-c314a34bde8c.png)
![QQ截图20230203104629](https://user-images.githubusercontent.com/64688148/216501267-2410f888-b45c-4398-bbcf-763d0854fc86.png)

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

PluginMarket
InfLink
LibEAPIRequest
LibFrontendPlay
LiveSongPlayer
Material You
RefinedNowPlaying
RuLyrics
StyleSnippet
VisualRecord
ActionEnhancement
LibLyric
MikuPlugin
RoundCornerNCM
这首歌的封面是什么?

**Comment by MicroCBer** [comment]
请自行查看 FluentProgressbar 仓库内相关 issue
