### ISSUE TITLE
RuLyrics-0.1.2.plugin bug

### ISSUE THREAD

**Issue by SamuraiQAQ** [MicroCBer/BetterNCM#283]
### Bug 描述

今天我任务栏歌词插件升级后，我就打不开网易云客户端了，然后我尝试从C盘删掉那个插件，就又能打开了，之后我再次安装这个插件，结果还是打不开网易云音乐，确定就是这个插件的bug。

### 复现步骤

我尝试从C盘删掉那个插件，就又能打开了，之后我再次安装这个插件，结果还是打不开网易云音乐，确定就是这个插件的bug。

### 期望行为

期望大佬能抽空修复下，麻烦了

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

Patch:15ad43a6

### 已安装插件

![Uploading image.png…]()
![$WGI5K9V~N@UFQ7`~$544$5](https://user-images.githubusercontent.com/62920132/216742012-62ddbefd-2ec1-4399-8369-dcb3e93413a8.png)

### 补充

无

**Comment by MicroCBer** [comment]
fixed

**Comment by Wmsqaq** [comment]
插件名称应该是RuLyrics 我遇到了同样的问题
English Machine：flip The plugin name should be RuLyrics I'm having the same issue
