### ISSUE TITLE
使用Material You 主题后歌单内歌曲乱序

### ISSUE THREAD

**Issue by LittleXingzzZ** [MicroCBer/BetterNCM#284]
### Bug 描述

某些歌单没有问题，但是排行榜里面的歌单乱序

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望能修复排行榜里面的歌单乱序问题

### 屏幕截图

![image](https://user-images.githubusercontent.com/55964606/216756089-541279ea-7117-4afa-9dea-979dbb07e62e.png)

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

-Material You
-fluentprogressbar
-simpleaudiovisualizer
-libfrontendplay

**Comment by solstice23** [comment]
已修复
