### ISSUE TITLE
[ Bug ] 使用在线功能更新后插件丢失

### ISSUE THREAD

**Issue by InSnocent** [MicroCBer/BetterNCM#285]
### Bug 描述

正在播放歌曲，从1.0.0版本在线更新到1.0.1后插件全部丢失

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望可以保存插件，或者添加个弹窗提醒

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by feng-or** [comment]
新版插件存储位置更改到了c盘betterncm目录下，之前是在用户文件夹betterncm文件夹下

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
