### ISSUE TITLE
安装BetterNCM后不能打开网易云

### ISSUE THREAD

**Issue by LittleXingzzZ** [MicroCBer/BetterNCM#286]
### Bug 描述

手动或者软件安装都是安装后不能打开网易云

### 复现步骤

1，安装BetterNCM
2，打开网易云
3，无任何反应

### 期望行为

希望修改此bug，安装BetterNCM后，能正常打开网易云

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by QingmingHaruaki** [comment]
发的什么issue

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
我第一次知道有这事

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by 3340378440** [comment]
我的也是，安装BetterNCM后网易云打不开，卸载之后就能打开。安装之后就打不开

**Comment by LSunnyCN** [comment]
同样的问题

**Comment by Armstrongzcl** [comment]
可以试试检查下C:\betterncm文件夹的安全权限，我安装后默认没有Autheenticated Users，添加了"Autheenticated Users"就可以了

![image](https://user-images.githubusercontent.com/22071010/217166875-66e06632-ca25-4b34-8b13-0234c055649e.png)

**Comment by LSunnyCN** [comment]
> 同样的问题

我发现可能是因为Taskbar-Lyrics与另一个任务栏歌词插件RuLyrics冲突引起的崩溃，在我已安装taskbar-lyrics后再安装RuLyrics会导致网易云崩溃，且崩溃后taskbar-lyrics还在plugins_runtime下且显示被其他应用程序占用无法删除。使用360解除占用且删除rulyrics后网易云可以正常打开

**Comment by MicroCBer** [comment]
taskbar lyrics 并非标准的 betterncm native plugin 实现方式，故不会随网易云关闭而关闭

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by LSunnyCN** [comment]
好滴，感谢解答

> taskbar lyrics 并非标准的 betterncm native plugin 实现方式，故不会随网易云关闭而关闭
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by 3340378440** [comment]
现在情况就是只要不安装BetterNCM网易云就可以正常使用，一旦安装BetterNCM就打不开了

**Comment by Big-Cake-jpg** [comment]
学校的一体机，Windows 8.1，网易云音乐和 BetterNCM 安装器均为最新版，一旦安装 BetterNCM 后网易云音乐就无法启动。

具体表现为任务管理器里闪了一下。

**Comment by MicroCBer** [comment]
请更新到最新版再试，看有无报错
