### ISSUE TITLE
[ Plugin FR ] 为Apple Music-like lyrics添加复制歌词功能

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#287]
### 你的功能请求是否与某个问题/需求有关？请描述

一部分人有频繁复制歌词的需求

### 描述你想要的解决方案

添加右键歌词复制的功能

**Comment by Ds1nk** [comment]
（过于简洁）
由于在Apple Music-like lyrics的repo里发issue没有回应，所以就发这里了: |

**Comment by Steve-xmh** [comment]
你要不再看看你发过的东西里我说了什么
https://github.com/Steve-xmh/applemusic-like-lyrics/issues/33
