### ISSUE TITLE
[ Plugin Bug ] 安装LibFrontendPlay后时间和进度条问题

### ISSUE THREAD

**Issue by VincentDirac** [MicroCBer/BetterNCM#289]
### Bug 描述

在该插件的repo下也提交了issue，但是由于一直没有回复，所以就只好在这里反馈了。
你好，我遇到了这样一个问题：安装了插件[LibFrontendPlay](https://github.com/BetterNCM/LibFrontendPlay)后，底部音乐栏的进度条和时间显示会在曲目不从头播放的时候出问题。比如，用鼠标点击进度条中间某个位置，音乐继续播放，但是时间跳到那个位置后就不再变化了，进度条也不再走了。卸载此插件后没有问题。
参见：[https://github.com/BetterNCM/LibFrontendPlay/issues/8](url)

### 复现步骤

1. 随便找一首曲子
2. 点击播放
3. 用鼠标随便点击进度条的某个时间点或者拖动进度条
4. 可以看到进度条和时间不随音乐播放而变化
5. 如果安装了Material You主题插件，可以解决进度条问题，但是时间仍然不会变化。

### 期望行为

希望能修正这个小bug，谢谢！

### 屏幕截图

![ENKHL@)O15)@Q}0Y1~032SR](https://user-images.githubusercontent.com/98157433/217867522-8bb7c7cc-5719-42b5-beb3-84f97780ccd1.png)
![L2MG93({OSE%2(OZ `6E307](https://user-images.githubusercontent.com/98157433/217867577-63c54ea0-4bdb-4c3f-8423-33644a55dbdb.png)

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

- StylesheetLoader
- ActionEnhancement
- Material You
- RefinedNowPlaying
- BGEnhanced
- FluentProgressBar
- 这首歌的封面是什么？
- LibFrontendPlay
- SimpleAudioVisualizer
- VisualRecord
- LibSongInfo

**Comment by cale044** [comment]
实际上一直都有这个bug

**Comment by cale044** [comment]
> 实际上一直都有这个错误

橘子懒得修罢了

**Comment by VincentDirac** [comment]
嗯，理解，毕竟有很多事情需要做，这个小细节的bug影响也不是太大。

**Comment by MicroCBer** [comment]
fixed
