### ISSUE TITLE
[功能请求] 自定义插件加载时期

### ISSUE THREAD

**Issue by Steve-xmh** [MicroCBer/BetterNCM#29]
可以默认 `load` 事件时加载，也可以自定义成初始化完 JS 后加载

这样可以让某些 Hook 操作更方便

注：考虑到如果有 Hook 需求需要在最早时期加载且主程序脚本不能开始加载，加载这类插件时需要同步加载。

**Comment by Steve-xmh** [comment]
已经自行尝试用 Rust 重写并实现初始化时期加载脚本的能力 #30 

可以参考（或者修改后合并）

**Comment by MicroCBer** [comment]
已实现
