### ISSUE TITLE
[ Plugin Bug ] LibFrontendPlay导致循环播放失效

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#293]
### Bug 描述

LibFrontendPlay导致循环播放失效，在播放一次后就不再播放

### 复现步骤

这还需要复现？

### 期望行为

能正常的循环播放

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![image](https://user-images.githubusercontent.com/104675168/218267399-62b040f8-80af-468c-a05b-34b648e5bad4.png)

**Comment by MicroCBer** [comment]
can't repro
