### ISSUE TITLE
[ Plugin Bug ] RuLirics在启用StyleSnippet中的 Material You 透明背景兼容后不会在打开网易云后显示

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#296]
### Bug 描述

RuLirics在启用StyleSnippet中的 Material You 透明背景兼容后不会在打开网易云后显示，需要重新打开Material You 透明背景兼容才能正常显示

### 复现步骤

无需

### 期望行为

正常显示

### 屏幕截图

![image](https://user-images.githubusercontent.com/104675168/218297197-c4264577-4672-4f23-8667-55c492673f47.png)

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![image](https://user-images.githubusercontent.com/104675168/218297258-78e2ed53-482a-4d4c-8414-00584147ac68.png)

**Comment by cale044** [comment]
更新看看
