### ISSUE TITLE
[ Bug ] 观看MV后返回主界面，侧边导航栏消失

### ISSUE THREAD

**Issue by ElegantLee** [MicroCBer/BetterNCM#297]
### Bug 描述

观看歌曲MV后，点击左上角返回键，侧边栏消失

### 复现步骤

1. 观看歌曲MV；
2. 点击左上角后退键；
3. 侧边导航栏消失；

### 期望行为

感谢作者的付出，希望作者抽空修复一下这个小 bug :heart:

### 屏幕截图

![QQ截图20230212214200](https://user-images.githubusercontent.com/45191822/218314854-e156d091-e89e-4570-8b43-b21e413171ea.png)
![QQ截图20230212214220](https://user-images.githubusercontent.com/45191822/218314866-c817c1f7-f52b-442b-8365-a7211ff414d7.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by 961739124** [comment]
![capture_20230227195235653](https://user-images.githubusercontent.com/100020034/221559878-295bb991-60dd-4023-ae0d-375e7656670a.jpg)
一样

**Comment by solstice23** [comment]
测试版中已修复
https://github.com/MicroCBer/BetterNCM/commit/988173f23b9795c53cf0916629e671401ccb2384
