### ISSUE TITLE
[ Bug ] 重载插件后内存占用异常

### ISSUE THREAD

**Issue by CMSMortal-chen** [MicroCBer/BetterNCM#298]
### Bug 描述

在每次点击重载插件后内存占用都会提高一些

### 复现步骤

1. 转到“BetterNCM”界面
2. 点击'重载插件'
3. 内存占用提高
4. 看到错误

### 期望行为

1. 转到“BetterNCM”界面
2. 点击'重载插件'
3. 正常占用

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by CMSMortal-chen** [comment]
补充:不装任何插件，点击重载也会这样

**Comment by MicroCBer** [comment]
网易云自带问题
