### ISSUE TITLE
Material You主题和Refined Now Playing插件工作使界面显示出现问题

### ISSUE THREAD

**Issue by ziyu-king** [MicroCBer/BetterNCM#299]
### Bug 描述

Material You主题和Refined Now Playing插件工作使网易云界面文字取色显示出现问题并会使右侧歌词设置页面出现遮挡

### 复现步骤

在安装Refined Now Playing和Material You主题情况下
1.打开 私人fm页面
2.问题出现

### 期望行为

Material You适配页面/Refined Now Playing正确覆盖页面
使文字背景正确显示

### 屏幕截图

![屏幕截图(106)](https://user-images.githubusercontent.com/60423212/218329808-214a54d8-9815-4cd1-b7c2-bb7465915bb1.png)
![屏幕截图(105)](https://user-images.githubusercontent.com/60423212/218329810-d180d3a5-a2ca-4955-a8d0-0fce030b4b26.png)
![屏幕截图(108)](https://user-images.githubusercontent.com/60423212/218329812-3be113c0-d80d-4963-86e4-fd1bff098ed0.png)
![屏幕截图(109)](https://user-images.githubusercontent.com/60423212/218329813-60f62155-886f-400d-9ff5-b4639a1acbdc.png)
![屏幕截图(110)](https://user-images.githubusercontent.com/60423212/218329818-825602b7-4d10-4fc6-bb6e-6951b141637c.png)
![屏幕截图(111)](https://user-images.githubusercontent.com/60423212/218329820-16f468f1-ae0b-45a0-a82a-4410cfb7fa90.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43d6

### 已安装插件

- Plugin Library
- StyleSnippet
- ActionEnhancement
- FluentProgessBar
- Material You
- Refined Now Playing
- 这首歌的封面是什么？
- LibFrontendPlay
- InfLink
- LibLyric
- LibEAPIRequest
- LibSongInfo
- RuLyric
- MikuPlugin

**Comment by solstice23** [comment]
是否开启了 更大的网易云 snippet
