### ISSUE TITLE
字体默认黑色

### ISSUE THREAD

**Issue by Muggles001** [MicroCBer/BetterNCM#3]
为什么我安装了主题，什么配置也没改，字体默认是黑色，也不知道怎么改成白色

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/182907748-de83fae9-37a8-4f6e-aa47-463407f8870d.png)
![image](https://user-images.githubusercontent.com/66859419/182907768-9302cc14-7405-40b8-bc70-d63517a79cbe.png)

如图 切换到酷炫黑即可
