### ISSUE TITLE
[ Bug ] 网易云关掉在开启后会进入安全模式

### ISSUE THREAD

**Issue by Nazrin720** [MicroCBer/BetterNCM#300]
### Bug 描述

网易云首次开启或完全关闭再次开启就会导致脚本进入安全模式

### 复现步骤

关掉网易云然后在重新打开就会导致插件进入安全模式
第 1 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./plugins_runtime"
    at ie (betterncm://betterncm/framework.js:1:22892)
    at betterncm://betterncm/framework.js:4:461

第 2 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./plugins_runtime"
    at ie (betterncm://betterncm/framework.js:1:22892)
    at betterncm://betterncm/framework.js:4:461

第 3 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./plugins_runtime"
    at ie (betterncm://betterncm/framework.js:1:22892)
    at betterncm://betterncm/framework.js:4:461

### 期望行为

脚本正常运行

### 屏幕截图

![QQ截图20230213132148](https://user-images.githubusercontent.com/63951577/218377303-50a4e630-c2c2-4770-bac7-f6d017c9d502.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

Patch:1:5ad43a6

**Comment by fivebaigei** [comment]
![image](https://user-images.githubusercontent.com/80877554/224536768-f3cf9a34-5a6e-4cec-a201-059e9ccf863e.png)
我是出现这个

**Comment by 3555189137** [comment]
我也是

**Comment by MicroCBer** [comment]
已经把安全模式阉掉了

后面两个 commit 的请更新 Taskbar-Lyrics（任务栏歌词），拜托你们不要把不同的问题发在同一个issue
