### ISSUE TITLE
[ Bug ] 加载界面覆盖主页

### ISSUE THREAD

**Issue by LilaSPPZ** [MicroCBer/BetterNCM#301]
### Bug 描述

卡在加载界面，但是可以操作，卸载后显示正常

### 复现步骤

打开网易云音乐后，卡在加载界面，但是可以操作播放，看不到主界面

### 期望行为

打开网易云音乐后，卡在加载界面，但是可以操作播放，看不到主界面

### 屏幕截图

<img width="1280" alt="微信截图_20230213135223" src="https://user-images.githubusercontent.com/125241669/218381625-df972d6b-c1b2-4750-b975-254f878022c0.png">

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

**Comment by cale044** [comment]
更新1.0.2试试

**Comment by cale044** [comment]
> 更新1.0.2试试

如果更新后还是这样就重启试试

**Comment by LilaSPPZ** [comment]
> 

更新了，重启过了，问题没解决

**Comment by cale044** [comment]
> > 
> 
> 更新了，重启过了，问题没解决

重装一下

**Comment by MicroCBer** [comment]
fixed
