### ISSUE TITLE
[ Bug ]配置好后当时能打开，过一天就打不开了。

### ISSUE THREAD

**Issue by MillionZBW** [MicroCBer/BetterNCM#302]
### Bug 描述

插件啥的都设置好后，当时能打开，过个一天网易云就打不开了。按常见问题删了插件文件夹就好了，但是过一天又是这样，反反复复。

### 复现步骤

安装插件后正常使用再关闭，过一天再打开。

### 期望行为

能正常打开

### 屏幕截图

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/23210456/218475103-f75ba2ea-ace2-48ce-bdc0-a669c74e626f.png">

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 补充

值得一提的是，从0.2.4开始就这样。0.2.1无此问题（非严格逐个版本测试，0.2.1为接触本插件时的最新版）。有个非常规解决方法，将betterncm文件夹移走，正常启动网易云后再覆盖回来，就可以启动网易云了，但是应该治标不治本。qq1195083101(已加群)

**Comment by MicroCBer** [comment]
尝试使用测试通道最新版 看看是否已修复
