### ISSUE TITLE
插件库里啥也没有

### ISSUE THREAD

**Issue by f2934749636** [MicroCBer/BetterNCM#306]
![image](https://user-images.githubusercontent.com/98155560/219940323-97c6dbc0-0fb4-413b-817c-ae917f10c4a8.png)

网易云版本2.10.7

**Comment by yangnuozhen** [comment]
https://github.com/MicroCBer/BetterNCM/issues/305#issuecomment-1435687629

**Comment by cale044** [comment]
![image](http://koi.microblock.cc:5140//files/b0cb5845bc6d04d49699754b3f80cd3bdaf2cb60-3f9e379cb73b48370dc7d80387271d0d.image)

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
