### ISSUE TITLE
[bug]安装插件后无法读取本地lrc歌词文件

### ISSUE THREAD

**Issue by jingyu233** [MicroCBer/BetterNCM#308]
Bug 描述
在离线状态打开本地文件的时候无法读取本地lrc文件

复现步骤
在不安装betterNCM情况下，在打开本地音频文件时会自动匹配同目录下的lrc文件
在安装betterNCM之后，无法实现本地匹配。

期望行为
能够实现在betterNCM启用的状态下读取本地lrc文件并且兼容使用插件
另外希望有一个插件能够读取mp3文件自带的标签文件（网易云音乐本身似乎不支持直接读取mp3文件中自带的标签中的歌词内容，但是可以读到封面等内容）

屏幕截图
没启用betterNCM时
![Snipaste_2023-02-19_22-32-34](https://user-images.githubusercontent.com/59231782/219954811-60ea50f4-dc84-49c8-8654-807b316cd78d.png)
启用betterNCM后（如图为启用插件的效果，实测在只启用betterNCM但是不启用插件的时候依旧无法读到本地歌词）
![Snipaste_2023-02-19_22-31-31](https://user-images.githubusercontent.com/59231782/219954839-418c49b2-5295-4a26-ab07-f6ad726acd7e.png)

BetterNCM 版本
1.0.2

网易云音乐版本
2.10.6

网易云音乐 Patch 版本
5ad43d6

已安装插件
![image](https://user-images.githubusercontent.com/59231782/219954910-c02afa19-75a4-4a15-9d3f-f7d85344448c.png)

补充
真的是急需此功能，电脑平时有不联网使用的需求，非常喜欢betterNCM提供的功能，带给我很好的体验！感谢开发者，希望问题能够得到解决。

**Comment by Keith-the-wise** [comment]
跟楼主一个问题，无法读取本地歌词，只能播放网络歌曲

**Comment by solstice23** [comment]
已在 https://github.com/solstice23/refined-now-playing-netease/commit/41b2aace6d4daaa63863080e0a128d122377fdf7 中支持

**Comment by Keith-the-wise** [comment]
> 已在 [solstice23/refined-now-playing-netease@41b2aac](https://github.com/solstice23/refined-now-playing-netease/commit/41b2aace6d4daaa63863080e0a128d122377fdf7) 中支持

这个应该是betterNCM1.1.0更新前的修复吧，我经常更新refined-now-playing的插件，应该不是这个的问题？我有个任务栏歌词的插件出错了，然后现在就是本地带歌词的音乐无法播放

**Comment by Keith-the-wise** [comment]
> 已在 [solstice23/refined-now-playing-netease@41b2aac](https://github.com/solstice23/refined-now-playing-netease/commit/41b2aace6d4daaa63863080e0a128d122377fdf7) 中支持

这个应该是betterNCM1.1.0更新前的修复吧，我经常更新refined-now-playing的插件，应该不是这个的问题？我有个任务栏歌词的插件出错了，然后现在就是本地带歌词的音乐无法播放

**Comment by SamuraiQAQ** [comment]
我也遇到了一个bug，现在不显示任务栏歌词了，咋弄都不显示，看了下是能识别歌曲信息的，但是就是看不到歌词。

**Comment by Keith-the-wise** [comment]
很绝望，刚刚卸载重装也播放不了本地音乐，测试通道也没用

**Comment by Keith-the-wise** [comment]
找到解决办法了，插件一个一个删排查问题，楼上的哥们可以试试，我换了一个任务栏显示歌词的插件RuLyrics

**Comment by SamuraiQAQ** [comment]
谢谢楼上老哥的建议，但是我试过了，并不管用。

**Comment by jingyu233** [comment]
刚刚在实机环境中重新测试，在安装1.2.0和更新所有插件后所有功能正常，可以读取到本地lrc文件并且自动做匹配；
在虚拟机环境中测试，可以读到歌词但是读不到封面（可能是因为虚拟机环境有问题）
这个issue就close了，感谢betterNCM开发者和插件开发者

**Comment by jingyu233** [comment]
呜呜不知道为什么，在另外一台物理断网的机器上还是不能读到歌词，于是reopen一下

**Comment by jingyu233** [comment]
我在我自己的机器和这台机器的虚拟机中安装网易云+betterncm就能读到歌词lrc文件，
换一个机器就莫名其妙的不读lrc文件（玄学bug
而且更新之后最近好像本地文件的封面图片也读不出来了qaq

**Comment by MicroCBer** [comment]
禁用所有插件后可以吗

**Comment by jingyu233** [comment]
> 禁用所有插件后可以吗

开发老师您好，离线Windows7环境中依旧无法读出歌词文件。
![image](https://github.com/MicroCBer/BetterNCM/assets/59231782/5e78e59e-26ea-4b66-b405-a25d005ac30a)
在离线windWindows11环境可以读。
感谢老师回复！

**Comment by jingyu233** [comment]
> 禁用所有插件后可以吗

刚才把c++依赖库补了一下之后可以了
在离线Windows11环境和Windows7环境可以读，
但是存在部分插件读不到的情况：
![image](https://github.com/MicroCBer/BetterNCM/assets/59231782/a949847b-8ffd-4a5d-b2d0-16fa45061526)
![image](https://github.com/MicroCBer/BetterNCM/assets/59231782/666e3cf3-6af7-4fea-95f0-426c11c54889)
![image](https://github.com/MicroCBer/BetterNCM/assets/59231782/fc442efe-ef0a-4056-b404-18ed43f0166e)

感谢老师回复！
