### ISSUE TITLE
[功能请求]支持在Discord的状态显示

### ISSUE THREAD

**Issue by XiaoMouz** [MicroCBer/BetterNCM#31]
表现效果类似运行Discord时启动YesPlayMusic、Spotify后会在用户动态显示状态

[Discord RPC](https://discord.com/developers/docs/intro)

这个功能不急着做！加油喵！

**Comment by MicroCBer** [comment]
game sdk是`cpp/c#`的，我js想要调用貌似还挺麻烦

**Comment by XiaoMouz** [comment]
[YesPlayMusic](https://github.com/qier222/YesPlayMusic) 有这个功能可以参照一下[实现方式](https://github.com/qier222/YesPlayMusic/search?q=discord)？
我不是很清楚，只是希望能尽力帮助到你（（

**Comment by MicroCBer** [comment]
yesplay是用的老的RPC api，然后那个api现在已经不开放注册了

或许可以直接把他的id拿来用 ~~(应该不会被打)~~

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/193534628-8d188249-10b1-4f4e-97d9-f1b7210ad014.png)

**Comment by XiaoMouz** [comment]
> yesplay是用的老的Rich Presence api，然后那个api（貌似）现在已经不开放注册了
> 
> 或许可以直接把他的id拿来用 ~(应该不会被打)~



> game sdk是`cpp/c#`的，我js想要调用貌似还挺麻烦

欸等等，这不是一个`cpp`项目吗？？

**Comment by MicroCBer** [comment]
插件是js写的

**Comment by XiaoMouz** [comment]
> 插件是js写的

喔喔，好的）

**Comment by MicroCBer** [comment]
![E65VLW%WH_V2O(K0_QN NJE](https://user-images.githubusercontent.com/66859419/235318132-f030f194-0066-4884-af6b-b536d3ea107d.png)

感谢：https://github.com/Pizzabelly/EasyRP
