### ISSUE TITLE
升级版本后无法进入插件

### ISSUE THREAD

**Issue by yi447780897** [MicroCBer/BetterNCM#310]

**Comment by Na-Sizuku** [comment]
同样该问题

**Comment by cale044** [comment]
![image](http://koi.microblock.cc:5140//files/b0cb5845bc6d04d49699754b3f80cd3bdaf2cb60-3f9e379cb73b48370dc7d80387271d0d.image)

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
