### ISSUE TITLE
突然插件市场不显示任何插件了

### ISSUE THREAD

**Issue by Lnksoul** [MicroCBer/BetterNCM#311]
![image](https://user-images.githubusercontent.com/125109071/220497852-a7d7c526-e917-4f6e-a2b5-78c3149e7026.png)

**Comment by SakamotoCHN** [comment]
[https://github.com/MicroCBer/BetterNCM/issues/306#issuecomment-1435939664](url)

**Comment by SakamotoCHN** [comment]
[这里](https://github.com/MicroCBer/BetterNCM/issues/305#issuecomment-1435687629)
