### ISSUE TITLE
安装前端播放插件可能会导致黑胶会员格式无法正常播放

### ISSUE THREAD

**Issue by Aviciion** [MicroCBer/BetterNCM#312]
会员格式即使下载到本地也无法正常播放。
不清楚是否是前端播放插件与其他插件有冲突还是怎么样。

**Comment by Steve-xmh** [comment]
前端播放插件不支持解码ncm格式音频

**Comment by MicroCBer** [comment]
现在 libfrontendplay 会自动将 `.ncm` 转交给网易云自身播放，不过就没有音频可视化了
