### ISSUE TITLE
插件市场变灰以及RefinedNowPlaying调整设置按钮消失

### ISSUE THREAD

**Issue by merept** [MicroCBer/BetterNCM#313]
## 插件市场变灰

更新1.0.2版本后，Plugin-Market按钮变灰导致插件市场无法进入

重启网易云以及重载插件均无法解决问题

## RefinedNowPlaying调整设置按钮消失

原来播放界面RefinedNowPlaying设置按钮现在没有显示了，但是在插件管理界面仍提示“打开正在播放界面以调整设置”

该问题同样在重启网易云以及重载插件后没有解决

**Comment by solstice23** [comment]
后者，请更新到 2.10.6 以上版本

**Comment by merept** [comment]
> 后者，请更新到 2.10.6 以上版本

已解决，谢谢

**Comment by feng-or** [comment]
插件市场变灰请重载

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by feng-or** [comment]
并重启wyy

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
