### ISSUE TITLE
歌曲详情页面

### ISSUE THREAD

**Issue by zw-95** [MicroCBer/BetterNCM#314]
点开歌曲详情报错，切换歌曲无变化，重启恢复，暂不确定一定能复现问题的操作
![image](https://user-images.githubusercontent.com/35022819/220870113-b7dd7b52-09c1-43a1-9c4f-11d3b775dad5.png)

**Comment by MicroCBer** [comment]
@Steve-xmh

**Comment by Steve-xmh** [comment]
[请移步 AMLL 仓库发送 Issue](https://github.com/Steve-xmh/applemusic-like-lyrics/issues/new)
