### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by imusic-487** [MicroCBer/BetterNCM#315]
加了RefinedNowPlaying的插件之后gpu占用挺大，估计该插件作者无解，所以我想问可以实现一个整体插件的开关吗？虽然把软件最小化后可以解决问题，但是我直播或者打游戏有需求，用了该插件之后会导致和游戏抢资源，导致游戏卡

**Comment by solstice23** [comment]
https://github.com/solstice23/refined-now-playing-netease/issues/90
