### ISSUE TITLE
安装后无法启动网易云

### ISSUE THREAD

**Issue by HermosMerlin** [MicroCBer/BetterNCM#318]
### Bug 描述

1.安装BetterNCM后无法启动网易云（没有任何显示，任务管理器无进程）
2.启动网易云后，安装NCM后网易云界面会消失，进程消失，点击卸载NCM后界面立即出现，一切正常
3.在之前issues中有人提到的文件夹安全权限问题也确定设置正常

### 复现步骤

1.先安装插件后，正常启动网易云
2.或者先启动网易云，再安装插件

### 期望行为

希望修复

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

d769382

**Comment by HermosMerlin** [comment]
朋友描述不清晰，纠正：
并非本体问题，可能是插件问题，据说是安装某一插件后出现，我让他把C:\BetterNCM文件夹删除后可以正常安装使用
但是，插件市场变为灰色，无法点击，重装插件无效。

**Comment by MicroCBer** [comment]
点击
![image](https://user-images.githubusercontent.com/66859419/221238989-9de382a5-b367-4415-85fc-f88068a172d2.png)
即可重新释放插件市场

**Comment by KeeLee2005** [comment]
你或许可以尝试一下补全Microsoft Visual C++的运行库。我之前安装完BetterNCM之后也是打不开网易云，在把Microsoft Visual C++ 2005 Redistributable 至 2015-2022 的32位和64位都补全之后就可以打开了。

**Comment by MicroCBer** [comment]
若仍然无法解决请用

https://www.codeproject.com/Articles/14618/Catch-All-Bugs-with-BugTrap

捕获错误日志

**Comment by duwenba** [comment]
我也是同样的问题,卸载之后可以正常使用,但是安装之后网易云就无法启动了
