### ISSUE TITLE
[ Bug ] 无法正常启动，显示网络连接失败

### ISSUE THREAD

**Issue by fbstorm** [MicroCBer/BetterNCM#319]
### Bug 描述

1.显示 网络连接失败
2.插件界面未正常加载，插件显示不出来，版本也也显示一直在检测

### 复现步骤

我也不清楚，打开就是

### 期望行为

正常启动网易云和插件

### 屏幕截图

![image](https://user-images.githubusercontent.com/100028477/221355798-290a0573-091b-48bd-8b7d-0ae82d825c01.png)
![image](https://user-images.githubusercontent.com/100028477/221355914-7cb6dadf-da14-4e85-b07b-7f758cda7650.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

Patch:1:dc27721

### 补充

1.之前启动的时候没删插件，显示了错误信息但是没留，删了插件（C:\betterncm）之后就没有错误信息了，但还是不行

**Comment by MicroCBer** [comment]
自行关闭代理

**Comment by fbstorm** [comment]
我代理关了也重启了一次，但还是不行啊
