### ISSUE TITLE
系统兼容性？

### ISSUE THREAD

**Issue by silite** [MicroCBer/BetterNCM#32]
发现win11家庭版注入msimg32.dll时，启动网易云秒退，本地编译(x86)尝试用usp10.dll注入，同样问题发生
在dllMain入口函数起始点写入MessageBox，启动app没有发现弹窗直接秒退。
有没有什么dll注入的测试方法，启动app时自动中断点那种，或者大大知不知道无法注入成功启动app的原因

**Comment by MicroCBer** [comment]
网上随便找个dll injector

**Comment by Steve-xmh** [comment]
可以尝试一下[我的分支](https://github.com/Steve-xmh/BetterNCM/releases/tag/eapi-shark)

正在尝试用 Rust 重写，不知道在你这里稳定性能否有所改善

**Comment by MicroCBer** [comment]
另：自行编译要注意是32位 以及修改项目编译后行为里的网易云音乐路径
