### ISSUE TITLE
[ Bug ] 在此输入标题

### ISSUE THREAD

**Issue by fbstorm** [MicroCBer/BetterNCM#320]
### Bug 描述

无法正常启动，显示网络连接失败
关了代理还重启了一次，还是显示未连接

### 复现步骤

我也不清楚，打开就是

### 期望行为

正常启动网易云和插件

### 屏幕截图

![221355798-290a0573-091b-48bd-8b7d-0ae82d825c01](https://user-images.githubusercontent.com/100028477/221357294-60b0d459-6f3a-4182-b107-c61670a1717c.png)
![221355914-7cb6dadf-da14-4e85-b07b-7f758cda7650](https://user-images.githubusercontent.com/100028477/221357295-4a18d046-bfcb-47b6-8bf4-ac949273fd52.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

Patch:1:dc27721

**Comment by MicroCBer** [comment]
自行关闭代理
