### ISSUE TITLE
[ Bug ] 安装插件后不能登录

### ISSUE THREAD

**Issue by YumeYuiko** [MicroCBer/BetterNCM#321]
### Bug 描述

使用BetterNCM Installer安装，安装后有原先默认配置，但今天启动网易云后没有登录状态，且点击登录显示正在加载登录页面无反应，卸载后正常登录

### 复现步骤

打开网易云无登录状态，且点击头像与设置都无法弹出登录窗口（无设置更改
重装插件无变化
卸载插件后窗口正常弹出，正常登录
重新安装插件失去登录状态，但显示了原先的黑胶等级

### 期望行为

能够在安装插件的情况下正常弹出登录窗口，保持正常登录状态

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

Patch:1:d769382

**Comment by MicroCBer** [comment]
应该是某个插件的 Hijack 造成的，还不太清楚是哪个插件，可以暂时先禁用插件，登陆后再启用。

**Comment by duanluan** [comment]
> 应该是某个插件的 Hijack 造成的，还不太清楚是哪个插件，可以暂时先禁用插件，登陆后再启用。

那就得一个一个尝试……很麻烦，我现在也是这个问题，禁用所有插件，登录后再启用，然后登录状态就没了。

**Comment by duanluan** [comment]
确认了，我这边是 LibFrontendPlay 或 SimpleAudio Visualizer 的问题。

**Comment by MicroCBer** [comment]
fixed
