### ISSUE TITLE
[ Plugin FR ] RuLyrics插件的功能添加请求

### ISSUE THREAD

**Issue by IIIIAbyss** [MicroCBer/BetterNCM#326]
### 你的功能请求是否与某个问题/需求有关？请描述

**主要功能请求：RuLyrics插件的任务栏歌词希望能添加一个记录用户自己修改的位置，不然每一次打开都是默认的位置，又要重新调；**

无关紧要的叨叨：
1. 关于任务栏歌词的显示：比如我常听的是外文歌，那我根据它的歌词调了大小，使歌词在任务栏默认位置显示时（因为懒得每次都调位置）是居中的，但是有的歌歌词又会太靠下

![(PU6 D VM1 GW34R9(P 2ZE](https://user-images.githubusercontent.com/126242834/222890482-5e2927fd-489e-414e-8ba2-cd2d80caff5e.png)

 有的又会莫名只有一句是靠下的（如图左上）：

![038R8XC9WZ}NQ@G1XJ_%VP8](https://user-images.githubusercontent.com/126242834/222891258-8650e06e-5e09-46ef-beab-370b653885cc.png)

![$MH@W9EAES$IZA{UR08HLU7](https://user-images.githubusercontent.com/126242834/222891321-3adc6b19-aa93-4c88-838e-b22bd4635d36.png)

2. 也有比如歌词居中的需求的时候，所以如果附加一下歌词一件居中、居左等功能就更棒了。

### 描述你想要的解决方案

1. 最最最需要的其实就是能记录下用户自己调的位置，不用每次都调；（其它的根据每个人使用任务栏习惯不同，感觉众口难调）
2. 副歌词感觉会影响歌词显示的位置啊，如果是用大任务栏显示歌词两行也很丑，所以其实可以设置两种，非任务栏歌词就按现在的，任务栏歌词要不就直接取消副歌词，只按原文歌词来设定歌词范围、获取并设置歌词位置，这样歌词的位置也许就不会出现那些问题了...？...

**Comment by MicroCBer** [comment]
现在是无副歌词则在窗口居中显示 ![image](http://koi.microblock.cc:5140//files/df93df0af6e5ffd6c38bba9a5782873b1809d3ea-311265e1e112f4b6b3661037c0d3480e.image)![image](http://koi.microblock.cc:5140//files/df3b5724b3a6b635f875f7a2bd99da5bc524f7cb-5298c698421fd9388d47616839e55327.image)

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by IIIIAbyss** [comment]
> 现在是无副歌词则在窗口居中显示 ![image](https://camo.githubusercontent.com/f5b51697f76e539a181177651a95c0b2d7c5119dbfe37f5dacb4205e2b44cdb0/687474703a2f2f6b6f692e6d6963726f626c6f636b2e63633a353134302f2f66696c65732f646639336466306166366535666664366333386262613961353738323837336231383039643365612d33313132363565316531313266346236623336363130333763306433343830652e696d616765)![image](https://camo.githubusercontent.com/519964703b3943e6d5724de9faf0d4dcd762ffb853b48f58fb21e33a9dfec62a/687474703a2f2f6b6f692e6d6963726f626c6f636b2e63633a353134302f2f66696c65732f646633623537323462336136623633356638373566376132626439396461356263353234663763622d35323938633639383432316664393338386434373631363833396535353332372e696d616765)
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

大佬我没法看到你的图欸，不过你这么说的话，我刚刚试了一下把副歌词显示出来，然后就发现了，那些歌词靠下的歌曲，一种是没有翻译的（音译的不知道没注意过）；
另一种是像我上面传的那两张大图的那种，**某一句歌词的翻译没有被读取到**（只是猜想，因为那一句副歌没显示），**所以就导致那一句歌词位置和其他句的歌词不一样**，那这也许是网易云歌词源的问题惹...
至于你说的”无副歌词则在窗口居中显示“应该是你代码设定的规则吧（因为我看不到你的图所以只是猜测emmm），但是插件设置界面不是只能把副歌词透明处理吗。。所以感觉和最终的显示效果会有些些差异；
最后，感谢大佬的付出🌹

**Comment by MicroCBer** [comment]
哦哦，是想关闭副歌词吗，后面做一下

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by IIIIAbyss** [comment]
> 

哦忘了一点，因为挺多外文歌都是有翻译的，所以用户设置隐藏掉副歌词的时候，根据有翻译的歌曲来调歌词

> 哦哦，是想关闭副歌词吗，后面做一下
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

嗯算是这样的，因为挺多外文歌都是有翻译的，所以用户设置隐藏掉副歌词的时候，根据有翻译的歌曲来调的歌词位置，到没有翻译的歌曲的时候歌词位置就会变（主要是任务栏上的变化太难受了，单纯的桌面歌词那就还好）；
另外，歌词位置的记录真的超级超级有必要，大佬要是能考虑一下就太棒了（比心）

**Comment by IIIIAbyss** [comment]
> 哦哦，是想关闭副歌词吗，后面做一下
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

嗯算是这样的，因为挺多外文歌都是有翻译的，所以用户设置隐藏掉副歌词的时候，根据有翻译的歌曲来调的歌词位置，到没有翻译的歌曲的时候歌词位置就会变（主要是任务栏上的变化太难受了，单纯的桌面歌词那就还好）；
另外，歌词位置的记录真的超级超级有必要，大佬要是能考虑一下就太棒了（比心）

**Comment by IIIIAbyss** [comment]
> 哦哦，是想关闭副歌词吗，后面做一下
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

嗯算是这样的，因为挺多外文歌都是有翻译的，所以用户设置隐藏掉副歌词的时候，根据有翻译的歌曲来调的歌词位置，到没有翻译的歌曲的时候歌词位置就会变（主要是任务栏上的变化太难受了，单纯的桌面歌词那就还好）；
另外，任务栏歌词位置的记录真的超级超级有必要，大佬要是能考虑一下就太棒了（比心）
