### ISSUE TITLE
之前解灰插件怎么没了

### ISSUE THREAD

**Issue by fbstorm** [MicroCBer/BetterNCM#327]
### 你的功能请求是否与某个问题/需求有关？请描述

rt

### 描述你想要的解决方案

rt

### 描述你考虑过的替代方案

rt

### 额外的背景

rt

**Comment by cale044** [comment]
建议加群看群公告

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by fbstorm** [comment]
好的

**Comment by fbstorm** [comment]
能指条路吗，真没找到😢

**Comment by cale044** [comment]
QQ群：479613101

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
