### ISSUE TITLE
[ Bug ] Unable to load login page,infinity loading instead of showing

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#329]
### Bug 描述

I reinstalled NeteaseCloudMusic and Installed betterNCM,but this time I could not login because there is a "loading login pages,please wait..." forever,so I open console(and f12) to get a test and find there the http_file_down_manager.cpp tried 2+ times then stopped report anything.

### 复现步骤

Logout in NCM
install betterNCM
retry to login

### 期望行为

Hope to fix this bug(

### 屏幕截图
[in normal ncm]
![微信图片_20230308231950](https://user-images.githubusercontent.com/119386507/223754366-e150d489-4eca-41bf-a764-323fdb29f195.png)
[in better ncm]
![image](https://user-images.githubusercontent.com/119386507/223754863-e110b5d4-3d08-4b36-ab4f-c037672324d1.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

Patch:1:8d8117c

**Comment by ConCose** [comment]
但是当时在写代码懒得切输入法了（
明天放学edit一下



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 9, 2023 00:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MicroCBer/BetterNCM] [ Bug ] Unable to load login page,infinityloading instead of showing (Issue #329)




 
你用中文我们也是看得懂的

**Comment by cale044** [comment]
> 但是当时在写代码懒得切输入法了（ 明天放学edit一下
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Mar 9, 2023 00:08 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [MicroCBer/BetterNCM] [ Bug ] Unable to load login page,infinityloading instead of showing (Issue #329) 你用中文我们也是看得懂的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

理解的

**Comment by MicroCBer** [comment]
It appears that there may be an unresolved bug in LibFrontendPlay. While I had believed that the issue had been resolved with the release of LFP 1.0.2, it seems that the problem persists. In order to address this, I recommend that you try reinstalling betterncm to the latest version of the test channel, and ensure LFP has been updated to the latest version.

**Comment by cale044** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。
