### ISSUE TITLE
安装后打不开私信

### ISSUE THREAD

**Issue by SakuraSayaka** [MicroCBer/BetterNCM#33]

**Comment by laorentou666** [comment]
https://user-images.githubusercontent.com/89732460/208044565-aa2c5c33-5a6b-483b-b989-abffcc0094a5.mp4

如视频所示，安装BetterNCM后无法打开网易云私信
操作平台：Windows11 Pro（另外一台Windows10也有同样的问题）
网易云版本：2.10.6
