### ISSUE TITLE
[ Bug ] 安装部分插件后，管理器不识别该插件

### ISSUE THREAD

**Issue by Xionghaizi001** [MicroCBer/BetterNCM#330]
### Bug 描述

安装部分插件，如“明暗主题切换器”，管理器中不识别已安装的插件，重启或重载也无法解决，导致部分依赖该插件的主题和扩展无法使用

### 复现步骤

1.打开插件商店
2.安装“明/暗主题切换器”
3.重载或重启网易云

### 期望行为

插件的安装被正确识别

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1:aa07988

**Comment by MicroCBer** [comment]
“无法识别” 具体是什么情况？

**Comment by Xionghaizi001** [comment]
不管是从插件管理器装还是手动放到插件文件夹，管理器都找不到这个插件，依赖这个插件的主题也无法启用

**Comment by MicroCBer** [comment]
截图插件管理器和运行时的 plugins_runtime 文件夹看看

**Comment by Xionghaizi001** [comment]
如图
[https://s1.ax1x.com/2023/03/10/ppuUuZQ.png](url)
[https://s1.ax1x.com/2023/03/10/ppuUmqg.png](url)
[https://s1.ax1x.com/2023/03/10/ppuUKaj.png](url)

**Comment by MicroCBer** [comment]
已修复的问题
