### ISSUE TITLE
[ Bug ] 安装betterncm后无法修改歌曲下载目录

### ISSUE THREAD

**Issue by Apkeniqo** [MicroCBer/BetterNCM#331]
### Bug 描述

如题

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

能在不用卸载betterncm的情况下更换音乐下载文件夹

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

8d8117c

**Comment by feng-or** [comment]
请先移除主程序后，修改完毕再装回

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
duplicated #211
