### ISSUE TITLE
[ Bug ] 启动时报错，疑似编码问题

### ISSUE THREAD

**Issue by zizouqi** [MicroCBer/BetterNCM#333]
### Bug 描述

Win 10 系统，系统语言为英文，启动时报错如图。

![Snipaste_2023-03-12_23-52-55](https://user-images.githubusercontent.com/49933676/224546073-0f6d4ce6-0a6c-4a44-af11-423ad9424859.png)

在用 Installer 更新为 BetterNCM 最新版本时出现，大约半年前的老版本无问题正常使用。

### 复现步骤

启动即报错。

### 期望行为

期望修复。

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1:aa07988

**Comment by HentaiMikuy** [comment]
如何不嫌麻烦的话，可以通过修改系统设置中区域设置，将“Beta版：使用Unicode UTF-8 提供全球语言支持”勾选上，再重新启动系统，打开网易云就不会报编码错误。

**Comment by MicroCBer** [comment]
duplicated #338
