### ISSUE TITLE
[ Bug ] 用不了http代理

### ISSUE THREAD

**Issue by giaonice** [MicroCBer/BetterNCM#335]
### Bug 描述

启用自定义代理后经过代理测试可使用，但仍然显示无网络

### 复现步骤

1、设置
2、工具
3、自定义代理

### 期望行为

可以使用代理

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.6

**Comment by Mu0xi** [comment]
在C:\betterncm\config.json里把"cc.microblock.betterncm.ignore-certificate-errors":"true"加进去就好了

**Comment by MicroCBer** [comment]
这是因为在 BetterNCM 1.1.0 (https://github.com/MicroCBer/BetterNCM/commit/5f84ddd5d553c652273be1c24c533a9d10a17c88) 中，将忽略 https 证书默认设为了禁用。在此前的版本中，忽略证书错误被设为默认强制开启，这可以让某些使用 MITM 攻击修改网易云请求的代理可以在不导入自签名根证书的情况下运行，但是也可以使攻击者有可能直接获取到你的网易云登录信息，是非常不安全的行为。你可以通过在设置项中添加

```
"cc.microblock.betterncm.ignore-certificate-errors":"true"
```
以再次开启忽略证书限制。
