### ISSUE TITLE
[ Bug ] 由1.0.2版本更新到1.1.0后，网易云内置 输出设备切换失效

### ISSUE THREAD

**Issue by Nervedao** [MicroCBer/BetterNCM#336]
### Bug 描述

无论网易云内设置任意一个输出设备，均由系统默认输出设备输出音乐，且手动降级1.0.2后问题依然存在（未更新前一切正常，无任何插件增减）

### 复现步骤

更新到1.1.0后
（无任何插件增减）

### 期望行为

查明原因或提出解决办法

### 屏幕截图

![image](https://user-images.githubusercontent.com/127742402/224692583-515ab4f0-de88-42f6-8adb-c33907710665.png)

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

1:8d8117c

**Comment by Rothes** [comment]
是不是装了 [LibFrontendPlay](https://github.com/BetterNCM/LibFrontendPlay)

**Comment by Nervedao** [comment]
> 是不是装了 [LibFrontendPlay](https://github.com/BetterNCM/LibFrontendPlay)

取消启用确实解决了问题，但为什么没更新前启用时没有这个问题呢

**Comment by MicroCBer** [comment]
LFP 会取代网易云的播放系统，所以网易云输出设置就没有用了，可以在windows设置内改
