### ISSUE TITLE
安装后打开网易云不起效果，

### ISSUE THREAD

**Issue by Pr-159** [MicroCBer/BetterNCM#337]
### Bug 描述

如图，之前配置好了，今天有一个任务栏歌词的更新，更新完以后任务栏没有显示歌词，重载几次插件网易云就和图二一样了。

此后每一次打开网易云都会出现图一的白色对话框，点击确定，网易云自动打开，成图二的样子。

重新安装，使用了测试通道仍未解决。

### 复现步骤

更新任务栏歌词，歌词未正常显示 -> 重载插件数次 -> 发现无效后关掉网易云重开 -> 出现白色对话框 -> 点击确定 -> 网易云自动打开，BetterNCM 本体未起任何效果 -> 重复第三至六步 -> ... -> 重新安装 -> 重复第三至六步 -> ... -> 卸载使用测试通道 -> ...

### 期望行为

BetterNCM 正常工作

### 屏幕截图

![image](https://user-images.githubusercontent.com/67935478/224711163-83d07e1f-4c48-47a5-9161-f4b1ec90edf6.png)
![image](https://user-images.githubusercontent.com/67935478/224711300-8b952e2e-32b8-444a-82a4-cb9159a53b0f.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

8d8117c

**Comment by Keith-the-wise** [comment]
我的任务栏歌词插件也出问题了，现在本地音乐的歌词也读取不了，删掉了那个插件也没用，好像都是更新1.1.0后出的问题

**Comment by Pr-159** [comment]
重启电脑后就解决了，任务栏歌词也正常了

**Comment by xxpoi002** [comment]
网易云音乐.用管理员身份运行
