### ISSUE TITLE
[ Bug ] 更新到1.1.0版本出现没有Unicode字符建议映射到字符

### ISSUE THREAD

**Issue by yuexl258** [MicroCBer/BetterNCM#338]
### Bug 描述

????在多字节的目标代码页中，没有此Unicode字符可以映射到的字符。

### 复现步骤

1.今日晚上打开网易云，看到有更新到新版本，于是我点了更新
2.就出现这个提示，打开网易云，BetterNCM未加载
3.重新打开也提示这个，于是我把BetterNCM卸载之后进行重新安装，仍然提示
4.这个提示会连续出现三次，第一次出现点击确定之后，后面两个同时出现

### 期望行为

修复此bug

### 屏幕截图

![bug](https://user-images.githubusercontent.com/68294135/225022185-ab056625-2ca7-4bbf-9e6a-cc3ca328d3d5.png)

### BetterNCM 版本

1.1.0-nightly

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

1:8d8117c

**Comment by yami1772** [comment]
+10086

**Comment by yami1772** [comment]
![image](https://user-images.githubusercontent.com/64481110/225554781-155e69dd-9273-4e00-a11c-b71629f8fea5.png)
可能是这个问题？会自动重命名为这个

**Comment by Rothes** [comment]
重复议题 https://github.com/MicroCBer/BetterNCM/issues/333

**Comment by MICOAST** [comment]
> ![image](https://user-images.githubusercontent.com/64481110/225554781-155e69dd-9273-4e00-a11c-b71629f8fea5.png) 可能是这个问题？会自动重命名为这个

是的，将这个插件删除后可正常更新和启动

**Comment by MicroCBer** [comment]
哇这个居然还有人在用…删了换新版本的 TinyNCM 吧，这个是写给老版本 BetterNCM 的
