### ISSUE TITLE
[ Bug ] 左边栏和右边区域会重叠

### ISSUE THREAD

**Issue by rainpenber** [MicroCBer/BetterNCM#339]
### Bug 描述

从前几个版本开始出现的，左边菜单栏和右边区域会重叠。（详情见图）
复现比较困难。目前仅有我一个人遇到过这个情况，但是无法解决，且不知道如何定位问题

怀疑是插件问题，尝试：更新网易云客户端、卸载重装BetterNCM，清理BetterNCM文件夹（C:\betterncm）均不能解决问题、
在新的电脑上安装没有问题。

### 复现步骤

1. 安装插件后，来到BetterNCM设置界面会发生重叠行为。
2. 如果手动拖动以改变边栏宽度，松开后又会恢复正常。但是切换另一个页面又会遇到这个情况

### 期望行为

希望他们不要重叠

### 屏幕截图

![Snipaste_2023-03-14_21-05-18](https://user-images.githubusercontent.com/15974476/225010891-8b25aa71-7ca3-44ae-b299-aaa1a594a9c2.png)
![20230314_211237](https://user-images.githubusercontent.com/15974476/225023656-124ca787-e816-43e3-bcd1-b731df836f4e.gif)

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7(Build200863)

### 网易云音乐 Patch 版本

1:111de9c

**Comment by cale044** [comment]
使用滚动条隐藏

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by rainpenber** [comment]
> 使用滚动条隐藏
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

尝试了下，似乎没有解决问题
![Snipaste_2023-03-14_23-32-26](https://user-images.githubusercontent.com/15974476/225053198-f9da8a88-9a87-476e-8ba6-f744b3c624b9.png)

**Comment by cale044** [comment]
请尝试把侧边栏拉到最小

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
实际上把侧边栏拉到最小可以解决这个问题

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
