### ISSUE TITLE
支持以 MSIX 方式安装的网易云

### ISSUE THREAD

**Issue by Lapis-Apple** [MicroCBer/BetterNCM#34]
在 Microsoft Store 有由网易云官方上架的 MSIX 转制版本网易云。

得益于 MSIX 本身的沙盒性，使用它可以获得更好的隔离，以得到更好的安全性。

MSIX 还有“在卸载后完全不会有残留”的好处等。

经过本人测试，下载网易云在 Store 的 MSIX 文件并加入 BetterNCM 的 DLL 重新打包之后，一切工作正常。

这里是经过本人修改的 MSIX，供测试和参考。除加入必要的 DLL 以及重新签名外，和原版一致，并无法和原版并存。

https://1drv.ms/u/s!AjG6GhGcFZACplbjGBOcvKefTlAh?e=B1Vfin

同时这里是签名所使用的证书文件。

https://1drv.ms/u/s!AjG6GhGcFZACpleIhDbmHfqthEwl?e=SFJZFU

在 Windows 10 LTSC 2021 上测试完全正常。

**Comment by yuki-one** [comment]
牛啊，客户端不支持的unblockmusic   UWP版本居然支持

**Comment by Lapis-Apple** [comment]
在此发布新重打包的 MSIX 网易云，代号 “NeteaseCloudMusicBN”。

- 基于官方网易云 v10.2.3，Store 版。
- 修改了包名，现在其应该可以和几乎所有官方版（例如 UWP，Store 版，官网版）并存。
- 内置 BetterNCM 0.2.3。
- 替官方略微优化了图标边缘过于僵硬的问题。
- 在 Windows 10 上以标准尺寸固定磁贴时使用透明背景（而不是丑炸的巨大红色图标）。资源从老 UWP 版本提取。

签名用的证书依然是上面那个证书，不过我其实建议大家自己重新签名。

兼容性的话.. 理论上，只要系统兼容官方 Store 版网易云，那就一定兼容这个重打包版。
下载： https://1drv.ms/u/s!AjG6GhGcFZACplkFcQmImP7f-JH6?e=Q1iQJH

**Comment by BRanulf** [comment]
链接是不是挂了？
证书和下面的版本链接均无法访问

<img width="506" height="366" alt="Image" src="https://github.com/user-attachments/assets/a5e3bd3a-d4f6-45fb-99e7-b28f405c4547" />

**Comment by Remik1r3n** [comment]
> 链接是不是挂了？ 证书和下面的版本链接均无法访问
> 
> <img alt="Image" width="506" height="366" src="https://private-user-images.githubusercontent.com/188014413/473974750-a5e3bd3a-d4f6-45fb-99e7-b28f405c4547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMDE3MTcsIm5iZiI6MTc1NDMwMTQxNywicGF0aCI6Ii8xODgwMTQ0MTMvNDczOTc0NzUwLWE1ZTNiZDNhLWQ0ZjYtNDVmYi05OWU3LWIyOGY0MDVjNDU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNFQwOTU2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGUxODlkODFmYWU0OTU0NTZlODE3Mjk5YzQyNDRhMGM4YmNkMjQzNzNlNTU1MWUxNDBlY2VjOTU1YWQwNWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WaQzp-7pbfvaKXRC4CJuHoO-d6ECtzNqh1GZqwKrnMA">

https://1drv.ms/f/c/0290159c111aba31/EuUKXKo-3eJAsyy8zMrvsNIBS6Yit741JH_YRj_fnCcmhA?e=89bHuv
已更新
