### ISSUE TITLE
[ Bug ] 这插件的Bug似乎和BetterNCM本身有联系，希望能协同解决

### ISSUE THREAD

**Issue by China-Mr-Hou** [MicroCBer/BetterNCM#340]
### Bug 描述

关闭cloudmusic.exe后，再次启动时提示taskbar-lyrics.exe拒绝访问，且全部插件（包括BetterNCM本身）不加载。
在taskmgr中手动结束taskbar-lyrics.exe进程之后可修复

### 复现步骤

1. 确保安装了Taskbar Lyrics插件并启动
2. 正常关闭NCM（托盘右键-退出）
3. 再次启动NCM

### 期望行为

不论如何关闭NCM，再次启动时不提示拒绝访问，同时插件全部正常加载

### 屏幕截图

<img width="266" alt="image" src="https://user-images.githubusercontent.com/125100179/225179412-476daff1-63db-43fb-b50b-35e663d17234.png">

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

8d8117c

**Comment by China-Mr-Hou** [comment]
已经在该插件仓库下的issue区域反馈

**Comment by MicroCBer** [comment]
这是因为taskbar lyrics没有使用betterncm使用的标准native plugin格式，占用了临时文件夹导致临时文件夹无法删除而报错，并不是betterncm本体的问题。

建议插件作者修改至类似unblock插件运行第三方应用程序的形式。
