### ISSUE TITLE
[ Bug ] 在2023.3.15win10系统强制更新后，打开网易云提示已崩溃，可能由于插件引起。

### ISSUE THREAD

**Issue by fishbone233** [MicroCBer/BetterNCM#341]
### Bug 描述

2023.3.15win10系统强制更新后，打开网易云跳弹窗提示网易云已崩溃：
BetterNCM网易云音乐崩溃BetterNCM网易云音乐崩溃

Exception code 0x000001d(LLEGAL INSTRUCTION)Exception flags: 0x0

Exception address. 0x5001D769

Context record:

EIP: 0x5001f085

ESP: 0xd1e0ac

EBP: 0x0

Backtrace:

See console for detail

In Process.0x10

这有可能是由于插件引起的崩溃，要重启网易云音乐吗?

点击中止以直接结束网易云点击重试以直接重启网易云

Sit(A)

Wit(R)

BFE()
多次点击重试/中止没有改善，只能点击忽略（禁用插件）来加载网易云。

### 复现步骤

1.  点击网易云图标
2. 立刻跳出弹窗， 提示崩溃。

### 期望行为

希望问题被解决。

### 屏幕截图

![屏幕截图(1473)](https://user-images.githubusercontent.com/128005508/225480308-e4352002-c77f-4f52-9ef5-f0f11f9dcbfb.png)

### BetterNCM 版本

1.0.2.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

1：111de9c

### 补充

win10版本22H2

**Comment by SamuraiQAQ** [comment]
一样遇到了，但是里面有个防崩溃的插件可以安装下

**Comment by fishbone233** [comment]
> 一样遇到了，但是里面有个防崩溃的插件可以安装下

！！！可以发下这个防崩溃插件的下载网址么（我依稀记得在我的BetterNCM还能用的时候在插件列表里下过一个名字叫“能够防止部分崩溃原因的”？）

**Comment by MicroCBer** [comment]
看下控制台

**Comment by fishbone233** [comment]
> 看下控制台

![image](https://user-images.githubusercontent.com/128005508/225820306-a89b3404-eaf0-4141-b3a5-1cb070ae54da.png)
这个么?

**Comment by cale044** [comment]
6

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
在崩溃后会自动弹出一个黑窗口

**Comment by fishbone233** [comment]
> 在崩溃后会自动弹出一个黑窗口

![image](https://user-images.githubusercontent.com/128005508/225820640-59755642-2405-44ae-8488-e1aeb2bb53c7.png)

**Comment by MicroCBer** [comment]
请手动删除 RuLyrics

如果愿意，可以再次安装 RuLyrics 最新版，以测试问题是否已经修复
