### ISSUE TITLE
[ Bug ] JavaScript API dom函数报错

### ISSUE THREAD

**Issue by samyycX** [MicroCBer/BetterNCM#342]
### Bug 描述

按照Wiki内的教程代码:
```javascript
dom('p', {}, 'Hello!');
```
直接在控制台输入，会报以下错误
`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`
应该是参数'Hello!'导致的，删除就不报错了

### 复现步骤

直接在F12控制台输入Wiki中的代码:
```javascript
let myDiv = dom('div', {class: 'my-div'}, 
    dom('p', {}, 'Hello!'),
    dom('p', {}, 'World!')
);
```

### 期望行为

正常使用不报错

### 屏幕截图

![QQ截图20230318171724](https://user-images.githubusercontent.com/60744529/226096764-ee09abad-5581-4680-baed-224c6716f957.png)

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

f8712c1

**Comment by MicroCBer** [comment]
chatgpt出来受罚！

fixed

**Comment by samyycX** [comment]
草，效率这么高
