### ISSUE TITLE
能否支持旧版网易云 

### ISSUE THREAD

**Issue by Enchanter-W** [MicroCBer/BetterNCM#343]
### 描述你想要的功能

希望可以支持旧版的网易云（2.9.7）
因为正在使用的那个网易云音乐的解析插件不能支持新版本的网易云

**Comment by cale044** [comment]
更新不好嗎，爲什麽要用舊版本

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by MicroCBer** [comment]
不可能
