### ISSUE TITLE
[ Plugin Bug ] 插件市场页面显示异常

### ISSUE THREAD

**Issue by SteveXu9102** [MicroCBer/BetterNCM#345]
### Bug 描述

BetterNCM的插件市场页面内所有元素出现严重闪烁、遮挡问题

### 复现步骤

1. 点击右上角'最大化'
2. 点击BetterNCM图标
3. 点击页面内左边栏‘PluginMarket’
4. 看到错误

### 期望行为

正常显示

### 屏幕截图

** 页面内所有异常显示的元素会随鼠标光标移动出现不定期闪烁 **
![QQ图片20230323223119](https://user-images.githubusercontent.com/68725147/227236134-99a5c0b5-0a86-4090-af14-5c0de8a3442c.png)

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

a395d7a

### 已安装插件

 - ActionEnhancement
 - crossfade-lfp
 - FluentMusicCover
 - FluentProgressBar
 - LibEAPIRequest
 - liblyric
 - list-scroll-fix
 - LyricBar
 - MaterialYouTheme
 - PluginMarket
 - RefinedNowPlaying
 - remove-tracking-attribute
 - RoundCornerNCM
 - StyleSnippet

### 补充

1. 该情况只会在主界面最大化时出现，主界面未最大化时可正常显示；
2. 推测可能与某个插件的更新相关 （该情况在某次插件更新之后出现）（不记得是哪个了，抱歉）；

**Comment by WindLeaf233** [comment]
同样的问题。经测试，是 `MaterialYouTheme` 插件导致的问题。在卸载上述插件后，相关症状均消失。

我在 `solstice23/material-you-theme-netease` 开了一个 `Issue`：[material-you-theme-netease#66](https://github.com/solstice23/material-you-theme-netease/issues/66)，你可以关注下。

**Comment by solstice23** [comment]
已修复
