### ISSUE TITLE
忘记是哪个插件了，原先是可以设置字体颜色的，现在没了，但是还是很需要这个东西

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#346]
### 你的功能请求是否与某个问题/需求有关？请描述

添加文字颜色设置功能

### 描述你想要的解决方案

可以设置字体的暗色，原先是在哪个插件里忘记了，由于我现在用了一个比较明亮的背景，导致经常看不清文字

**Comment by feng-or** [comment]
tinyncm或者miku 也可以使用明暗主题切换器

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by cale044** [comment]
tinyncm不能自定义字体颜色

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by luotianyiismywife** [comment]
> tinyncm或者miku 也可以使用明暗主题切换器
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

tinyncm只能修改字体，修改不了颜色。
miku没有找到，你的意思是建议自己写css么

**Comment by cale044** [comment]
MikuPlugin啊没有吗

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by luotianyiismywife** [comment]
没有的发自我的手机-------- 原始邮件 --------发件人： 坐在桥上看猫 ***@***.***>日期： 2023年3月25日周六 01:22收件人： MicroCBer/BetterNCM ***@***.***>抄送： luotianyiismywife ***@***.***>, Author ***@***.***>主    题： Re: [MicroCBer/BetterNCM] 忘记是哪个插件了，原先是可以设置字体颜色的，现在没了，但是还是很需要这个东西 (Issue #346)
MikuPlugin啊没有吗


Generated by koishi-plugin-github.

**Comment by feng-or** [comment]
![image](http://koi.microblock.cc:5140//files/6e559b4136585da0dab3383d31c9acea6faaa07e-4969d878e83627c53409b940fec099f7.image)

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by feng-or** [comment]
> 没有的发自我的手机-------- 原始邮件 --------发件人： 坐在桥上看猫 ***@***.***>日期： 2023年3月25日周六 01:22收件人： MicroCBer/BetterNCM ***@***.***>抄送： luotianyiismywife ***@***.***>, Author ***@***.***>主    题： Re: [MicroCBer/BetterNCM] 忘记是哪个插件了，原先是可以设置字体颜色的，现在没了，但是还是很需要这个东西 (Issue #346)
> MikuPlugin啊没有吗
> 
> 
> Generated by koishi-plugin-github.
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

![9Y}5H~GJ_8L1EA3(15RT11J.png](https://user-images.githubusercontent.com/104701550/227678223-d148fb6a-0669-41b3-b2da-62743a5cd127.png)

**Comment by MicroCBer** [comment]
TinyNCM 已支持

![image](https://user-images.githubusercontent.com/66859419/227698743-b9a23a4c-5620-4210-9d77-b4e183e45eb6.png)

（一般改一个“一般文字”选项即可）

**Comment by luotianyiismywife** [comment]
![图片](https://user-images.gitshenmedouent.com/81459639/227776760-ba16a409-ab91-40c4-b894-4bb760e6ac98.png)
我这里还是什么都没有。。。。。

**Comment by luotianyiismywife** [comment]
![图片](https://user-images.githubusercontent.com/81459639/227776786-50832664-119c-421e-9f27-93d54032d665.png)

我这里还是什么都没有
