### ISSUE TITLE
[ Plugin FR ] UnblockNeteaseMusic/server-rust 插件

### ISSUE THREAD

**Issue by Creepercdn** [MicroCBer/BetterNCM#347]
### 你的功能请求是否与某个问题/需求有关？请描述

添加一个插件，在播放 VIP 和不可用（灰色）曲目时替换成从 server-rust 请求到的音源。

### 描述你想要的解决方案

如上。

可以添加一个菜单，用于手动替换音源（如果 server-rust 的 REST API 支持的话，还可以显示所有的候选音源）。

如果可能的话，对被替换的曲目开放下载功能。

### 额外的背景

更具体一点地说，替换掉 NCM 内部获取音乐 URL 的逻辑（或者借用 libfrontendplay 的思路，播放时替换 URL），用从 server-rust 请求到的音源替换掉原来不可用的。

**Comment by MicroCBer** [comment]
只能说 曾经有过
