### ISSUE TITLE
[ Plugin Bug ] 插件冲突 不确定哪个插件

### ISSUE THREAD

**Issue by Healock** [MicroCBer/BetterNCM#350]
### Bug 描述

重启后产生，怀疑是某缓存因为强制结束进程 不完整而出错

-------- BetterNCM CrashReport -------
BackTrace:

C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 4397(`?w詗咠€?I?w)
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 57AB8(cxxbridge1$rust_vec$str$reserve_total)

--------------------------------------

classname: "Shell_TrayWnd", traywin: 10104

-------- BetterNCM CrashReport -------
BackTrace:

C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1C32A( ?? )
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1CB02( ?? )
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1DDE5(BetterNCMPluginMain)
C:\Program Files (x86)\Netease\CloudMusic\MSIMG32.dll + 6988D(TransparentBlt)
C:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe + EBE60C(TransparentBlt)
C:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe + 3A588C3D(TransparentBlt)

--------------------------------------

### 复现步骤

无法正常运行网易云，故无法复现

### 期望行为

正常运行

### 屏幕截图

![HGE@9 KWQOX_T{}APGF{@%I](https://user-images.githubusercontent.com/59949582/227787278-991df4a6-77e9-4b73-8efa-5b92c03fea08.png)

### BetterNCM 版本

1.0.2

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

db18145

### 已安装插件

- ActionEnhancement-0.1.6 
- FluentProgressBar-0.2.0
- InfLink-0.1.8
- LibEAPIRequest-1.6.2
- liblyric-1.0.0
- list-scroll-fix-0.1.0
- LyricBar-0.3.2
- PluginMarket
- RefinedNowPlaying-2.15.3
- relive-theme-0.5.3
- RuLyrics-0.3.4
- StyleSnippet-0.2.0
- VisualRecord-1.0.2
- What-is-the-cover-of-this-music-2.0.8

**Comment by MicroCBer** [comment]
尝试删除用户文件夹下 文件名含有 lastpos 的文件
