### ISSUE TITLE
[ Bug ] BetterNCM 在尝试解压格式不正确的 .plugin 插件包时会发生问题

### ISSUE THREAD

**Issue by Steve-xmh** [MicroCBer/BetterNCM#352]
### Bug 描述

BetterNCM 在尝试解压格式不正确的 .plugin 插件包时会出错崩溃或正常打开网易云但 BetterNCM 及其插件均不会加载。

### 复现步骤

随意拿一个不是正确的 .zip 格式然后改名为 .plugin 文件后放入插件文件夹下即可复现。
（创建一个空文件然后改名也可以复现）

### 期望行为

会提出警告并继续解压其他插件/显示错误并退出

### 屏幕截图

因为是直接崩溃退出所以没有截图

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.7

### 网易云音乐 Patch 版本

0ade34e

### 补充

关联 Issue：https://github.com/Steve-xmh/applemusic-like-lyrics/issues/93

**Comment by Nanodayoo** [comment]
啊 不对啊 该怎么解决啊0-0

**Comment by solstice23** [comment]
https://github.com/MicroCBer/BetterNCM/commit/a6467be0a84a75a894752ae43666548e27abc7af

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/228872719-5a8a09f6-0c06-4e14-be2d-aeec14861fb6.png)
