### ISSUE TITLE
[ Plugin FR ] 之前有个解灰插件，好久没看，怎么现在没了啊

### ISSUE THREAD

**Issue by wentlwr** [MicroCBer/BetterNCM#358]
### 你的功能请求是否与某个问题/需求有关？请描述

网易云解除歌曲置灰状态，置灰歌曲可以播放

### 描述你想要的解决方案

置灰歌曲可以播放

**Comment by MicroCBer** [comment]
https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller
