### ISSUE TITLE
需要管理员运行网易云才能读取配置文件，希望能改一下配置文件存放地址

### ISSUE THREAD

**Issue by Recruit-b** [MicroCBer/BetterNCM#359]
### 描述你想要的功能

双击打卡网易云报错信息，打开以后无法加载插件：

BetterNCM
BetterNCM ????
BetterNCM ?????
222222222
?????remove all: 拒绝访问"C: betterncm/plugins runtime LibEAPIRequest
确定

使用管理员运行打开网易云正常使用

### 描述你考虑过的替代方案

希望能改一下配置文件存放地址or自定义配置文件存放地址，在插件里面新增设置即可

### 额外的背景

![Snipaste_2023-04-10_10-18-11](https://user-images.githubusercontent.com/68763803/230812916-4298adcd-b510-4c62-b4de-8a68223b9a4d.png)

**Comment by MicroCBer** [comment]
duplicated #27
