### ISSUE TITLE
[ Bug ] 杜比全景声在使用betterNCM后不可用

### ISSUE THREAD

**Issue by 9thChasingWindGirl** [MicroCBer/BetterNCM#364]
### Bug 描述

在播放器支持杜比全景声的歌曲切换到杜比时，无法播放，进度条不走进度

### 复现步骤

无需复现，尚不清楚是哪一个插件的原因

### 期望行为

检查这个问题即可，

### 屏幕截图

![微信图片_20230416152443](https://user-images.githubusercontent.com/69580996/232280298-da775557-4db9-4fe8-a55f-6c22b59ec7ae.png)
![微信图片_20230416152417](https://user-images.githubusercontent.com/69580996/232280303-4ac7b078-36c2-4ac6-a376-b7993be1ea34.png)

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

6f4f404

**Comment by MicroCBer** [comment]
LibFrontendPlay 尚不支持杜比等音效，也不会支持
