### ISSUE TITLE
[ FR ] 建议在README中添加如何卸载教程

### ISSUE THREAD

**Issue by Ya2gLu** [MicroCBer/BetterNCM#366]
### 描述你想要的功能

- 因为安装插件导致内存占用大和时常卡顿的原因，所以想卸载回归默认状态。
- 在删除了插件目录后网易云插件图标并没有消失，希望可以提供一个卸载的入口。

**Comment by solstice23** [comment]
有没有一种可能，安装器安装按钮的旁边就是卸载按钮

**Comment by MicroCBer** [comment]
😅
