### ISSUE TITLE
[ Bug ] 是更新以后，不能在“下载”按钮上右键下载apk了吗

### ISSUE THREAD

**Issue by RizukiJI** [MicroCBer/BetterNCM#367]
### Bug 描述

是更新以后，不能在“下载”按钮上右键下载apk了吗

### 复现步骤

0.25版本：右键“下载” - 跳网页 - 下载成功、
更新到1.2.0：右键“下载” - 跳网页 - 下载成功、

### 期望行为

希望是有佬告诉我是缺哪个扩展了还是就没有这个功能了，还是我自己出bug了

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

6f4f404

**Comment by cale044** [comment]
什么下载apk

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by RizukiJI** [comment]
说错了……mp3



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月18日 23:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MicroCBer/BetterNCM] [ Bug ] 是更新以后，不能在“下载”按钮上右键下载apk了吗 (Issue #367) |

什么下载apk

Generated by koishi-plugin-github.

**Comment by MicroCBer** [comment]
下载 mp3 的老 API 没了，虽然可以用 LFP 做但是有版权风险，就不做了

**Comment by RizukiJI** [comment]
懂了，那我用旧版本的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月01日 12:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MicroCBer/BetterNCM] [ Bug ] 是更新以后，不能在“下载”按钮上右键下载apk了吗 (Issue #367) |

下载 mp3 的老 API 没了，虽然可以用 LFP 做但是有版权风险，就不做了

**Comment by MicroCBer** [comment]
API 没了用旧版本有啥用。。。

**Comment by RizukiJI** [comment]
我前几天用旧版本的就可以下载……



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月01日 12:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MicroCBer/BetterNCM] [ Bug ] 是更新以后，不能在“下载”按钮上右键下载apk了吗 (Issue #367) |

API 没了用旧版本有啥用。。。

**Comment by MicroCBer** [comment]
哦 刚刚试了一下 貌似是改成认证了 那我加回来
