### ISSUE TITLE
有什么办法能获取到当前正在播放的音乐名称吗?

### ISSUE THREAD

**Issue by LastStranger** [MicroCBer/BetterNCM#371]
### 描述你想要的功能

有什么办法能获取到当前正在播放的音乐名称吗?

### 描述你考虑过的替代方案

没找到

### 额外的背景

我想获取到当前正在播放的音乐信息,并将该信息实时传到另外一个地方

**Comment by MicroCBer** [comment]
## BetterNCM API
`betterncm.ncm.getPlayingSong()`

## InfLink 插件
[SMTC API](https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22621)

建议在开 Issue 之前先看看文档

**Comment by LastStranger** [comment]
> ## BetterNCM API
> `betterncm.ncm.getPlayingSong()`
> 
> ## InfLink 插件
> [SMTC API](https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22621)
> 
> 建议在开 Issue 之前先看看文档
这个SMTC API只支持网页上的吧?我看调用方法都是window.media.XXX, 这个betterncm.ncm.getPlayingSong()在哪个地方,我搜索了一圈文档还是没找到, 另外这个支持mac吗?

**Comment by yangnuozhen** [comment]
> > ## BetterNCM API
> > `betterncm.ncm.getPlayingSong()`
> > ## InfLink 插件
> > [SMTC API](https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22621)
> > 建议在开 Issue 之前先看看文档
> > 这个SMTC API只支持网页上的吧?我看调用方法都是window.media.XXX, 这个betterncm.ncm.getPlayingSong()在哪个地方,我搜索了一圈文档还是没找到, 另外这个支持mac吗?

不是很能理解您的意思。可以简要描述您的需求吗？另，`betterncm.ncm.getPlayingSong()` 应在F12中的控制台运行。

Like This:

![Like This](https://github.com/MicroCBer/BetterNCM/assets/56541171/8d3473c7-0cc4-462a-933a-c2f732de5520)
