### ISSUE TITLE
InfLink 在win10 专业版中会崩溃

### ISSUE THREAD

**Issue by Crying-qi** [MicroCBer/BetterNCM#372]
### Bug 描述

下载完InfLink重启网易云崩溃
只有删除插件才能使用
![屏幕截图 2023-04-30 001103](https://user-images.githubusercontent.com/115856855/235312465-60f1f606-2f77-4c33-885a-764f339eae67.png)

### 复现步骤

1.下载InfLink
2.点击自动弹出的重启按钮
3.重启完成显示奔溃 

### 期望行为

更新win10 专业版本的InfLink插件

### BetterNCM 版本

BetterNCM Installer版本1.0.2

### 网易云音乐版本

网易云版本2.10.8

### 网易云音乐 Patch 版本

6f4f404

### 已安装插件

InfLink

**Comment by MicroCBer** [comment]
已修复

**Comment by Crying-qi** [comment]
爱死啦
