### ISSUE TITLE
[ Bug ] 网易云10.8.2安装插件闪退

### ISSUE THREAD

**Issue by slromusb** [MicroCBer/BetterNCM#373]
### Bug 描述

操作系统：Windows 11 22H2系统最新版
问题描述：不安装插件，网易云能正常打开，安装插件之后打开网易云看不到界面进程显示一秒左右直接闪退，安装盘在C盘和D盘都经测试同样情况，直接卸载网易云，重新安装在曾经的安装网易云有插件的目录（网易云卸载之后，有插件dll文件log等残留）还是闪退，删除插件残留一切正常。

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

事出紧急,诚恳地请您尽快解决,感激之情,溢于言表。

### 屏幕截图

![卸载残留文件](https://user-images.githubusercontent.com/124541512/235367419-72fa5f64-cad9-4800-90d4-7d2a16a7cc9d.png)
![log文件乱码](https://user-images.githubusercontent.com/124541512/235367425-d90fb9fa-6912-43fc-8753-77b4aae9cfd9.png)
[debug.zip](https://github.com/MicroCBer/BetterNCM/files/11361911/debug.zip)

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8.200945.

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

**例**:
- StylesheetLoader
- ActionEnhancement
安装了很多插件前天还可以用，今天打不开所以卸载重装了一下

### 补充

安装插件闪退,测试中文目录和英文目录，是一样的情况

**Comment by MicroCBer** [comment]
请更新 InfLink

**Comment by slromusb** [comment]
大佬，安装主体插件网易云就打不开如何更新InfLink插件，麻烦给开个药方

**Comment by feng-or** [comment]
> 大佬，安装主体插件网易云就打不开如何更新InfLink插件，麻烦给开个药方

没有任何报错吗

**Comment by slromusb** [comment]
没有报错，直接闪退，卸载完主体插件，立马就能打开，不知道什么原因，网易云客户端已经更新到2.10.9，插件更新1.0.3，还是闪退

**Comment by slromusb** [comment]
闪退都看不到网易云界面，进程就直接结束了

**Comment by feng-or** [comment]
参考这个手动卸载inflink
https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme?from=tab_home#XoOEdoaU2o0G22x6Cx4cOt8knxg
应该是这个的原因，正常有报错才对

**Comment by slromusb** [comment]
ヽ(・∀・)ﾉ感谢成功解决，我把C:/betterncm整个文件全删了，已经可以正常打开了，可能是内置插件冲突了，谢谢大佬(o･ω･o)
