### ISSUE TITLE
[ Bug ] 系统盘盘符不是C时无法使用

### ISSUE THREAD

**Issue by Apkeniqo** [MicroCBer/BetterNCM#374]
### Bug 描述

系统为win11，盘符为E，安装后无法打开网易云音乐，卸载后正常，切换回win10（盘符为C）正常

### 复现步骤

必要条件：系统盘盘符不为C
步骤：使用betterncm安装器安装插件
结果：网易云音乐无法启动

### 期望行为

在系统盘为任意盘符时可正常启动网易云音乐

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

1:6f4f404

**Comment by MicroCBer** [comment]
请按照：https://github.com/MicroCBer/BetterNCM/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E4%BF%AE%E6%94%B9%E6%8F%92%E4%BB%B6%E6%95%B0%E6%8D%AE%E4%BD%8D%E7%BD%AE 修改数据位置
