### ISSUE TITLE
[ Bug ] 设置中无法自定义

### ISSUE THREAD

**Issue by pglterry** [MicroCBer/BetterNCM#377]
### Bug 描述

在设置中，点击自定义插件源无效（闪现“加载插件中”页面）。
尝试过重装网易云和BetterNCM插件（删除所有已装插件）
![GIF 2023-05-05 14-34-42](https://user-images.githubusercontent.com/44747145/236392289-99713bee-2b28-4ac0-a722-fe40578b768b.gif)
[Profile-20230505T123025.zip](https://github.com/MicroCBer/BetterNCM/files/11403830/Profile-20230505T123025.zip)

### 复现步骤

1. 点击"BetterNCM“图标
2. 点击已安装右边的小齿轮
3. 点击'自定义'
4. 看到错误

### 期望行为

能正常添加自定义源

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.9

### 网易云音乐 Patch 版本

1:00469c4

### 补充

安装ReviveSource插件无效，似乎和这个问题有关联

**Comment by fbstorm** [comment]
+1

**Comment by ldqs365** [comment]
+1

**Comment by likfees** [comment]
+1

**Comment by ReviveUnblockNCMInstaller** [comment]
请见 [README.md](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller) 公告部分。
