### ISSUE TITLE
网易云桌面歌词无法滚动。

### ISSUE THREAD

**Issue by Cx-666** [MicroCBer/BetterNCM#379]
### Bug 描述

在安装插件后，网易云桌面歌词无法正常使用

### 复现步骤

1.打开网易云
2.安装插件
3.播放歌曲
4.打开桌面歌词
5.发现桌面歌词无法滚动
ps：期间没在库里安装任何一个插件模块

### 期望行为

希望修复一下这个问题

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

无

**Comment by MicroCBer** [comment]
请发送 数据路径/plugins_runtime 的截图
