### ISSUE TITLE
releases中说不与UnblockNeteseMusic冲突，但测试后发现只有网易云2.9.6能用

### ISSUE THREAD

**Issue by IASUI** [MicroCBer/BetterNCM#38]
如题，本插件要求2.10.2以上。但Unblock测试发现只能2.9.6用。所以冲突了。
如果插件能兼容更低的网易云版本或者作者写个Unblock插件就好了

**Comment by yuki-one** [comment]
测试发现置顶的大佬改的uwp版本能用https://github.com/MicroCBer/BetterNCM/issues/34

**Comment by IASUI** [comment]
> 测试发现置顶的大佬改的uwp版本能用#34

请问为啥我试了没用，我是本地使用Unblock,用的是代理模式这个方法。

**Comment by IASUI** [comment]
#34 修改的UWP版本依然不能使用Unblock
客户端2.9.6可以正常使用，是我Unblock打开方式有问题？
![image](https://user-images.githubusercontent.com/66980246/193142225-51035a36-9156-479f-a389-d733ea7be428.png)

**Comment by IASUI** [comment]
问题应该出在CLASH上，两者同时使用全局代理，导致Unblock失效。2.10.4等版本实际可以用Unblock。  之前说只有2.96刚好是巧合。

**Comment by yuki-one** [comment]
> #34修改的 UWP 版本不能仍然使用 Unblock 客户端 2.9.6 可以正常使用，是我的 Unblock 打开方式有问题吗？ ![图片](https://user-images.githubusercontent.com/66980246/193142665-f56e6cfa-09e8-46c1-8d5b-c266d03688f3.png)
> 
> ![图片](https://user-images.githubusercontent.com/66980246/193142225-51035a36-9156-479f-a389-d733ea7be428.png) ![图片](https://user-images.githubusercontent.com/66980246/193143244-96eee3b3-464f-407b-8447-dbc384f4e8f6.png)

你把unblock的两个证书【ca.crt】和【server.crt】安装为受信任的根证书了吗？
![)OY2Y $ND7`~WJU_WK S~MR](https://user-images.githubusercontent.com/76642580/193207083-86ce0679-a097-4d57-8e99-43345672ea2d.png)
还有就是如果你是本地使用的话，因为uwp默认不允许环回，你需要使用[EnableLoopback](https://raw.github.com/wiki/OpportunityLiu/E-Viewer/Tools/EnableLoopback.zip)进行解除

**Comment by IASUI** [comment]
@yuki-one   谢了哥们，是我打开方式不对，作者的这个插件还是可以和Unblock一起用的👍
我发现开CLASH后，2.9.6也不能用，我猜应该是两边都用了全局代理，所以我花了好久才弄懂把代理规则写进clash的配置文件里。然后我发现2.9.6可以用，但2.10还是不行。然后我在Unblock的issue找到说要安装证书的，安装后2.10.4就可以用了。不过我没装server.crt，因为那个过期了，还有也没按那个issue说的弄双端口https监听。但是好像也没啥大问题。

**Comment by MicroCBer** [comment]
这玩意现在我还没折腾懂...貌似有的人能用有的人不能用 之前稍微追了一下 没看出来不能用的是寄在哪了

本来写了一个自动配置并安装unblock的（还不用安装证书） 因为有人不能用就搁置了

**Comment by IASUI** [comment]
> 这玩意现在我还没折腾懂...貌似有的人能用有的人不能用 之前稍微追了一下 没看出来不能用的是寄在哪了
> 
> 本来写了一个自动配置并安装unblock的（还不用安装证书） 因为有人不能用就搁置了

@MicroCBer  😭其实我还是失败了。我发现只要先开启网易云的代理设置，再安装BetterNCM的插件，就不能联网了。但是反过来先安装BetterNCM的插件，再开启设置里的代理就没问题（我只是在几次测试中发现是这样，没细致地去对比是不是某些插件还是什么一安装就不能用）。当发生不能联网时，卸载BetterNCM也没有用；唯一的解决方法是删除网易云音乐的数据文件。
但是我目前Unblock只安装了一个ca.crt证书，所以也可能是我这边Unblock一些安装步骤没完善或者正确导致的。
而另一个过期的证书，只能自己生成，但是我看不懂啊，昨天研究代理，今天研究证书😭😭😭😭😭😭😭😭

**Comment by MicroCBer** [comment]
> > 这玩意现在我还没折腾懂...貌似有的人能用有的人不能用 之前稍微追了一下 没看出来不能用的是寄在哪了
> > 本来写了一个自动配置并安装unblock的（还不用安装证书） 因为有人不能用就搁置了
> 
> @MicroCBer 😭其实我还是失败了。我发现只要先开启网易云的代理设置，再安装BetterNCM的插件，就不能联网了。但是反过来先安装BetterNCM的插件，再开启设置里的代理就没问题（我只是在几次测试中发现是这样，没细致地去对比是不是某些插件还是什么一安装就不能用）。当发生不能联网时，卸载整个BetterNCM也没有用；唯一的解决方法是删除网易云音乐的数据文件。 但是我目前Unblock只安装了一个ca.crt证书，所以也可能是我这边Unblock一些安装步骤没完善或者正确导致的。 而另一个过期的证书，只能自己生成，但是我看不懂啊，昨天研究代理，今天研究证书😭😭😭😭😭😭😭😭

我这边测试直接禁用证书验证貌似也不太行（只能解灰 不能播放）

国庆再研究下

**Comment by yuki-one** [comment]
> @yuki-one 谢了哥们，是我打开方式不对，作者的这个插件还是可以和Unblock一起用的👍 我发现开CLASH后，2.9.6也不能用，我猜应该是两边都用了全局代理，所以我花了好久才弄懂把代理规则写进clash的配置文件里。然后我发现2.9.6可以用，但2.10还是不行。然后我在Unblock的issue找到说要安装证书的，安装后2.10.4就可以用了。不过我没装server.crt，因为那个过期了，还有也没按那个issue说的弄双端口https监听。但是好像也没啥大问题。

server.crt过期问题你可以使用https://github.com/UnblockNeteaseMusic/server  ，目前好像切换到这个库进行更新了，目前我是使用的这个项目的unblock

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/193449386-8169810f-4b86-4f05-9a60-dc5e0c4ddcf5.png)

**Comment by IASUI** [comment]
@MicroCBer 👍👍👍❤️效率高啊。不过请问我怎么没在设置和插件Market里找到这个插件呢

**Comment by PIndividual** [comment]
同问

**Comment by BLdada** [comment]
> @MicroCBer 👍👍👍❤️效率高啊。不过请问我怎么没在设置和插件Market里找到这个插件呢

先装Revived
