### ISSUE TITLE
安装插件后网易云本体崩溃

### ISSUE THREAD

**Issue by Gu-Mie** [MicroCBer/BetterNCM#381]
### Bug 描述

安装插件后网易云本体崩溃
版本信息如下
![image](https://user-images.githubusercontent.com/95342846/236719796-e969a56c-04c2-4300-acb6-eb2ce0d3c394.png)

### 复现步骤

1. 打开网易云
2. 安装插件
3. 再次重启网易云
4. 弹出崩溃信息，见下图
![image](https://user-images.githubusercontent.com/95342846/236719955-93632119-9814-4787-87ec-a7586391b95f.png)
5. 重新卸载插件后可以正常打开

### 期望行为

正常使用插件

### 屏幕截图

![image](https://user-images.githubusercontent.com/95342846/236719983-c8e12cb0-a8b1-4501-af75-72dfca5e231c.png)

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

1:b3c097c

**Comment by Gu-Mie** [comment]
抱歉 刚刚对插件清理后 再次进行重装  发现该问题已成功解决
原因推测：之前安装插件时仍保留插件目录，将所安装的 ncm 子插件删除后，便可以正常运行

**Comment by Gu-Mie** [comment]
> 请问，如何找到子插件删除

Windows的话 默认是 C 盘下的 betterncm 文件夹

**Comment by Laoevil** [comment]
你好，我也是遇到这个问题，请问是删除betterncm目录下的哪个文件夹？

**Comment by Laoevil** [comment]
没事啦，点击自动修复ok啦
