### ISSUE TITLE
[ Bug ] 无c盘插件无法正常运行

### ISSUE THREAD

**Issue by jcs233** [MicroCBer/BetterNCM#382]
### Bug 描述

电脑 （系统装在a盘）无c盘插件无法正常运行

### 复现步骤

1电脑不存在C盘
2安装启动就报错

### 期望行为

能否自定义安装路径解决这个问题

### 屏幕截图

![Uploading 屏幕截图2023-05-16231400.png…]()

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

b3c097c

**Comment by MicroCBer** [comment]
duplicated #278 #249 #233 #27

请自行修改profile路径
