### ISSUE TITLE
Material You Bug 报告：播放播客时倍速按钮未应用主题，且遮挡播放时间显示

### ISSUE THREAD

**Issue by xbx787** [MicroCBer/BetterNCM#384]
### Bug 描述

播放播客时倍速按钮未应用主题，且遮挡播放时间显示

### 复现步骤

播放任意播客
右下角，倍速按钮呈白色（未被渲染），且遮盖播放时间

### 期望行为

播放播客时，倍速按钮正常渲染主题色，时间显示左移，使之不与倍速按钮冲突，如果能做个动效就更好啦，感谢大大们！

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

ca5e0ab

### 已安装插件

**例**:
- StylesheetLoader
- BGEnhanced
- InfLink
- 明/暗主题切换器
- Material You
- RefinedNowPlaying
- CrashFix
- ListScrollFix
- RoundCornerNCM

**Comment by solstice23** [comment]
无法复现
![image](https://github.com/MicroCBer/BetterNCM/assets/23134847/4b393319-2e92-4324-b18f-144e0cd2c5b6)
![image](https://github.com/MicroCBer/BetterNCM/assets/23134847/107c3d7b-ea56-4aa6-aaf5-bdb4c231f3fb)
