### ISSUE TITLE
[ Bug ] 新版本1.2.1更新时被WIndowsDefender报毒

### ISSUE THREAD

**Issue by ilexcactus** [MicroCBer/BetterNCM#386]
### Bug 描述

点击更新到新版本后被WD报毒，说是Trojan:Win32/Wacatac.B!ml

### 复现步骤

启动网易云
点击BatterNCM页面
点击现在更新

### 期望行为

不再报毒

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

f49710d

**Comment by MicroCBer** [comment]
修不了 等白名 所有流程全开源 不放心自己看源码吧 可能报毒的部分在避免崩溃的强制更新插件那
