### ISSUE TITLE
2022年9月29日失效 客户端没反应

### ISSUE THREAD

**Issue by ccjk45415** [MicroCBer/BetterNCM#39]
2022年9月29日好像是失效了，插件装了和原版没区别

**Comment by ccjk45415** [comment]
![image](https://user-images.githubusercontent.com/76248184/192940346-5cb05273-5360-4fc9-87ac-336a58c76bed.png)

**Comment by ccjk45415** [comment]
![image](https://user-images.githubusercontent.com/76248184/193291964-529e18a5-2e25-4bb8-b1e6-30fdb6c40524.png)
前几天不行 今天可以了

**Comment by CitronBemly** [comment]
怎么解决的哇
![图片](https://user-images.githubusercontent.com/48025099/195995643-b5cc4394-3d11-4f39-b4bd-c3bcff0167c7.png)
![图片](https://user-images.githubusercontent.com/48025099/195995685-32328e9e-47c0-4b2b-843d-e534131ce5fa.png)




> ![image](https://user-images.githubusercontent.com/76248184/193291964-529e18a5-2e25-4bb8-b1e6-30fdb6c40524.png) 前几天不行 今天可以了
