### ISSUE TITLE
希望能够可以和unblockneteasemusic一同使用

### ISSUE THREAD

**Issue by ClayTT** [MicroCBer/BetterNCM#393]
### 描述你想要的功能

使用unblockneteasemusic之后无网络，127.0.0.1 端口8080  ，希望能够兼容unblockneteasemusic。

### 描述你考虑过的替代方案

或者能够有相同功能的插件？（似乎这样更好）

**Comment by MicroCBer** [comment]
1. BetterNCM 现在并不与 MITM Proxy 冲突，这大概是你自己配置有误，或请到 unblock 仓库发 issue 而不是在这 ( duplicated #8 )
2. 同功能插件已有，但是为了避免造成侵权，没有允许上架
