### ISSUE TITLE
[ Bug ] 电脑进入休眠状态后出现的问题

### ISSUE THREAD

**Issue by setube** [MicroCBer/BetterNCM#394]
### Bug 描述

当我的电脑在无操作一段时间黑屏过后,如果网易云还运行着并且还在播放私人FM或心动模式的话,切歌需要很久很久,然后再去操作电脑亮屏就会发现网易云已经无响应了,右下角托盘里的图标也无法双击唤起

### 复现步骤

1. 电脑无操作之后黑屏
2. 过一段时间网易云会卡死

### 期望行为

希望能够修复这个问题

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

aa07988

### 补充

这里说的切歌很久很久,并不是一开始黑屏之后就会出现,而是黑屏了一段时间之后会出现

**Comment by KingDariaDu** [comment]
我的是挂在后台会假死，过好久才切下一首歌，然后这时候打开网易云发现已经什么都不能点了，假死了

**Comment by setube** [comment]
> 我的是挂在后台会假死，过好久才切下一首歌，然后这时候打开网易云发现已经什么都不能点了，假死了

对,我的就是这样

**Comment by ButterBartel3C3A** [comment]
我也会

**Comment by ty-peng** [comment]
我的也是，电脑设置了一直唤醒，但是锁屏了一段时间再解锁网易云就没响应了，必须杀死进程才能重新进
