### ISSUE TITLE
自定义源点不动

### ISSUE THREAD

**Issue by ybbsb233** [MicroCBer/BetterNCM#396]
### Bug 描述

自定义源按钮点不动

### 复现步骤

点击 右上角出现的云音乐按钮
点击 搜索按钮左边的设置按钮
点击 自定义插件源后无反应

### 期望行为

修复自定义插件源按钮

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

1:2be876b

### 补充

RevivedUnblockInstaller等插件无法安装

**Comment by MicroCBer** [comment]
#380
