### ISSUE TITLE
网易云最新3.0插件无法兼容

### ISSUE THREAD

**Issue by dzqc** [MicroCBer/BetterNCM#397]
### Bug 描述

网易云官网最新的3.0，betterncm installer提示未适配，手动安装了最新的[1.3.0-rc1]版本插件还是提示无法兼容，插件无法使用

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望作者大大更新

### 屏幕截图

<a href="https://imgse.com/i/pCGQNJe"><img src="https://s1.ax1x.com/2023/06/21/pCGQNJe.md.png" alt="pCGQNJe.png" border="0" /></a>
<a href="https://imgse.com/i/pCGQtiD"><img src="https://s1.ax1x.com/2023/06/21/pCGQtiD.png" alt="pCGQtiD.png" border="0" /></a>
<a href="https://imgse.com/i/pCGQvO1"><img src="https://s1.ax1x.com/2023/06/21/pCGQvO1.md.png" alt="pCGQvO1.png" border="0" /></a>

### BetterNCM 版本

1.3.0-rc1

### 网易云音乐版本

3.0.0

### 网易云音乐 Patch 版本

3625547

**Comment by lycstar** [comment]
same issue

**Comment by chaofanx** [comment]
最新测试兼容版本：2.10.10

3.0.0 测试版兼容进度：https://github.com/MicroCBer/BetterNCM/tree/3.0.0-adaption

**Comment by MicroCBer** [comment]
目前插件本体已接近完成适配，但是很多插件尚未适配

你先别急.webp
