### ISSUE TITLE
私人漫游不自动连播

### ISSUE THREAD

**Issue by Linxiux** [MicroCBer/BetterNCM#398]
### Bug 描述

私人漫游当前歌曲放完不能自动连播，会卡到歌单的歌曲去放

### 复现步骤

在私人漫游点击播放拉到最后

### 期望行为

可以连播

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2be876b

### 已安装插件

ActionEnhancement-0.1.7
CrashFix-0.1.3
InfLink-1.0.3
FluentProgressBar-1.0.3
crossfade-lfp-0.1.5

**Comment by lyl328** [comment]
兄弟，你这个解决了吗

**Comment by lywsyxx** [comment]
请问是如何解决的？

**Comment by lywsyxx** [comment]
发现问题所在了，是crossfade-lfp插件导致的这个问题，禁用就能恢复了
