### ISSUE TITLE
[ FR ] 修改安装地址

### ISSUE THREAD

**Issue by eamon2003** [MicroCBer/BetterNCM#399]
### 描述你想要的功能

![image](https://github.com/MicroCBer/BetterNCM/assets/51506762/a2223860-eda9-4681-b7a8-118bd14acad8)
可以修改安装地址吗

**Comment by MicroCBer** [comment]
除了装在网易云目录下你还想往哪装

**Comment by eamon2003** [comment]
> 除了装在网易云目录下你还想往哪装

你看我这个的路径在c盘 我网易云放在d盘某个文件夹里

**Comment by MicroCBer** [comment]
已经成功探测到网易云安装路径了啊 使用上有问题吗

**Comment by eamon2003** [comment]
> 已经成功探测到网易云安装路径了啊 使用上有问题吗

使用上没有问题 所以我只是说能否修改安装地址 毕竟它放在c盘一级目录显得很突兀

**Comment by yangnuozhen** [comment]
> > 已经成功探测到网易云安装路径了啊 使用上有问题吗
> 
> 使用上没有问题 所以我只是说能否修改安装地址 毕竟它放在c盘一级目录显得很突兀

猜你想找：[使用环境变量更改插件文件存放位置](https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#EUuudouWaog8iMx8WAGcBOC0n1b)

**Comment by eamon2003** [comment]
> > > 已经成功探测到网易云安装路径了啊 使用上有问题吗
> > 
> > 
> > 使用上没有问题 所以我只是说能否修改安装地址 毕竟它放在c盘一级目录显得很突兀
> 
> 猜你想找：[使用环境变量更改插件文件存放位置](https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#EUuudouWaog8iMx8WAGcBOC0n1b)

感谢感谢
