### ISSUE TITLE
0.2.2 崩溃

### ISSUE THREAD

**Issue by alex3236** [MicroCBer/BetterNCM#40]
更新后网易云音乐崩溃

**Comment by IASUI** [comment]
+1

**Comment by MicroCBer** [comment]
网易云版本？

**Comment by MicroCBer** [comment]
https://github.com/MicroCBer/BetterNCM/commit/5a3a6e7df453dabc87d2900883cb56d5c091c0c4

很迷，按理说这个定义应该改才对，但是改了好像挺多人遇到崩溃的

**Comment by IASUI** [comment]
> 网易云版本？

@MicroCBer  2.10.3 Build:200198 Patch:1:dfc4e8c

**Comment by MicroCBer** [comment]
[BetterNCMII.zip](https://github.com/MicroCBer/BetterNCM/files/9692894/BetterNCMII.zip)
试下这个没改过定义的版本

**Comment by Marce1ek** [comment]
> [BetterNCMII.zip](https://github.com/MicroCBer/BetterNCM/files/9692894/BetterNCMII.zip) 试下这个没改过定义的版本

这个也崩溃

**Comment by MicroCBer** [comment]
测试出来了……是startup script那边的问题 马上去修一下

**Comment by JonhhyD** [comment]
刚刚找到这个插件就崩溃不能使用，很巧合哈哈

**Comment by MicroCBer** [comment]
0.2.3 已修复
