### ISSUE TITLE
[ Bug ] 插件商店加载失败

### ISSUE THREAD

**Issue by Niyoubingbing** [MicroCBer/BetterNCM#400]
### Bug 描述

插件商店显示加载失败，没有开代理

### 复现步骤

打开网易云就一直这样

### 期望行为

希望可以访问插件商店

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/89000522/7eb66ed0-00e4-444f-832b-44d9b7d6c37a)

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

a392e4e

**Comment by CosmicRide** [comment]
me too

**Comment by xiqwqxi** [comment]
我尝试重装插件，但依然无法访问
![image](https://github.com/MicroCBer/BetterNCM/assets/94767651/cc0fd38f-8272-4a86-a7bb-5e6add968315)

**Comment by Hleison** [comment]
感觉是gitee插件仓库被人举报没了

**Comment by Niyoubingbing** [comment]
> 

我选上面的GitHub一样不行，开了代理也不行

**Comment by yangnuozhen** [comment]
![40031452b8defab7ae8a2a7b94dc0fe5](https://github.com/MicroCBer/BetterNCM/assets/56541171/cda5ed24-90f1-4291-918a-766848ce0cc4)

**Comment by SakuraPuare** [comment]
Gitee仓库无了，可以试试切换Github源

如果还是不能，可以按 F12 看看自己请求的报错是什么
![image](https://github.com/MicroCBer/BetterNCM/assets/52142762/da419187-c42c-49a1-a3e9-8c20082bc9b8)

**Comment by Niyoubingbing** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/89000522/db895249-ba85-4cf4-89d8-539ae75830ad)

**Comment by yangnuozhen** [comment]
> ![image](https://user-images.githubusercontent.com/89000522/250268949-db895249-ba85-4cf4-89d8-539ae75830ad.png)

切换自定义源，填入`https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/`

> 第三方注意

**Comment by eamon2003** [comment]
> > ![image](https://user-images.githubusercontent.com/89000522/250268949-db895249-ba85-4cf4-89d8-539ae75830ad.png)
> 
> 切换自定义源，填入`https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/`
> 
> > 第三方注意

刚把地址改了就出现这个问题了 又看到你了 谢谢哥

**Comment by JiuShua** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/96060971/ebb647f4-97f8-418e-9a3f-6612257a355e)

**Comment by yangnuozhen** [comment]
**喜报**：现有橘子新插件源，使用方法：

![image](https://github.com/MicroCBer/BetterNCM/assets/56541171/15946534-0ce7-49c4-88cb-42c707661775)
![image](https://github.com/MicroCBer/BetterNCM/assets/56541171/c68281ed-2cdf-4261-87b5-13f5ee38a93c)

**填入 `
https://gitee.com/microblock/volartary/raw/master/
`**

![image](https://github.com/MicroCBer/BetterNCM/assets/56541171/8dc7342d-899a-406a-bd23-735eb883fdd7)

**Comment by whzdl** [comment]
> https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/

感谢大佬

**Comment by R6s-Jackal** [comment]
一样，希望作者可以解决

**Comment by yangnuozhen** [comment]
> 一样，希望作者可以解决

看看上面的replies吧

**Comment by qr-kk** [comment]
家人们，无法自定义咋搞，点击自定义没反应，
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/d2aa8c94-d1e1-4d26-b6e4-0c3ab85794bb)
上面这个页面因为自定义点不出来插件商店依然加载失败
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/74f96a72-a731-4ac5-bf08-14fad818afdc)

**Comment by xfrqh** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/73733485/135194df-5832-4f6a-a1e1-18508e8c8ada)

你这边似乎出现了异常”版本不兼容“，试试安装 网易云音乐 2.10.10。

[网易云音乐 2.10.10](https://www.onlinedown.net/soft/110772.htm)

**Comment by qr-kk** [comment]
更新到2.10.10虽然不显示兼容问题但是除了不显示兼容以外其他的情况都没变化
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/ec26fb87-2487-46ca-8e60-4223b674c60b)
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/e6e38d28-3fc8-4b14-972e-ac150547b040)

**Comment by xfrqh** [comment]
> 
试试打开 C:/betterncm/config.json 
将其中的网址替换为可以使用的源的地址（如 https://gitee.com/microblock/volartary/raw/master/ ）

**Comment by xfrqh** [comment]
> 更新到2.10.10虽然不显示兼容问题但是除了不显示兼容以外其他的情况都没变化 ![image](https://user-images.githubusercontent.com/138861317/251709157-ec26fb87-2487-46ca-8e60-4223b674c60b.png) ![image](https://user-images.githubusercontent.com/138861317/251709205-e6e38d28-3fc8-4b14-972e-ac150547b040.png)

试试打开 C:/betterncm/config.json
将其中的网址替换为可以使用的源的地址（如 https://gitee.com/microblock/volartary/raw/master/ ）

**Comment by qr-kk** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/a8a8aa20-6c85-4e33-b5fc-f900ecdbfdcb)
改过后还是这样
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/eb662b77-337e-4e74-8797-ee081f2cb8af)

**Comment by xfrqh** [comment]
有一个必杀技（在我这边成功解决问题）：重装软件

#### 建议操作

1. 卸载网易音乐
2. 删除 C:\Program Files (x86)\Netease\CloudMusic\ 下的所有文件
3. 备份音乐文件（如果需要）（将文件 剪切 到别处）
4. 安装网易云音乐，安装 BetterNCM

**Comment by xfrqh** [comment]
> ![image](https://user-images.githubusercontent.com/138861317/251712375-a8a8aa20-6c85-4e33-b5fc-f900ecdbfdcb.png) 改过后还是这样 ![image](https://user-images.githubusercontent.com/138861317/251712523-eb662b77-337e-4e74-8797-ee081f2cb8af.png)


#### 建议操作

1. 卸载网易音乐
2. 删除 C:\Program Files (x86)\Netease\CloudMusic\ 下的所有文件
3. 备份音乐文件（如果需要）（将文件 剪切 到别处）
4. 安装网易云音乐，安装 BetterNCM

**Comment by qr-kk** [comment]
我去试试等我好消息

**Comment by qr-kk** [comment]
必杀技也败了
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/b6fde71c-6859-4896-9995-4c2422ccc2fa)
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/a40aef59-5649-44ef-9a93-5893788e703d)
我把那个文件夹里面的全部删了但是重新下载后依然是依然甚至我还怕没选保留客户数据我还这样操作了两次，但是还是失败了

**Comment by xfrqh** [comment]
> 必杀技也败了
> ![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/b6fde71c-6859-4896-9995-4c2422ccc2fa)
> ![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/a40aef59-5649-44ef-9a93-5893788e703d)
> 我把那个文件夹里面的全部删了但是重新下载后依然是依然甚至我还怕没选保留客户数据我还这样操作了两次，但是还是失败了

试试这些？
卸载，删除。用“电脑管家”类软件（如，火绒）清理垃圾，重启，安装。

**Comment by yangnuozhen** [comment]
> 必杀技也败了 ![image](https://user-images.githubusercontent.com/138861317/251724082-b6fde71c-6859-4896-9995-4c2422ccc2fa.png) ![image](https://user-images.githubusercontent.com/138861317/251724133-a40aef59-5649-44ef-9a93-5893788e703d.png) 我把那个文件夹里面的全部删了但是重新下载后依然是依然甚至我还怕没选保留客户数据我还这样操作了两次，但是还是失败了

等更新吧

**Comment by qr-kk** [comment]
> > 必杀技也败了 我把那个文件夹里面的全部删了但是重新下载后依然是依然甚至我还怕没选保留客户数据我还这样操作了两次，但是还是失败了 ![image](https://user-images.githubusercontent.com/138861317/251724082-b6fde71c-6859-4896-9995-4c2422ccc2fa.png) ![image](https://user-images.githubusercontent.com/138861317/251724133-a40aef59-5649-44ef-9a93-5893788e703d.png)
> 
> 试试这些？ 卸载，删除。用"电脑管家"类软件（如，火绒）清理垃圾，重启，安装。

我尝试过均已失败告终，插件用习惯了，现在用正常的太难受了，简直折磨

**Comment by qr-kk** [comment]
唉，还是老老实实等更新吧

**Comment by yangnuozhen** [comment]
~~看来只能暂时祭出我之前做的烂活了~~
![image](https://github.com/MicroCBer/BetterNCM/assets/56541171/9d0c3666-66fd-44ba-89a4-57ee195aae9d)

按照使用说明安装即可

[RePluginMarket (附使用说明).zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)

**Comment by qr-kk** [comment]
> ~看来只能暂时祭出我之前做的烂活了~ ![image](https://user-images.githubusercontent.com/56541171/251732623-9d0c3666-66fd-44ba-89a4-57ee195aae9d.png)
> 
> 按照使用说明安装即可
> 
> [RePluginMarket （附使用说明）.zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)

而你我的朋友，不要说他是烂活，能暂时解决我没主题用的问题的都是好活
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/af047df7-304b-4879-aa3f-eb12796f9ba3)
gan感谢你让我暂时有个可以用的主题，这下应该可以等到更新啦，太感谢啦

**Comment by zsm839853915** [comment]
> ~看來只能暫時祭出我之前做的爛活了~ ![image](https://user-images.githubusercontent.com/56541171/251732623-9d0c3666-66fd-44ba-89a4-57ee195aae9d.png)
> 
> 按照使用說明安裝即可
> 
> [RePluginMarket （附使用說明）.zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)

朋友，你是真真正的hero

**Comment by yangnuozhen** [comment]
哦对了，如果点不开自定义源，可以试试点开插件商店，键盘打`上上下下左右左右BABA` （使用方向键和B、A键）

（这是橘子提供的方法 不过我好像触发不了

**Comment by qr-kk** [comment]
虽然这个我也没触发，不过我今天早上起来发现我的自定义源可以打开了

**Comment by Qykyyds021228** [comment]
> > ~看来只能暂时祭出我之前做的烂活了~ ![image](https://user-images.githubusercontent.com/56541171/251732623-9d0c3666-66fd-44ba-89a4-57ee195aae9d.png)
> > 按照使用说明安装即可
> > [RePluginMarket （附使用说明）.zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)
> 
> 而你我的朋友，不要说他是烂活，能暂时解决我没主题用的问题的都是好活 ![image](https://user-images.githubusercontent.com/138861317/251746910-af047df7-304b-4879-aa3f-eb12796f9ba3.png) gan感谢你让我暂时有个可以用的主题，这下应该可以等到更新啦，太感谢啦

我的朋友你是真正的英雄

**Comment by CShisan** [comment]
> > ~看来只能暂时祭出我之前做的烂活了~ ![image](https://user-images.githubusercontent.com/56541171/251732623-9d0c3666-66fd-44ba-89a4-57ee195aae9d.png)
> > 按照使用说明安装即可
> > [RePluginMarket （附使用说明）.zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)
> 
> 而你我的朋友，不要说他是烂活，能暂时解决我没主题用的问题的都是好活 ![image](https://user-images.githubusercontent.com/138861317/251746910-af047df7-304b-4879-aa3f-eb12796f9ba3.png) gan感谢你让我暂时有个可以用的主题，这下应该可以等到更新啦，太感谢啦

只要去隔壁的RevivedUnblockInstaller把里面的插件丢到插件文件夹   你就会发现自定义源可以用了  然后再把楼上老哥的橘子源填上去就可以愉快的听歌啦
![image](https://github.com/MicroCBer/BetterNCM/assets/55305718/51d70c90-679a-4555-b63d-24e00d7434e1)

**Comment by yangnuozhen** [comment]
> > > ~看来只能暂时祭出我之前做的烂活了~ ![image](https://user-images.githubusercontent.com/56541171/251732623-9d0c3666-66fd-44ba-89a4-57ee195aae9d.png)
> > > 按照使用说明安装即可
> > > [RePluginMarket （附使用说明）.zip](https://github.com/MicroCBer/BetterNCM/files/11981628/RePluginMarket.zip)
> > 
> > 
> > 而你我的朋友，不要说他是烂活，能暂时解决我没主题用的问题的都是好活 ![image](https://user-images.githubusercontent.com/138861317/251746910-af047df7-304b-4879-aa3f-eb12796f9ba3.png) gan感谢你让我暂时有个可以用的主题，这下应该可以等到更新啦，太感谢啦
> 
> 只要去隔壁的RevivedUnblockInstaller把里面的`RevivedUnblockNeteaseMusic.plugin`插件丢到插件文件夹 然后重载插件 你就会发现自定义源可以用了 然后再把楼上老哥的橘子源填上去就可以愉快的听歌啦 ![image](https://user-images.githubusercontent.com/55305718/253598822-51d70c90-679a-4555-b63d-24e00d7434e1.png)

没上上下下左右左右BABA好用（

**Comment by HoneyBlock** [comment]
> 哦对了，如果点不开自定义源，可以试试点开插件商店，键盘打 （使用方向键和B、A键）`上上下下左右左右BABA`
> 
> （这是橘子提供的方法 不过我好像触发不了
> 
> 以下是写在群公告的：
> 
> > 暂时的修复方法：点击设置按钮，点击自定义源，填入：自定义源 https://gitee.com/microblock/volartary/raw/master/ 点不开自定义源可以按以下按键序列：上上下下左右巴巴

哦朋友，谢谢你

**Comment by tangturtle** [comment]
自定义源 https://gitee.com/microblock/volartary/raw/master/
好像失效了

**Comment by QZZ1793** [comment]
> 哦对了，如果点不开自定义源，可以试试点开插件商店，键盘打`上上下下左右左右BABA` （使用方向键和B、A键）
> 
> （这是橘子提供的方法 不过我好像触发不了
> 
> 以下是写在群公告的：
> 
> > 暂时的修复方法：点击设置按钮，点击自定义源，填入：自定义源 https://gitee.com/microblock/volartary/raw/master/
> > 点不开自定义源可以按以下按键序列：上上下下左右左右baba

好使 专门注册了个账号表达感谢ヾ(^▽^*)))

**Comment by yangnuozhen** [comment]
> 自定义源 https://gitee.com/microblock/volartary/raw/master/ 好像失效了

我这里完全正常

**Comment by xushet** [comment]
插眼

**Comment by yangnuozhen** [comment]
> 插眼

去更新最新版
