### ISSUE TITLE
BetterNCM插件出现403

### ISSUE THREAD

**Issue by wwejfguf** [MicroCBer/BetterNCM#402]
### Bug 描述

BetterNCM主界面PluginMarket界面出现
https://gitee.com/microblock/BetterNCMPluginsMarketData/raw/master/plugins.json  failed:403 Forbidden
点击Github（UserContent）/Github（Raw）都会出现Failed to fetch

### 复现步骤

**例**:
1. 打开网易云音乐（以安装插件的情况下）
2. 点击'BetterNCM小图标'
3. 再点击PluginMarket
4. 看到错误

### 期望行为

恢复

### 屏幕截图

![屏幕截图2023-07-02102409](https://github.com/MicroCBer/BetterNCM/assets/107800903/e7a324fc-c0a6-4a3f-a968-f90487b70b38)
![屏幕截图 2023-07-02 103510](https://github.com/MicroCBer/BetterNCM/assets/107800903/844fb561-2b32-4e95-9364-5a1101ea582a)

### BetterNCM 版本

1.0.5

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

1:a392e4e

**Comment by MoeBai** [comment]
感觉好像是仓库被封了.

**Comment by wwejfguf** [comment]
> 感觉好像是仓库被封了.

看到了，不知道为什么，我的插件源不能自定义

**Comment by whzdl** [comment]
> 
还有别的插件源吗

**Comment by ymy139** [comment]
gitee的仓库好像无了

**Comment by ckp-0217** [comment]
> > 感觉好像是仓库被封了.
> 
> 看到了，不知道为什么，我的插件源不能自定义

打开插件文件夹 有个config.json 替换链接
https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/
再进去网易云就可以自定义
自定义改成
https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/

**Comment by wwejfguf** [comment]
> > > 感觉好像是仓库被封了.
> > 
> > 
> > 看到了，不知道为什么，我的插件源不能自定义
> 
> 打开插件文件夹 有个config.json 替换链接 https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/ 再进去网易云就可以自定义 自定义改成 https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/

谢谢，我试了一下确实可以了

**Comment by SleeqzZ** [comment]
> > > 感觉好像是仓库被封了.
> > 
> > 
> > 看到了，不知道为什么，我的插件源不能自定义
> 
> 打开插件文件夹 有个config.json 替换链接 https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/ 再进去网易云就可以自定义 自定义改成 https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/

淦，我这找不到config.json怎么办啊
