### ISSUE TITLE
[ Bug ] 插件市场一直转圈

### ISSUE THREAD

**Issue by 4O4NtFd** [MicroCBer/BetterNCM#404]
### Bug 描述

插件市场一直转圈
![image](https://github.com/MicroCBer/BetterNCM/assets/49442853/85c9f9dc-828a-4b77-a036-00a790789e82)

### 复现步骤

安装后点击插件图标就会一直转圈

### 期望行为

能正常使用

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/49442853/f8225587-3e27-4500-844b-3ee6fa2f58af)

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2e7873f

### 补充

前两天换电脑了，今天第一次在新电脑上安装。
推测是与gitee仓库被封有关。查看别的issue提到了修改插件目录下的config.json，但是查看文档没看到应该怎么配置。而且插件的页面也没有设置的图标
![我的config.json](https://github.com/MicroCBer/BetterNCM/assets/49442853/6b65daa8-fc47-4c0a-bfd0-8488c41765c9)

**Comment by wwejfguf** [comment]
打开插件文件夹 有个config.json 替换链接
https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/
再进去网易云就可以自定义
自定义改成
https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/
你试试这个有没有效果

**Comment by 4O4NtFd** [comment]
插件文件夹下的config.json只有这么一句话
{"cc.microblock.betterncm.cpp_side_inject_feature_disabled":"false"}
我应该插在哪
![image](https://github.com/MicroCBer/BetterNCM/assets/49442853/2f77f6f2-502c-447c-ae43-ce9249468b82)

**Comment by wwejfguf** [comment]
> 插件文件夹下的config.json只有这么一句话 {“cc.microblock.betterncm.cpp_side_inject_feature_disabled”：“false”} 我应该插在哪 ![image](https://user-images.githubusercontent.com/49442853/251346084-2f77f6f2-502c-447c-ae43-ce9249468b82.png)

你用word试试，我用word打开里面是
{"cc.microblock.betterncm.cpp_side_inject_feature_disabled":"false","cc.microblock.pluginmarket.source":"https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/"}

**Comment by wwejfguf** [comment]
> 插件文件夹下的config.json只有这么一句话 {“cc.microblock.betterncm.cpp_side_inject_feature_disabled”：“false”} 我应该插在哪 ![image](https://user-images.githubusercontent.com/49442853/251346084-2f77f6f2-502c-447c-ae43-ce9249468b82.png)

我知道了，你复制我那一段话试试

**Comment by 4O4NtFd** [comment]
好了，谢谢

**Comment by yangnuozhen** [comment]
请参照此[方法将插件源改为橘子的官方信源](https://github.com/MicroCBer/BetterNCM/issues/400#issuecomment-1616433602)，因为我临时Fork的插件源不会提供更新（
