### ISSUE TITLE
[ Bug ] 版本不兼容

### ISSUE THREAD

**Issue by fon11731** [MicroCBer/BetterNCM#406]
### Bug 描述

打开后发现版本不兼容

### 复现步骤

无，直接出现

### 期望行为

无

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

781a990

**Comment by qr-kk** [comment]
一样显示版本不兼容，而且自定义选项无法打开
<img width="767" alt="微信图片_20230707163348" src="https://github.com/MicroCBer/BetterNCM/assets/138861317/ce72417a-bb9f-44e2-ae3c-b5e19aae7a73">
![image](https://github.com/MicroCBer/BetterNCM/assets/138861317/b8e7da58-84d7-4c6b-b93c-736f321230c0)
自定义可以点击，但是点击后没反应，重载重装均无法解决

**Comment by iAmP1us** [comment]
好像还没更新，现在网易云到了2.10.11，BetterNCM只支持到2.10.10

**Comment by raging-flames** [comment]
> 好像还没更新，现在网易云到了2.10.11，BetterNCM只支持到2.10.10

并不是吧，我网易云2.10.8，也这样

**Comment by qr-kk** [comment]
先等一下更新吧要是更新完还不行就把网易云和插件的所有数据都删了重新下一遍

**Comment by iAmP1us** [comment]
我退回到2.10.10已经解决了

**Comment by qr-kk** [comment]
我的退回也没用，不过用了个别人的东西暂时还可以用，看看更新后能恢复不能吧

**Comment by Wdepth** [comment]
目前退回到2.10.10 版本显示正常但是插件还是没法下载

**Comment by iAmP1us** [comment]
- 版本不兼容的，我建议你卸载了之后下载2.10.10【链接：https://pan.baidu.com/s/16i9Dcn8LQmJLvrWTRUsp5g?pwd=6657 

提取码：6657 】
安装好之后，在[关于网易云音乐]里找到有新版本时提醒我。因为我用[BetterUniverse-Installer]=(https://github.com/MicroCBer/BetterUniverse-Installer)工具一键部署的时候他就给我半途更新，这样是肯定失败的。然后就是杀毒软件一定要关，不然会把部署程序直接删了，也不能成功部署。

- 版本正常兼容的，插件无法下载的很好解决。网易云设置-工具-自定义代理，服务器填写本地地址127.0.0.1，端口填写你clash或者其他vpn的代理端口。确定，然后重启。插件市场应该就可以正常使用了。之后更改回不使用代理。

- 以上是我的一点经验，希望对各位有帮助。（不一定有用

**Comment by zxbforever** [comment]
> 

6657 UPUP!

**Comment by iAmP1us** [comment]
> 

好好好

**Comment by zhuzixuan2019241** [comment]
#400

**Comment by FinaFina233** [comment]
用Github源，或者自定义https://gitee.com/yangnuozhen/r-better-ncm-packed-plugins/raw/master/
