### ISSUE TITLE
[ Bug ] 安装不上

### ISSUE THREAD

**Issue by beitianstu** [MicroCBer/BetterNCM#409]
### Bug 描述

把dll文件放到网易云文件夹没有用，安装器也只能删除

### 复现步骤

1.把dll文件复制到网易云目录
2.打开网易云

### 期望行为

希望可以告诉我为什么以及该怎么修复

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/112758008/a039b63d-3f98-4a9c-8423-cafe1d506494)
![image](https://github.com/MicroCBer/BetterNCM/assets/112758008/059740ba-d689-4f95-95ef-95e8d58b5fbe)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2be876b

### 补充

我重启了好多次了

**Comment by beitianstu** [comment]
更新到最新版本安装器好了

**Comment by tangturtle** [comment]
最新版本安装器会闪退

https://github.com/MicroCBer/BetterNCM/assets/88638584/aa236cbb-a9c2-46b3-8147-10cfb82d99d2
