### ISSUE TITLE
点歌机点歌问题

### ISSUE THREAD

**Issue by yuki-one** [MicroCBer/BetterNCM#41]
点歌机点歌的时候，如果网易云搜索不到结果的话就会卡住接下来点的歌都不能正常继续搜索点上，解决方法是随便搜索一个能播放的才会把点歌积压的歌继续点上
例：
![image](https://user-images.githubusercontent.com/76642580/193464940-f41c8c1a-6666-4ac7-8045-513dac910dcf.png)

**Comment by MicroCBer** [comment]
fixed in `0.1.2`
