### ISSUE TITLE
客户端首页样式会导致消息面板无法打开

### ISSUE THREAD

**Issue by 21064321** [MicroCBer/BetterNCM#410]
### Bug 描述

![image](https://github.com/MicroCBer/BetterNCM/assets/88960203/d0e831bb-5b9d-4a57-be50-d85d6a6557c3)
这是没开首页样式的消息面板
![image](https://github.com/MicroCBer/BetterNCM/assets/88960203/89f52fed-22c7-40d2-ac64-8fc1f67397a6)
这是开了首页样式的消息面板

### 复现步骤

打开首页样式就会看不见消息面板

### 期望行为

把消息面板的图层往上调

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.11:201538

### 网易云音乐 Patch 版本

1:781a990

**Comment by MicroCBer** [comment]
请在对应插件下发 Issue 而不是在本体下
