### ISSUE TITLE
[ Bug ] 插件商店一直在旋转，无法更改源

### ISSUE THREAD

**Issue by jerryyang-git** [MicroCBer/BetterNCM#411]
### Bug 描述

根据文档中`由于Gitee仓库限制，无法公开，导致插件商店无法使用，请自行更改代理设置使用GitHub源！！！`
我想设置为 github 源或自定义，但是我的`PluginMarket`插件一直在旋转，等待5分钟一直旋转

### 复现步骤

打开插件商店（PluginMarket），插件一直加载

### 期望行为

PluginMarket 能正常加载更新插件

### 屏幕截图

具体加载表现形式如下
![image](https://github.com/MicroCBer/BetterNCM/assets/60727068/5108d3ac-2841-444b-8fb4-628327f3dc17)
并没有出现 #400 中更换插件源的界面
![image](https://github.com/MicroCBer/BetterNCM/assets/60727068/7ddc3379-eb94-42ea-b4d2-9eb7ff693ee2)
根据其他Issue #404 我尝试寻找`BetterNCM`的`config.json`更改源，但发现文件配置内容跟 #404 的一样
![image](https://github.com/MicroCBer/BetterNCM/assets/60727068/b5bb312b-c73e-4ef2-85dc-4175295977a4)

### BetterNCM 版本

1.2.1

### 网易云音乐版本

当前版本2.10.11(Build:201538)(Patch1:781a990)

### 网易云音乐 Patch 版本

781a990

### 补充

系统：windows11
已测试不挂任何代理软件和挂代理软件，网易云设置均为默认

**Comment by fon11731** [comment]
是的，我也遇到了

**Comment by GuaiJieYo** [comment]
自定义源用 https://ghproxy.net/https://raw.githubusercontent.com/BetterNCM/BetterNCM-Packed-Plugins/master/ 即可  
(这是官方github源 只是加了个代理)

**Comment by jerryyang-git** [comment]
> 自定义源用 https://ghproxy.net/https://raw.githubusercontent.com/BetterNCM/BetterNCM-Packed-Plugins/master/ 即可 (这是官方github源 只是加了个代理)

我无法设置自定义源，一直在加载，也没有弹出自定义选项

![image](https://github.com/MicroCBer/BetterNCM/assets/60727068/4bd07226-2a6a-4577-b15b-25763b7f1d7c)
