### ISSUE TITLE
[ Bug ] 1.2.2无法正常使用

### ISSUE THREAD

**Issue by tangturtle** [MicroCBer/BetterNCM#412]
### Bug 描述

刚刚更新的1.2.2好像无法正常使用，右上角插件管理打不开，但插件可以用。

### 复现步骤

正常通过1.2.1插件管理更新，发现用不了又下载.dll文件手动更新了一次。

### 期望行为

正常打开插件管理

### 屏幕截图

https://github.com/MicroCBer/BetterNCM/assets/88638584/63cbd26f-eefe-467a-b0e7-ce12cb861885

### BetterNCM 版本

1.2.2

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2e7873f

**Comment by Mr-licz** [comment]
遇到相同问题。
网易云音乐版本：2.10.11
BetterNCM版本：1.2.2

**Comment by windy1021** [comment]
应该是不兼容2.10版本吧，最近几个版本都在给3.0做适配，老版本被适配下去了（悲

**Comment by hans1980775481** [comment]
我也遇到这个问题了
网易云音乐版本：2.10.11
BetterNCM版本：1.2.2
Patch:1:781a990

**Comment by yangnuozhen** [comment]
> 应该是不兼容2.10版本吧，最近几个版本都在给3.0做适配，老版本被适配下去了（悲

不是 是橘子发行的问题

**Comment by yangnuozhen** [comment]
目前的解决方案：下载[1.2.1发行包](https://github.com/MicroCBer/BetterNCM/releases/download/1.2.1/BetterNCMII.dll)，[参照文档手动安装](https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme#part-OMyvdeqHjoRCLXx4ZmHczOPUnge)

**Comment by yangnuozhen** [comment]
[MicroCBer: fixed](https://github.com/MicroCBer/BetterNCM/issues/413#issuecomment-1649231656)

直接在BNCM菜单更新，Github上目前还没发Release。

**Comment by 2270180144** [comment]
已经发布1.2.3了，修复了问题

**Comment by MicroCBer** [comment]
> > 应该是不兼容2.10版本吧，最近几个版本都在给3.0做适配，老版本被适配下去了（悲
> 
> 不是 是橘子发行的问题

确实是给3.0做适配的东西重新兼容2.10就出问题了
