### ISSUE TITLE
手动重新更新安装最新版后，打不开betterncm界面

### ISSUE THREAD

**Issue by hans1980775481** [MicroCBer/BetterNCM#413]
### Bug 描述

![VeryCapture_20230725103849](https://github.com/MicroCBer/BetterNCM/assets/29484912/8f5ba64c-395f-4b74-9e61-b732369de153)

网易云版本：2.10.11
BetterNCM版本：1.2.2

### 复现步骤

之前有安装过BetterNCM，但是后于gitee源失效了打开BetterNCM界面 没啥内容， 就想着更新一下最新版本，手动更新完之后发现BetterNCM界面都打不开了；但之前下载的插件效果还在。

### 期望行为

希望手动更新之后还是能和之前一样可以打开BetterNCM界面

### BetterNCM 版本

1.2.2

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

Patch:1:781a990

**Comment by tiancaigaowan** [comment]
同样遇到该问题

**Comment by yangnuozhen** [comment]
duplicated #412

**Comment by wominIII** [comment]
同样遇到该问题

**Comment by wsxyjy** [comment]
同样遇到该问题，插件正常生效，无法打开BetterNCM界面

**Comment by MicroCBer** [comment]
fixed

**Comment by yangnuozhen** [comment]
> fixed

#412 没关 以及Github没发Release包（
