### ISSUE TITLE
[ Plugin Bug ] 插件市场（PliginMarket）加载失败

### ISSUE THREAD

**Issue by Singularia39** [MicroCBer/BetterNCM#414]
### Bug 描述

进入插件市场时显示加载失败，无法获取新的插件

### 复现步骤

进入插件市场时显示加载失败（插件源选择Gitee）
弹出设置与重试按钮，重试仍然失败
在设置中更换插件源至Github（Raw）仍显示加载失败，重试仍然失败
更换插件源至Github（UserContent）同样显示加载失败，重试仍然失败
插件源无法切换至自定义

### 期望行为

修复PluginMarket，使其能够正常加载

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/132178246/eb9042aa-aff1-444f-9c12-5c8cb8c8a825)
![image](https://github.com/MicroCBer/BetterNCM/assets/132178246/fb92b41f-28bf-434d-8386-ae01cb3c23a1)
![image](https://github.com/MicroCBer/BetterNCM/assets/132178246/46509af7-c923-4e23-8
![屏幕截图 2023-07-27 115251](https://github.com/MicroCBer/BetterNCM/assets/132178246/b3d1607e-15c7-4a6a-8e0f-f0b2449d2972)
51e-8c5843cf6f95)

### BetterNCM 版本

1.2.3

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

781a990

### 已安装插件

- BGEnhanced
- BGEnhanced Extra
- LibFrontendPlay
- 明/暗主题切换器
- LyricBar
- MikuPlugin
- MoTheme
- RefinedNowPlaying
- StylesheetLoader
- TinyNCM
- CrossFade LFP
- ListScrollFix
- RevivedSource

**Comment by MicroCBer** [comment]
请重启
