### ISSUE TITLE
网易云3.0.0安装后无法启动

### ISSUE THREAD

**Issue by Lukoning** [MicroCBer/BetterNCM#415]
### Bug 描述

开始是用BetterNCM Installer安装的，后来自行在GitHub上下载1.3.0-RC3和1.3.0-RC1手动安装，都无法启动网易云。卸载BetterNCM后正常启动。
双击cloudmusic.exe后任务管理器没看到进程，应该是闪退了
不知道跟虚拟机有没有关系（因为我是在Windows 沙盒里安装的）

### 复现步骤

1.安装网易云音乐3.0.0
2.安装BetterNCM
3.尝试启动网易云

### 期望行为

.

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/92252063/0b7022b2-c589-4bab-a3a2-ad097a2eb982)
Installer把网易云版本识别成了3.0.1

### BetterNCM 版本

1.3.0-RC3 / 1.3.0-RC1

### 网易云音乐版本

3.0.0.Beta (64位) (Build: 201589)

### 网易云音乐 Patch 版本

1cc15de

**Comment by MicroCBer** [comment]
https://microblock.lanzouy.com/iMwxT13j0kze

尝试使用此文件覆盖安装

**Comment by Lukoning** [comment]
> https://microblock.lanzouy.com/iMwxT13j0kze
> 
> 尝试使用此文件覆盖安装

按照压缩包里的使用方法覆盖安装，还是无法启动。
移除msimg32.dll后可以正常启动，但变成了这样：
![image](https://github.com/MicroCBer/BetterNCM/assets/92252063/cb1f2941-355d-478b-9f68-ca36c9672ee4.png)
![image](https://github.com/MicroCBer/BetterNCM/assets/92252063/4304cce1-64c0-442f-87d9-4cabbd930fa5.png)

**Comment by FinaFina233** [comment]
![image](https://github.com/MicroCBer/BetterNCM/assets/52440333/d3db163c-b18a-49d3-9a76-0686f2d12146)
![image](https://github.com/MicroCBer/BetterNCM/assets/52440333/42709b6c-d043-484b-a438-5abd1af42f57)
我这没问题

**Comment by Lukoning** [comment]
补充：刚刚试了下，32位版本可以启动（但没找到BetterNCM的入口）
![image](https://github.com/MicroCBer/BetterNCM/assets/92252063/f2fe85e0-54d3-40c7-bdee-2ee78394396b)

**Comment by FinaFina233** [comment]
> 补充：刚刚试了下，32位版本可以启动（但没找到BetterNCM的入口）
> ![image](https://github.com/MicroCBer/BetterNCM/assets/92252063/f2fe85e0-54d3-40c7-bdee-2ee78394396b)
> 

尝试手动安装64位的msvc

**Comment by Lukoning** [comment]
> > 补充：刚刚试了下，32位版本可以启动（但没找到BetterNCM的入口）
> > ![image](https://user-images.githubusercontent.com/92252063/257497804-f2fe85e0-54d3-40c7-bdee-2ee78394396b.png)
> 
> 尝试手动安装64位的msvc

> 手动安装64位的msvc

谢谢，现在可以启动了。
