### ISSUE TITLE
0.2.3无法加载插件，只有图标

### ISSUE THREAD

**Issue by LuxQuet** [MicroCBer/BetterNCM#42]
![图片](https://user-images.githubusercontent.com/50163161/193547520-d0c0fa48-61e1-4118-8201-23b5498a1518.png)

**Comment by MicroCBer** [comment]
按F12 切到Console 看看是否有报错

**Comment by LuxQuet** [comment]
![图片](https://user-images.githubusercontent.com/50163161/193555420-ccf17165-b16c-4385-8917-24decc6b8f36.png)

**Comment by MicroCBer** [comment]
重新开下看看

**Comment by LuxQuet** [comment]
![图片](https://user-images.githubusercontent.com/50163161/193557412-1faf371f-a8e2-43b3-aa40-a50b004f0363.png)

**Comment by MicroCBer** [comment]
重启网易云之后依然无法加载吗

**Comment by LuxQuet** [comment]
是的，但老版本能加载，新版本不行

**Comment by MicroCBer** [comment]
看下network一栏，还有用户文件夹下betterncm目录

**Comment by LuxQuet** [comment]
![图片](https://user-images.githubusercontent.com/50163161/193558450-70742aa9-60d3-45e7-ad4d-d2a74dee42ef.png)
![图片](https://user-images.githubusercontent.com/50163161/193558523-fcc28bee-dd2b-4e99-8b8f-cf4dd17e43af.png)

**Comment by LuxQuet** [comment]
betterncm目录没问题

**Comment by MicroCBer** [comment]
似乎是解压失败了

C:\Users\用户名\betterncm\plugins 下有东西吧

**Comment by LuxQuet** [comment]
有三个.plugin文件

**Comment by MicroCBer** [comment]
方便远程吗

**Comment by LuxQuet** [comment]
可以 只有TeamViewer

**Comment by MicroCBer** [comment]
ok

**Comment by LuxQuet** [comment]
直接在这发？

**Comment by MicroCBer** [comment]
b站私吧

**Comment by MicroCBer** [comment]
中文用户名的问题

**Comment by MicroCBer** [comment]
改了下数据文件夹就可以了，改天做个允许更改数据文件夹

**Comment by MicroCBer** [comment]
之前可以现在不行可能是我换了编译环境的原因

**Comment by MicroCBer** [comment]
顺便测试了一下UNM的安装（）

**Comment by LuxQuet** [comment]
行 非常谢谢
