### ISSUE TITLE
[ Bug ] 打开插件选项显示空白

### ISSUE THREAD

**Issue by AIX700800** [MicroCBer/BetterNCM#422]
### Bug 描述

昨晚正常使用且版本为最新版，今天打开显示插件空白。
重载NCM和重装NCM都未得到解决
退回旧版网易云和更新新版都未得到解决

### 复现步骤

1.打开网易云
2.打开插件选项
3.显示插件没有可用设置选项

### 期望行为

我希望能快速找到问题，并正常使用

### 屏幕截图

![unknown_2023 08 14-16 40](https://github.com/MicroCBer/BetterNCM/assets/142211274/fe12a813-6a57-41af-9e0e-2bc81d355cdf)

![unknown_2023 08 14-17 49](https://github.com/MicroCBer/BetterNCM/assets/142211274/46bba471-53db-48b8-a561-870fd3ba6d4e)

### BetterNCM 版本

1.3.0-RC4

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

781a990

**Comment by MicroCBer** [comment]
请点击设置，切换插件源

**Comment by AIX700800** [comment]
> 请点击设置，切换插件源
这个问题解决了，后面出现了打开空白，甚至连加载失败都不显示，怎么解决啊？？？
