### ISSUE TITLE
加载不出来而且还一直提示检查更新中

### ISSUE THREAD

**Issue by MrNya907** [MicroCBer/BetterNCM#423]
### Bug 描述

加载不出来而且还一直提示检查更新中

### 复现步骤

装上打开网易云就这样了，试过旧版本也没用（截图是用的一键安装器的最新版）

### 期望行为

望处理一下

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/115851525/fad0cb83-909c-4b62-8f59-3b6d577078bb)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

1:781a990

**Comment by daytime001** [comment]
我也是这样！

**Comment by fengxuanzs** [comment]
+1
一样
![屏幕截图(1)](https://github.com/MicroCBer/BetterNCM/assets/119654901/59f2d203-023c-4ead-a3ed-15029cc40758)

**Comment by MicroCBer** [comment]
点击“重载插件”

**Comment by fengxuanzs** [comment]
> 点击“重载插件”
点击“重启并重载插件”也不行
重启电脑也试过了

**Comment by MicroCBer** [comment]
那可能是连不上更新服务器

不过这不重要，能用就行
