### ISSUE TITLE
关于网易云3.0.0beta与wallpaper麻匪音频识别

### ISSUE THREAD

**Issue by Funyu78** [MicroCBer/BetterNCM#424]
### 描述你想要的功能

3.0.0beta有适配的考虑吗，大概时间可以透露一下

### 描述你考虑过的替代方案

或者能推出一个专门版本能让壁纸识别变化就行

**Comment by MicroCBer** [comment]
https://github.com/MicroCBer/BetterNCM/releases/tag/1.3.0-rc4
