### ISSUE TITLE
打开网易显示无插件选项

### ISSUE THREAD

**Issue by AIX700800** [MicroCBer/BetterNCM#426]
### Bug 描述

正常打开网易云音乐显示无插件选项
或许是我傻的原因

### 复现步骤

1.开打插件
2.显示无插件选项

### 期望行为

希望得到解决

### 屏幕截图

![unknown_2023 08 23-22 49](https://github.com/MicroCBer/BetterNCM/assets/142211274/24c48c47-a82b-4be8-8153-6b626c1e6def)

### BetterNCM 版本

1.1.0

### 网易云音乐版本

2.10.11（x86）

### 网易云音乐 Patch 版本

1：781a990

**Comment by GADDQ** [comment]
只是你网不好，访问不了github
换源到ghproxy就行了

**Comment by MicroCBer** [comment]
点击重载插件

**Comment by AIX700800** [comment]
>也不行啊，你能帮我弄吗，有偿
点啥都没反应，还会崩溃
