### ISSUE TITLE
[ Bug ] 更新插件之后本体全白页面

### ISSUE THREAD

**Issue by Saber222333** [MicroCBer/BetterNCM#427]
### Bug 描述

今天更新插件之后本体全白页面，本体卸载重装后可用，安装插件之后还是会变成白屏x64和x86版本都会
插件卸载之后本体正常使用

### 复现步骤

1. 使用betterncm_installer安装插件版本1.3.0-RC5
2. 打开网易云本体
3. 看到错误

### 期望行为

正常使用

### BetterNCM 版本

1.3.0-RC5

### 网易云音乐版本

3.0.0（201795）和2.10.12

### 网易云音乐 Patch 版本

ab17813和1：cc29d5f

**Comment by MicroCBer** [comment]
按F12，切到Console，截图上传看看

**Comment by Saber222333** [comment]
![屏幕截图 2023-08-25 165040](https://github.com/MicroCBer/BetterNCM/assets/143164728/c8fcf51f-4421-4f07-b0fc-348abd39cfc1)
![屏幕截图 2023-08-25 165140](https://github.com/MicroCBer/BetterNCM/assets/143164728/eb494810-1ddd-48c5-a37d-0ff73d25780f)

**Comment by Saber222333** [comment]
![屏幕截图 2023-08-25 170439](https://github.com/MicroCBer/BetterNCM/assets/143164728/fbca1e23-2d95-4545-8917-8e8a2145f363)
![屏幕截图 2023-08-25 165040](https://github.com/MicroCBer/BetterNCM/assets/143164728/fb7a9035-328f-4eac-8944-e467e589f61b)
![屏幕截图 2023-08-25 170513](https://github.com/MicroCBer/BetterNCM/assets/143164728/15cbf631-d8c3-4f7d-b210-cdc638f7aa54)

**Comment by MicroCBer** [comment]
fixed in 0.0.4
