### ISSUE TITLE
版本检测bug

### ISSUE THREAD

**Issue by xiaosi004** [MicroCBer/BetterNCM#428]
### Bug 描述

版本更新提示错误
![image](https://github.com/MicroCBer/BetterNCM/assets/116878905/8aece176-93f8-41ed-8c35-0e25d7c891c8)
![image](https://github.com/MicroCBer/BetterNCM/assets/116878905/ac74e681-13e7-4226-a699-b68c3da22e3a)

### 复现步骤

点击BetterNCM 按钮打开就提示更新到错误版本

### 期望行为

修复版本更新错误提示

### BetterNCM 版本

1.3.0-RC5

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

cc29

**Comment by MicroCBer** [comment]
这是因为 1.3.0 尚未正式发版
