### ISSUE TITLE
[功能请求] 操作增强插件 增加 保存歌曲专辑封面 功能

### ISSUE THREAD

**Issue by IASUI** [MicroCBer/BetterNCM#43]
增加 保存歌曲专辑封面 功能

**Comment by MicroCBer** [comment]
建议通过F12直接查看……有图的地方比较多 不太可能每个有图的地方都做右键保存吧

**Comment by IASUI** [comment]
@MicroCBer  大概是歌单详情页里的歌单封面、专辑详情页的专辑封面、播放中歌曲这三个地方。跟手机app对应.
