### ISSUE TITLE
[ Bug ] 插件市场加载不出来，无法使用，科学后也是。

### ISSUE THREAD

**Issue by ChaingTsung** [MicroCBer/BetterNCM#430]
### Bug 描述

插件市场加载不出来，无法使用，科学后也是。

### 复现步骤

更新安装好betterncm后，打开进行设置，插件市场加载不出来，科学后也是这样

### 期望行为

能加载出插件市场画面

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/140521752/2d28de1e-e531-4be1-8bee-01fe81c1f954)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.11

### 网易云音乐 Patch 版本

578da44

### 补充

![image](https://github.com/MicroCBer/BetterNCM/assets/140521752/107192aa-578f-4bb3-8cae-835be5dc2813)

**Comment by ChaingTsung** [comment]
目前已回到官方bate内测版使用，
感觉gu官方内测版UI还不错
![image](https://github.com/MicroCBer/BetterNCM/assets/140521752/2eda68ef-9be2-4bec-ba38-db8903f26e26)

**Comment by MicroCBer** [comment]
更新到1.3.0-rc6并删除PluginMarkey.plugin后重启
