### ISSUE TITLE
[ Plugin Bug ] 已知BGEnhanced与logcleaner不兼容

### ISSUE THREAD

**Issue by ITRS-stake** [MicroCBer/BetterNCM#431]
### Bug 描述

BGEnhanced功能无效，且BGEnhanced选项全黑
解决办法：检查是否安装了logcleaner并删除

### 复现步骤

1.安装BGEnhanced
2.安装logcleaner
3.重载后BGEnhanced失效
4.删除logcleaner后BGEnhanced重新生效

### 期望行为

本体有自检插件冲突的选项

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

cc29d5f

### 已安装插件

inflink
Material You
BGEnhanced
roundcornerNCM
LibEAPIRequest
FluentProgressBar
任务栏歌词
Apple Music-like lyrics
CrossFade LFP
这首歌的封面是什么？
SimpleAudioVisualizer
FluentMusicCover
RevivedSource
LiveSongplayer
StylesheetLoader
LibLyric
明/暗主题切换器
LibSongInfo

**Comment by MicroCBer** [comment]
fixed in logcleaner 0.0.5
