### ISSUE TITLE
[ Bug ] 在3.0.0Beta中加载了尚未支持的插件

### ISSUE THREAD

**Issue by yangnuozhen** [MicroCBer/BetterNCM#433]
### Bug 描述

在3.0.0Beta中加载了尚未支持的插件，导致界面混乱、主体崩溃。

### 复现步骤

no response

### 期望行为

![image](https://github.com/MicroCBer/BetterNCM/assets/56541171/c687c32f-2719-4f94-a13c-f6e85a23265b)

### 屏幕截图

![821d914c4e8ad361bccb22d0d4ca76cd](https://github.com/MicroCBer/BetterNCM/assets/56541171/10f2b0b9-7195-49ec-a761-f9b69dcf9d55)

### BetterNCM 版本

1.3.0-rc6

### 网易云音乐版本

3.0.0.201853

### 网易云音乐 Patch 版本

cbdb79f

**Comment by 2623684696** [comment]
我也遇到了
我是直接去C:\betterncm\plugins 删了

**Comment by yangnuozhen** [comment]
> 我也遇到了 我是直接去C:\betterncm\plugins 删了

是BNCM没完善的功能啦（

**Comment by Yan6527** [comment]
![Snipaste_2023-10-07_09-00-33](https://github.com/MicroCBer/BetterNCM/assets/101031237/6761abfd-1bb0-41cd-84b2-d205e1549267)
为什么周董的歌还是显示没有版权，
![Snipaste_2023-10-07_09-00-18](https://github.com/MicroCBer/BetterNCM/assets/101031237/50ecc424-2882-4bed-82bb-a55443811362)

**Comment by yangnuozhen** [comment]
> ![Snipaste_2023-10-07_09-00-33](https://user-images.githubusercontent.com/101031237/273353680-6761abfd-1bb0-41cd-84b2-d205e1549267.png) 为什么周董的歌还是显示没有版权， ![Snipaste_2023-10-07_09-00-18](https://user-images.githubusercontent.com/101031237/273353668-50ecc424-2882-4bed-82bb-a55443811362.png)

跟这个Issue有什么关系？
