### ISSUE TITLE
[ Bug ] betterncm一直在检查更新

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#434]
### Bug 描述

![图片](https://github.com/MicroCBer/BetterNCM/assets/81459639/5e92b9b1-3e6c-4283-994b-2b9b245bba5b)
就这样转，但是插件源除了gitee其他的都是可以正常加载的。

### 复现步骤

打开betterncm设置页面，就可看见

### 期望行为

检查更新几分钟成功或是失败给个提示

### BetterNCM 版本

1.3.0（原先是1.2.3，我手动更新到1.3.0但问题依旧存在）

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:cc29d5f

**Comment by MicroCBer** [comment]
正常，正式版130改
