### ISSUE TITLE
卸载之后重新安装再次开启启动直接卡屏

### ISSUE THREAD

**Issue by MoCo1134** [MicroCBer/BetterNCM#435]
### Bug 描述

![QQ图片20230908101924](https://github.com/MicroCBer/BetterNCM/assets/142894605/100e0658-f1e7-42b0-8006-66150769d4e2)

### 复现步骤

刚开始接触插件是因为某个公众号
不知道到底是不是版本冲突或者怎么，首次在GitHub上面下载BetterNCM插件
报错，bug，崩溃

### 期望行为

不知道是什么情况，1.3.0-RC6版本卸载老版本之后重新安装还是会卡，然后崩溃无数次提示unicorn字符不存在

### BetterNCM 版本

1.3.0-RC6

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:cc29d5f

**Comment by MoCo1134** [comment]
![QQ图片20230908102959](https://github.com/MicroCBer/BetterNCM/assets/142894605/1412d486-0f27-43bb-8c50-00db7713fc2d)
![QQ图片20230908103028](https://github.com/MicroCBer/BetterNCM/assets/142894605/38638eb3-76cd-45d7-a0b2-fbad83cfd919)

**Comment by MicroCBer** [comment]
> ![QQ图片20230908102959](https://user-images.githubusercontent.com/142894605/266484599-1412d486-0f27-43bb-8c50-00db7713fc2d.png) ![QQ图片20230908103028](https://user-images.githubusercontent.com/142894605/266484605-38638eb3-76cd-45d7-a0b2-fbad83cfd919.png)

你这张图不是没有问题吗

**Comment by MoCo1134** [comment]
这个只是我下载的版本，该崩还是崩，

**Comment by MoCo1134** [comment]
这只是我的版本，该崩还得崩，打不开网易云也退不出去（图一）

**Comment by MicroCBer** [comment]
二图很明显是一个已经打开了网易云的图啊
