### ISSUE TITLE
【Bug】无法正常使用，显示“该插件没有可用的设置选项”

### ISSUE THREAD

**Issue by linyun2233** [MicroCBer/BetterNCM#436]
### Bug 描述

所有的插件以及插件商店都无法运行，打开插件管理页面后，上方显示“检查更新中”，下方显示“该插件没有可用的设置选项。”
重载，重装插件，以及重启，重装网易云都没有得到解决。

### 复现步骤

1.打开网易云
2.发现之前安装的美化插件没有正常运行。
3.打开插件管理器
4.显示“该插件没有可用的设置选项”

### 期望行为

希望找到并解决问题，正常使用。

### 屏幕截图

无法添加截图，但大概是这样的
图标
图标    betterncm 1.3.0
图标    打开插件文件夹  打开控制台  重载插件  （加载中图标）检查更新中
            该插件没有可用的设置选项

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

a566dbd

### 补充

非常好的插件，可惜我只体验了一天就遇上了这糟心的bug

**Comment by MicroCBer** [comment]
更新到rc6，重启两次

**Comment by linyun2233** [comment]
> 更新到rc6，重启两次

抱歉，是我没有注明这个细节，我的版本就是rc-6，多次连续重启也试过了，还是没有效果，甚至出现了两次没能打开网易云的情况。
还有一点是，我的网易云装在D盘，我试着点击“打开插件文件夹”时，只能定位到D盘（[此电脑→Data D]），而我在D盘中没有找到插件文件，反而是在C盘的搜索里找到了。请问这样是正常的吗？

**Comment by yangnuozhen** [comment]
> > 更新到rc6，重启两次
> 
> 抱歉，是我没有注明这个细节，我的版本就是rc-6，多次连续重启也试过了，还是没有效果，甚至出现了两次没能打开网易云的情况。 还有一点是，我的网易云装在D盘，我试着点击“打开插件文件夹”时，只能定位到D盘（[此电脑→Data D]），而我在D盘中没有找到插件文件，反而是在C盘的搜索里找到了。另外，我在用betterncm installer（版本1.1.1）选择卸载betterncm以后，只是网易云里的插件管理器图标消失了，而C盘中的betterncm.dll的文件依旧存在。请问以上这些是正常的还是bug呢？实在麻烦了！

第一个定位到D盘不知道是什么原因，但是插件不和NCM存放在同一个文件夹。

对于你说的betterncm.dll的文件依旧存在，那个dll文件应该是你手动下载的，手动删除即可。

**Comment by MicroCBer** [comment]
> > 更新到rc6，重启两次
> 
> 抱歉，是我没有注明这个细节，我的版本就是rc-6，多次连续重启也试过了，还是没有效果，甚至出现了两次没能打开网易云的情况。 还有一点是，我的网易云装在D盘，我试着点击“打开插件文件夹”时，只能定位到D盘（[此电脑→Data D]），而我在D盘中没有找到插件文件，反而是在C盘的搜索里找到了。另外，我在用betterncm installer（版本1.1.1）选择卸载betterncm以后，只是网易云里的插件管理器图标消失了，而C盘中的betterncm.dll的文件依旧存在。请问以上这些是正常的还是bug呢？实在麻烦了！

你在安装时乱改了数据文件夹位置，改回默认（C:/betterncm）即可

**Comment by TTTNT** [comment]
我什么都没做，什么也没改但是也出现了一样的问题，用了半个小时后就用不了了，重装装载什么都没用大佬可以远程帮下我吗

**Comment by TTTNT** [comment]
> 我什么都没做，什么也没改但是也出现了一样的问题，用了半个小时后就用不了了，重装装载什么都没用大佬可以远程帮下我吗

vx：TTTNT7

**Comment by copenwu** [comment]
如何将数据文件位置改回默认呢？我的c盘里没有betterncm，总动下载到D盘里了

**Comment by yangnuozhen** [comment]
> 如何将数据文件位置改回默认呢？我的c盘里没有betterncm，总动下载到D盘里了

修改PATH 或者在[BetterNCM-Installer](https://github.com/MicroCBer/BetterNCM-Installer) 内修改回默认。

**Comment by M0dness** [comment]
你好，我也遇到了这样的问题，我尝试了BetterNCM-Installer内的手动修改和重置按钮，但是没有用，他还是会回到我乱改的地址。不知道改如何解决.现在已知的解决方法为，每次打开网易云需要用BetterNCM-Installer进行重装更新，才能正常打开插件。

**Comment by M0dness** [comment]
> 你好，我也遇到了这样的问题，我尝试了BetterNCM-Installer内的手动修改和重置按钮，但是没有用，他还是会回到我乱改的地址。不知道改如何解决.现在已知的解决方法为，每次打开网易云需要用BetterNCM-Installer进行重装更新，才能正常打开插件。

顺便一提，我每次把乱改地址的文件删掉，每次打开网易云他又会生成一个乱改地址的数据文件。

**Comment by haihai0128** [comment]
c盘中的betterncm文件夹删除掉，打开网易云，更改下载源，就可以显示了

**Comment by FenleyHalebourne** [comment]
试试删除环境变量中BETTERNCM_PROFILE变量（用户变量和系统变量都删除），然后重启网易云试试，这个时候应该会在C盘下新建一个betterncm文件夹；如果要自定义插件路径的话使用betterNCM-installer修改数据路径为一个全英文的路径应该就可以了
