### ISSUE TITLE
[ Bug ] 一直显示检查更新，无可用设置选项

### ISSUE THREAD

**Issue by zhonghuabie** [MicroCBer/BetterNCM#439]
### Bug 描述

本体已经是最新版本，前一天还是正常使用，而且没有挂加速器也正常使用，也显示了插件今天就出问题了.
重新下载安装也试过，挂加速器也试过了，但依旧解决不了。

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

期望得到解决

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/146697101/bba6f80b-fc16-4984-9d60-350aedae615b)
![image](https://github.com/MicroCBer/BetterNCM/assets/146697101/bd7dcf8f-c9c8-4a15-af3e-7758c22eb4bf)

### BetterNCM 版本

1.3

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1：62cafa7

**Comment by karlzero1** [comment]
我也一样，怎么解决啊

**Comment by l3543647041** [comment]
怎么解决

**Comment by MicroCBer** [comment]
请更新到最新版

**Comment by l3543647041** [comment]
> 请更新到最新版

怎么样更新

**Comment by MicroCBer** [comment]
使用 BetterNCM Installer 更新到最新版，且将数据位置修改回 `C:/betterncm`

**Comment by AIX700800** [comment]
> 使用 BetterNCM Installer 更新到最新版，且将数据位置修改回`C:/betterncm`
想问一下怎么该回去？修改数据地址和重置数据地址都没有用
