### ISSUE TITLE
[BUG ？& 功能请求] BGEnhanced 插件 删除壁纸后，C:\Users\用户名\betterncm\temp 中文件不删除

### ISSUE THREAD

**Issue by IASUI** [MicroCBer/BetterNCM#44]
- BUG现象：如图，文件不同步删除。（当我导入壁纸删除后，若忘记清除，将浪费存储空间，尤其是视频文件）
- BUG现象：插件v0.23点击【Open Folder】不会打开数据文件夹
- 疑问：壁纸导入使用的方式是复制一份文件，但这样可能会造成空间浪费，如果是链接到文件呢？（可能文件删除或移动导致找不到 
   文件）是否有更好的方式？
- 请求：为了避免重新装插件等情况后，重新导入壁纸，我每次都是先复制文件，再复制回去，是否可以导出壁纸数据。
- 请求：MoTheme主题-**背景模糊效果**：增加 兼容 BGEnhanced **视频格式壁纸**

![image](https://user-images.githubusercontent.com/66980246/193569919-853806fc-55a6-45d9-8cda-d752b7bd4108.png)
![image](https://user-images.githubusercontent.com/66980246/193569979-e02dad2b-3503-4376-b11d-05ee6941eecc.png)
![image](https://user-images.githubusercontent.com/66980246/193571237-fe44b4cf-75c1-4d5d-bfb9-d4a371e8aea1.png)

**Comment by MicroCBer** [comment]
不同步删除是某个人懒得写的原因（）

**Comment by MicroCBer** [comment]
第二个已经修了 还没发出来

**Comment by IASUI** [comment]
> 不同步删除是某个人懒得写的原因（）

😂好吧

**Comment by MicroCBer** [comment]
背景模糊效果我的建议是自己做一下 直接做在视频里 实时算感觉有点浪费 到时候又有人要说我挖矿了

非要做的话也不是不行吧 我考虑一下

**Comment by MicroCBer** [comment]
壁纸是复制的原因是 web端拿不到选中文件的真实路径……只能拿到数据

要节省就得自己写文件选择框，之后很可能会做，但是就看我咕多久了

**Comment by IASUI** [comment]
@MicroCBer  OK,了解👍

**Comment by MicroCBer** [comment]
已修复，不再复制文件，而是采用新 API `mountFile` 挂载到 httpServer
