### ISSUE TITLE
[ Bug ] 逆天PluginMarket动画问题

### ISSUE THREAD

**Issue by bhop0** [MicroCBer/BetterNCM#440]
### Bug 描述

展示插件的卡片堆叠在一起

### 复现步骤

idk
实在太过于巧合，可能是插件商店本身的性能问题

### 期望行为

正常排列

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/146635994/f643d3b4-93a5-4d3b-b183-901c4c6fbfd1)

### BetterNCM 版本

1.3.0 RC-6

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

62cafa7

**Comment by MicroCBer** [comment]
无法复现，影响较小
