### ISSUE TITLE
[ FR ] 请求能不能做一个qq音乐版本的哇

### ISSUE THREAD

**Issue by T-omeey** [MicroCBer/BetterNCM#441]
### 描述你想要的功能

qq音乐的桌面歌词实在是做的稀烂啊，左对齐了，但是没有完全对齐
在播放界面设置了显示翻译，桌面歌词也直接同步过来了
想做win11任务栏歌词就做不成了哇
![image](https://github.com/MicroCBer/BetterNCM/assets/108618853/e1f4f77c-c771-4fc8-b7a2-1ca65b0edf5c)
![image](https://github.com/MicroCBer/BetterNCM/assets/108618853/62ab6f47-c422-4399-9778-50f999ad55f2)
跪求一个q音的插件啊
谢谢啦

**Comment by MicroCBer** [comment]
主要是我不用……暂时不考虑

CppLyrics 后期可能会尝试兼容一下
