### ISSUE TITLE
求助有没有插件可以强制关闭网易云自动更新版本

### ISSUE THREAD

**Issue by slromusb** [MicroCBer/BetterNCM#443]
### 描述你想要的功能

强制关闭网易云自动更新版本，有时网易云自动更新bate版本，有没有插件可以强制关闭网易云自动更新

**Comment by mapleNJU** [comment]
在网易云的设置里，最后有一个“关于网易云音乐”，在那里可以设置“自动更新”或者“有新版本时提醒我”，可以试一下
