### ISSUE TITLE
能否支持最新版的pc网易云

### ISSUE THREAD

**Issue by lsjg292** [MicroCBer/BetterNCM#446]
### 描述你想要的功能

恢复任务栏歌词插件，歌词效果插件，现在网易云打开betterncm还一直是检查更新的状态

### 额外的背景

![0LDPT{303YA8LZ@G}XEM7TQ](https://github.com/MicroCBer/BetterNCM/assets/122085186/ab576e7c-c8e6-4606-8eb9-c8ef09642c44)

**Comment by MicroCBer** [comment]
新版网易云变动较大，部分插件会慢慢移植过来
