### ISSUE TITLE
[ Bug ] 网易云音乐2.10.12 插件页面显示该插件没有可用的设置选项

### ISSUE THREAD

**Issue by sst2020** [MicroCBer/BetterNCM#447]
### Bug 描述

网易云音乐2.10.12 插件页面显示该插件没有可用的设置选项
所有插件包括plugin market均无法使用

### 复现步骤

**例**:
1. 打开"网易云"
2. 点击'插件图标'
3. 看到错误

### 期望行为

插件能使用

### 屏幕截图

![图片](https://github.com/MicroCBer/BetterNCM/assets/77180679/f57bd219-0134-4c8e-9f9a-df6ae833a68a)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12 (Build:201849) (Patch:1:cc29d5f)

### 网易云音乐 Patch 版本

cc29d5f

### 补充

__无__

**Comment by MicroCBer** [comment]
duplicated #439

**Comment by MadBoy13** [comment]
删除CppLyrics这个插件，实测安装以后就会有这个BUG，没有效果的话就把所有插件删除 @MicroCBer @sst2020

**Comment by MicroCBer** [comment]
> 删除CppLyrics这个插件，实测安装以后就会有这个BUG，没有效果的话就把所有插件删除 @MicroCBer @sst2020 

无法复现 可以截图你安装后的插件文件夹（plugins，plugins_runtime）内容吗

另外github会自动通知所有participants，不用at
