### ISSUE TITLE
打开网易云弹出windows找不到start_easyrp.bat

### ISSUE THREAD

**Issue by shaihai0** [MicroCBer/BetterNCM#450]
### Bug 描述

在装配BetterNCMD的IndLink的前提下打开网易云音乐，会弹出“windows找不到start_easyrp.bat，请确定文件名是否正确后，再试一次”的窗口提示。
导致了Wallpaper Engine音频识别壁纸卡死或无法识别音频替换壁纸画面。
在重启电脑、重新安装网易云音乐与BetterNCMD installer后依然没有恢复正常。

### 期望行为

期望修复或解决教程

### 屏幕截图

![问题上报](https://github.com/MicroCBer/BetterNCM/assets/150021117/c28e5a23-695b-4576-bbcb-4288f07f10e6)
![问题上报2](https://github.com/MicroCBer/BetterNCM/assets/150021117/5cc20b72-ca52-4361-a7d1-2aefa3f18ffe)

### BetterNCM 版本

1.1.1

### 网易云音乐版本

2.10.12(x86)

### 网易云音乐 Patch 版本

1:3c65ae6

**Comment by Cruise0012** [comment]
我卸载之后重新装一遍就好了

**Comment by shaihai0** [comment]
> 我卸载之后重新装一遍就好了，但是识别壁纸和歌名还是会卡住

**Comment by shaihai0** [comment]
> 我卸载之后重新装一遍就好了，但是识别壁纸和歌名还是会卡住

**Comment by zme70** [comment]
我把所有插件都删除就好了

**Comment by zme70** [comment]
infLink这个插件导致的

**Comment by zme70** [comment]
解决办法：打开CMD输入（无需管理员），del /f /s /q C:\betterncm

**Comment by zme70** [comment]
解决办法：
网易云音乐里删除所有已经安装插件，
执行命令del /f /s /q C：\betterncm，
检查C:\betterncm是否删除成功
安装纯净分享链接，重启
安装InfLink，你就会发现没有报错了

**Comment by zme70** [comment]
觉得del /f /s /q C：\betterncm怕误删可以手动删，不过你需要重启电脑，因为有文件占用不能删的问题

**Comment by MicroCBer** [comment]
如果不用就不要开启SMTC。。。
