### ISSUE TITLE
[ Bug ] QuQ商店加载不出来，代理也没有quq，一直显示检查更新

### ISSUE THREAD

**Issue by yxCrucio** [MicroCBer/BetterNCM#451]
### Bug 描述

QuQ商店加载不出来，代理也没有quq，一直显示检查更新

### 复现步骤

1、点设置

### 期望行为

希望能修复捏

### 屏幕截图

![屏幕截图 2023-11-12 225528](https://github.com/MicroCBer/BetterNCM/assets/105279343/111ec28d-fa8c-4a82-a1b1-e620d96c4807)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12(Build:2184)

### 网易云音乐 Patch 版本

1:3c65ae6

**Comment by liulini** [comment]
我也是同样的问题，试着换了换源。有时候还是能成功的。
![image](https://github.com/MicroCBer/BetterNCM/assets/64997680/37b30c52-610a-40c0-94ea-4c24416738f6)

**Comment by liulini** [comment]
换个源试试。

**Comment by MicroCBer** [comment]
- 插件商店提示获取失败：
请在 BetterNCM Installer 内更新到最新版（获取不到就请先更新 installer），然后删除 C:\betterncm\plugins\PluginMarket.plugin 并重启
如果依然不行，点击设置按钮并删除由插件添加的源
