### ISSUE TITLE
[ Bug ]  更新后出现白屏的问题（已初步排查出原因）

### ISSUE THREAD

**Issue by luotianyiismywife** [MicroCBer/BetterNCM#452]
### Bug 描述

网易云自动更新后，插件掉了，于是通过installer进行更新，但在更新完成后打开网易云会白屏
![图片](https://github.com/MicroCBer/BetterNCM/assets/81459639/3d4482d0-c2ec-4c6a-bc78-296aac83430e)
情况如下

### 复现步骤

更新网易云
使用installer更新插件
更新完成后自动打开网易云即可复现

### 期望行为

正常加载网易云

### BetterNCM 版本

1.3.0-RC6

### 网易云音乐版本

3.0.3

### 网易云音乐 Patch 版本

未正常加载，故无法查看

**Comment by luotianyiismywife** [comment]
在另一台电脑上先删除c盘根目录下的betterncm文件夹后更新插件正常打开成功。
但当原本的betterncm插件拷回去后成功复现第一台电脑的白屏问题。

**Comment by luotianyiismywife** [comment]
当打算删除第一台台电脑上的c盘根目录下的betterncm文件夹时提示占用，但我已关闭全部可能会占用的程序，我先重启一下试试。
如果第一台电脑也没问题结合3.0的新版插件库插件较少的问题推断可能是一些插件无法在新版被正确加载导致的白屏。
但由于旧版本用的比较习惯且新版本缺少一些常用插件顾打算继续使用旧版本直至插件兼容新版本。

**Comment by MicroCBer** [comment]
fixed
