### ISSUE TITLE
更新最新版本(BetterNCM 1.3.0 RC6)后插件失效

### ISSUE THREAD

**Issue by mir-xiong** [MicroCBer/BetterNCM#453]
### Bug 描述

更新最新版本(BetterNCM 1.3.0 RC6)后插件失效，网易云启动后界面显示和没有插件的页面一样(更新前我是有下载插件并且生效的)

更新后的启动效果
![image](https://github.com/MicroCBer/BetterNCM/assets/150424027/412692fc-22d7-4e67-b822-de75a41fc14b)

### 复现步骤

1. 关闭网易云
2. 下载Github上的最新插件版本(BetterNCM 1.3.0 RC6)
3. 重命名为msimg32.dll
4. 替换网易云的安装目录下的旧版msimg32.dll
5. 启动网易云

### 期望行为

更新插件后启动网易云，效果有插件，并且报错和我之前下载的插件内容一致

### BetterNCM 版本

BetterNCM 1.3.0 RC6

### 网易云音乐版本

2.10.12（Build: 201849）

### 网易云音乐 Patch 版本

Patch:1:3c65ae6

**Comment by mir-xiong** [comment]
并且回退到 BetterNCM 1.21 版本 是可以正常生效的：
![image](https://github.com/MicroCBer/BetterNCM/assets/150424027/41f1d830-7be3-4450-941d-1c91f9c7ef78)

**Comment by AdoShan** [comment]
> 并且回退到 BetterNCM 1.21 版本 是可以正常生效的： ![image](https://user-images.githubusercontent.com/150424027/282985007-41f1d830-7be3-4450-941d-1c91f9c7ef78.png)

我也遇到一样的情况网易云版本以及Patch都是一样的，不过我回退到1.2.3也可以正常加载插件

**Comment by MicroCBer** [comment]
检查 F12 是否有作用，以及 msimg32.dll 文件大小？

**Comment by mir-xiong** [comment]
> 检查 F12 是否有作用，以及 msimg32.dll 文件大小？

msimg32.dll 文件是指什么？所有的文件我都是从github下载的

**Comment by mir-xiong** [comment]
> > 并且回退到 BetterNCM 1.21 版本 是可以正常生效的： ![image](https://user-images.githubusercontent.com/150424027/282985007-41f1d830-7be3-4450-941d-1c91f9c7ef78.png)
> 
> 我也遇到一样的情况网易云版本以及Patch都是一样的，不过我回退到1.2.3也可以正常加载插件

我在github release界面没找到1.2.3版本的，只看到了1.2.1版本的；
