### ISSUE TITLE
一直提示检查更新中

### ISSUE THREAD

**Issue by Laven-47** [MicroCBer/BetterNCM#456]
### Bug 描述

无法使用betterncm 提示 检查更新中。
<img width="585" alt="屏幕截图 2023-11-19 181004" src="https://github.com/MicroCBer/BetterNCM/assets/118798117/adaf6bdc-52e4-4787-b780-08f37b22c9b5">

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望能够得到回复并解决该问题。

### BetterNCM 版本

1.3.0RC6

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

cc29d5f

### 补充

重装网易云音乐以及betterncm后都无法解决该问题，当然我也尝试魔法上网也仍如此。
<img width="585" alt="屏幕截图 2023-11-19 181004" src="https://github.com/MicroCBer/BetterNCM/assets/118798117/71110359-313c-4451-a684-738056ff6ffc">

**Comment by Laven-47** [comment]
我应该怎么解决这个问题？求助求助。

**Comment by Sodaly1318** [comment]
#434

**Comment by Laven-47** [comment]
> #434

什么意思？

**Comment by Laven-47** [comment]
> #434

所以你也有这个问题，作者还没解决吗？

**Comment by MicroCBer** [comment]
你用不了并不是因为检查更新卡住了

**Comment by MicroCBer** [comment]
duplicate #439
