### ISSUE TITLE
InfLink识别新版网易云的封面,获取的是用户头像

### ISSUE THREAD

**Issue by haoshenwan** [MicroCBer/BetterNCM#457]
### Bug 描述

我是用识别音频的壁纸,
InfLink识别新版网易云的封面,获取的是用户头像,而不是歌曲封面本身

### 复现步骤

1.点击歌曲播放
2.壁纸切换封面
3.显示用户头像

### 期望行为

应该随着音乐的切换 更换背景的歌曲封面

### 屏幕截图

<img width="1280" alt="image" src="https://github.com/MicroCBer/BetterNCM/assets/128103579/9e6dedb5-a6d2-4a8f-82af-3f62d67ed215">
<img width="1280" alt="屏幕截图 2023-11-20 155749" src="https://github.com/MicroCBer/BetterNCM/assets/128103579/194b1cd7-bb67-4a83-a24d-1b6c805d8e29">
<img width="1280" alt="屏幕截图 2023-11-20 155802" src="https://github.com/MicroCBer/BetterNCM/assets/128103579/ee025214-1186-4b61-96e2-5213def38cfd">

### BetterNCM 版本

1.3.0

### 网易云音乐版本

3.0.0.beta

### 网易云音乐 Patch 版本

d9e68a5

### 已安装插件

**例**:
- inflink

**Comment by 631894570** [comment]
想识别专辑封面，降级到2.X版本  关闭自动升级，InfLink目前没完全适配3.0

**Comment by MicroCBer** [comment]
duplicated #457
