### ISSUE TITLE
[ Plugin Bug ] infLink插件无法正常使用，无法移除等问题

### ISSUE THREAD

**Issue by shaihai0** [MicroCBer/BetterNCM#458]
### Bug 描述

安装BetterNCMD installer打开网易云后没有任何问题

出现的问题是在下载插件后
1,下载infLink后，文件加载不完整的问题

2,文件补全后，infLink不能运行的问题

3.通过移除与重新下载infLink的问题

4.BetterNCMD installer与网易云音乐版本有差异的问题

### 复现步骤

以上问题的详细描述

1. 打开网易云，出现提示“windows找不到start_easyrp.bat，请确认文件名称是否正确‘’。（图一）
我从https://github.com/BetterNCM/InfinityLink/blob/main/src/index.tsx，把缺失的文件拷贝并放入InfLink-Discord-RPC文件夹下
找不到文件的提示弹窗就没有了。

2. 启动网易云音乐，弹出‘’此应用无法在你的电脑上运行‘’的窗口（图二）
 我打开InfLink-Discord-RPC文件夹并尝试启动easyrp.exe程序，弹出‘’此应用无法在你的电脑上运行‘’的窗口（图三）
  （我的电脑配置并没有很低，图四）

3. 点击右侧移除按键后下方会弹出提示‘’插件的更改需要重启以生效‘’，点击 重启，重新进入网易云发现插件并没有被移除。（图五）

点击左侧插件列表栏的移除，则会立刻闪退，并重新打开网易云，插件还是没有移除。（图六）
我多次尝试移除infLink时BetterNCM提示崩溃。（图七）
在多次点击移除与重启，电脑右下角隐藏栏里出现多个网易云音乐图标（图八）
4. BetterNCMD installer与网易云音乐版本有差异（图九）

### 期望行为

修复或者解决方法

### 屏幕截图

![问题报错1](https://github.com/MicroCBer/BetterNCM/assets/150021117/d1d72b87-ee5f-4f46-aa86-ead2629a81c0)
![问题报错2](https://github.com/MicroCBer/BetterNCM/assets/150021117/18fd9ad3-c9d1-4e8b-80f4-046aee1f898d)
![问题3](https://github.com/MicroCBer/BetterNCM/assets/150021117/11abdbf4-02f3-4c47-b59e-3c59d38c5511)
![设备未老化](https://github.com/MicroCBer/BetterNCM/assets/150021117/550f28fd-a864-4281-8395-51628b7ac818)
![删除1](https://github.com/MicroCBer/BetterNCM/assets/150021117/e7a8653f-80a8-47af-9469-ccdd2acf855d)
![删除2](https://github.com/MicroCBer/BetterNCM/assets/150021117/a32c3375-aa6b-4c17-b148-b9ffa86b7416)
![删除3](https://github.com/MicroCBer/BetterNCM/assets/150021117/58c1fba6-cf30-45db-a347-2bbf32db0000)
![问题](https://github.com/MicroCBer/BetterNCM/assets/150021117/5751778e-fa68-4ed1-9688-6226834a4406)
![版本不匹配](https://github.com/MicroCBer/BetterNCM/assets/150021117/2defe2aa-23a4-4abe-970b-e68ad44ad7e0)

### BetterNCM 版本

1.1.1

### 网易云音乐版本

3.0.0.Beta(64位)(Build:202125)

### 网易云音乐 Patch 版本

d9e68a5

### 已安装插件

infLink

**Comment by MicroCBer** [comment]
左侧删除按钮没处理native plugin

**Comment by shaihai0** [comment]
> 左侧删除按钮没处理native plugin

我应该如何解决该问题

**Comment by MicroCBer** [comment]
你可以直接删除inflink.plugin文件然后重启
