### ISSUE TITLE
[ Bug ] 插件无法正常使用

### ISSUE THREAD

**Issue by AIX700800** [MicroCBer/BetterNCM#459]
### Bug 描述

打开插件显示正在检查更新，且一直转圈
插件画面显示空白

### 复现步骤

1.打开网易云音乐
2.打开插件
3.显示无可以设置的插件

### 期望行为

解决问题正常使用

### 屏幕截图

![unknown_2023 11 26-22 42](https://github.com/MicroCBer/BetterNCM/assets/142211274/4f381459-1cd9-4e92-9145-09940efa4dd1)

### BetterNCM 版本

1.1.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

1：aa07988

**Comment by AIX700800** [comment]
重装插件和重载插件也并未得到解决

**Comment by Sodaly1318** [comment]
#456 #439
