### ISSUE TITLE
[ Bug ] 关闭网易云后插件设置被初始化

### ISSUE THREAD

**Issue by dlhaizhe2023** [MicroCBer/BetterNCM#460]
### Bug 描述

在每次关闭网易云后对插件的设置都不会被保存，再次打开网易云时又回到了初始化状态，像一个歌词插件会在每次打开网易云时弹出新手教程，即使在关闭前设置关闭教程

### 复现步骤

设置插件，保存
重启网易云音乐
插件设置回到初始状态

### 期望行为

对插件的设置能够在关闭网易云音乐后保存

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:3c65ae6

**Comment by MicroCBer** [comment]
这可能是因为你两次打卡使用的用户不同（一次以管理员打开，一次直接打开）
请始终使用管理员打开或者普通用户打开
