### ISSUE TITLE
[ Bug ] BetterNCM崩溃问题，无法运行，没有此Unicode字符可以映射到的字符

### ISSUE THREAD

**Issue by GANmj03** [MicroCBer/BetterNCM#461]
### Bug 描述

无法打开插件，插件崩溃

### 复现步骤

1. 转到网易云
2. 点击网易云或者beeterNCM重装/更新
3. 看到错误

### 期望行为

想知道该如何解决，还是现在版本都是这样

### 屏幕截图

![捕获](https://github.com/MicroCBer/BetterNCM/assets/152585145/11161f18-2a87-452e-b38b-cd67f53798cb)

### BetterNCM 版本

1.1.1

### 网易云音乐版本

3.0.3（x64）

### 网易云音乐 Patch 版本

493dbd1

**Comment by GANmj03** [comment]
![捕获](https://github.com/MicroCBer/BetterNCM/assets/152585145/57a7bcce-896a-4f0e-a8c9-87afcd7c73d0)

**Comment by MicroCBer** [comment]
请清除所有插件后重试
