### ISSUE TITLE
[ Bug ] 无法创建插件开发目录

### ISSUE THREAD

**Issue by VincentSHI1230** [MicroCBer/BetterNCM#462]
### Bug 描述

想试着自己动手来着，还没起步就翻车了

### 复现步骤

```
/betterncm/plugins_dev>npm create betterncm
```

### 期望行为

正常创建 dev 工作目录

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/81342412/fdfa5ef9-1811-4386-9cf0-b857b3adc542)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

3c65ae6

**Comment by MicroCBer** [comment]
网不好 可以自行下载那个repo或者自己配置
（我邮件回复的怎么没发出去）

**Comment by VincentSHI1230** [comment]
啊，似乎是前两天我邮件服务器炸了不好意思
哦对了给您的插件发了个 pr 麻烦大佬看一下 https://github.com/BetterNCM/RoundCornerNCM/pull/6
