### ISSUE TITLE
[ FR ] 调整betterncm插件文件夹的默认存放路径

### ISSUE THREAD

**Issue by Zaphkito** [MicroCBer/BetterNCM#464]
### 描述你想要的功能

请求将“betterncm”插件文件夹放至“C:\Users\‘User name’\Documents”、“C:\ProgramData”等其他你认为合适的目录，而不是C盘根目录，保证系统磁盘分区根目录的简洁，当从旧版本更新到新版本时，询问是否迁移文件夹至新的位置

### 额外的背景

![image](https://github.com/MicroCBer/BetterNCM/assets/64299266/b53aa899-139b-4bd8-8c05-9392112a76cf)

**Comment by MicroCBer** [comment]
不改，改了问题一堆

**Comment by MicroCBer** [comment]
曾经就在%AppData%
