### ISSUE TITLE
LibFrontendPlay

### ISSUE THREAD

**Issue by kkccccoo** [MicroCBer/BetterNCM#465]
### Bug 描述

这是怎么回事

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

求解决 

### 屏幕截图

![PixPin_2023-12-17_16-01-34](https://github.com/MicroCBer/BetterNCM/assets/154048471/39fa9485-26d2-45d9-aab2-580757773fb8)

### BetterNCM 版本

1.3

### 网易云音乐版本

2.1

### 网易云音乐 Patch 版本

1：3

### 已安装插件

![PixPin_2023-12-17_16-03-58](https://github.com/MicroCBer/BetterNCM/assets/154048471/ba694e10-b325-4c1c-9083-0efe0f6839bc)
![PixPin_2023-12-17_16-04-11](https://github.com/MicroCBer/BetterNCM/assets/154048471/2984e09b-d491-4154-908b-fc2a4edf2590)

**Comment by MicroCBer** [comment]
不去管它
