### ISSUE TITLE
[ Bug ] 最新的1.3.1 版本插件依旧显示未适配

### ISSUE THREAD

**Issue by Yancey597** [MicroCBer/BetterNCM#466]
### Bug 描述

最新的1.3.1 版本插件依旧显示未适配

### 复现步骤

打开

### 期望行为

正常使用

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/46004197/e94f8a04-c579-438d-b584-f553e9f6bbff)
![image](https://github.com/MicroCBer/BetterNCM/assets/46004197/8d2a6868-d38b-4145-a0d3-609228de2d05)

### BetterNCM 版本

1.3.1

### 网易云音乐版本

3.0.0.Beta(64位)(Build: 202125)

### 网易云音乐 Patch 版本

c891959

**Comment by EYW-015** [comment]
同样情况，唯一区别`Build 202295`，安装器显示网易云版本为`3.0.4`

**Comment by MicroCBer** [comment]
我都不知道出这个版本了..晚点加进适配列表

**Comment by Yancey597** [comment]
okk

**Comment by Yancey597** [comment]
> 我都不知道出这个版本了..晚点加进适配列表

版本有更新了
![image](https://github.com/MicroCBer/BetterNCM/assets/46004197/6c070832-e304-498d-bbae-27d7d7040bf8)
