### ISSUE TITLE
[ BGEnhanced ] 无法显示本地图片

### ISSUE THREAD

**Issue by jiaxcandy** [MicroCBer/BetterNCM#467]
### Bug 描述

BGEnhanced插件无法显示本地上传的图片，只会显示原有的背景

### 复现步骤

1.点击图片功能按钮
2.选择本地图片，点击打开
3.本地图片空白且背景无变化

### 期望行为

能够使用本地图片作为背景

### 屏幕截图

![(7TB5M$5NP2)W@E@%IWW{~Y](https://github.com/MicroCBer/BetterNCM/assets/154269217/22814a94-e535-4a72-a295-49b512ebf007)

### BetterNCM 版本

1.3.1

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1：3c65ae6

### 已安装插件

1.PluginMarket
2.BGEnhanced
3.明/暗主题切换器
4.MoTheme
5.StylesheetLoader
6.ListScrollFix

**Comment by MicroCBer** [comment]
看下你选的啥图片

**Comment by jiaxcandy** [comment]
![Uploading download_20220623173651.jpg…]()

**Comment by jiaxcandy** [comment]
> 看下你选的啥图片
![download_20220623173651](https://github.com/MicroCBer/BetterNCM/assets/154269217/22bf920a-eb30-4000-b031-493047fa210d)

**Comment by jiaxcandy** [comment]
> 看下你选的啥图片

这个。
![image](https://github.com/MicroCBer/BetterNCM/assets/154269217/dd6fb9ae-aa67-4435-bd81-b0e8af0eb334)

**Comment by Binken02** [comment]
请问解决了吗？我上传视频也是这样

**Comment by jiaxcandy** [comment]
> 请问解决了吗？我上传视频也是这样

并没有，还是这个样子的。不知道怎么解决233

**Comment by Binken02** [comment]
我感觉是不是跟分辨率有关?我上传一个模糊的视频就可以，高清的就不行。。。图片清晰模糊我都没成功233



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月22日(周五) 下午2:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MicroCBer/BetterNCM] [ BGEnhanced ] 无法显示本地图片 (Issue #467)




  
请问解决了吗？我上传视频也是这样
  
并没有，还是这个样子的。不知道怎么解决233

**Comment by jiaxcandy** [comment]
> 我感觉是不是跟分辨率有关?我上传一个模糊的视频就可以，高清的就不行。。。图片清晰模糊我都没成功233
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月22日(周五) 下午2:52 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [MicroCBer/BetterNCM] [ BGEnhanced ] 无法显示本地图片 (Issue #467) 请问解决了吗？我上传视频也是这样 并没有，还是这个样子的。不知道怎么解决233 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我也不太清楚，试了好多别的也还是没有用，，

**Comment by cbq11111** [comment]
一样的 退版本 和BETE版本都不能读取本地图片 只能用在线图片 出BUG了

**Comment by jiaxcandy** [comment]
> 看下你选的啥图片

请问一下有解决方法吗，，

**Comment by jiaxcandy** [comment]
> 一样的 退版本 和BETE版本都不能读取本地图片 只能用在线图片 出BUG了

请问下你那边解决了吗。三周了我这还是这样（）

**Comment by xwh8965** [comment]
> 看下你选的啥图片

哥 可以帮忙定制模块吗 有预算

**Comment by MicroCBer** [comment]
> > 看下你选的啥图片
> 
> 哥 可以帮忙定制模块吗 有预算

？

**Comment by MicroCBer** [comment]
图片，视频路径不要有中文，特殊字符
