### ISSUE TITLE
[ Bug ] 更新到1.3.1后不兼容3.0.0版本的网易云

### ISSUE THREAD

**Issue by HijetZhao** [MicroCBer/BetterNCM#468]
### Bug 描述

更新到1.3.1后不兼容3.0.0版本的网易云

### 复现步骤

更新到1.3..1版本的插件就不兼容了，之前还可以

### 期望行为

可以正常使用插件

### 屏幕截图

![屏幕截图 2023-12-20 174336](https://github.com/MicroCBer/BetterNCM/assets/44498643/c40a0a7b-ce9f-4676-b0c2-2d927975bb17)
![屏幕截图 2023-12-20 174325](https://github.com/MicroCBer/BetterNCM/assets/44498643/1ab2a848-33c3-484f-a96a-05f6e0244490)
![屏幕截图 2023-12-20 174311](https://github.com/MicroCBer/BetterNCM/assets/44498643/b7db2bb2-bd72-4348-8852-03dbf435609b)

### BetterNCM 版本

1.3.1

### 网易云音乐版本

3.0.0

### 网易云音乐 Patch 版本

391250a

**Comment by LBWnb617** [comment]
解决了吗？我也是这个问题，新版的网易云用不了插件

**Comment by HijetZhao** [comment]
> 解决了吗？我也是这个问题，新版的网易云用不了插件

更新到1.3.2后插件商店可以打开，在开发者选项中打开显示与版本不匹配的插件后也能看到所有插件，但是大部分都与3.0版本的网易云不匹配，所以还是无法使用的状态，最好还是把网易云降级

**Comment by MicroCBer** [comment]
请更新
