### ISSUE TITLE
[ Plugin Bug ] Furigana和RefinedNowPlaying疑似不兼容

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#469]
### Bug 描述

插件列表：
![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/e8d80f19-8c5e-4bed-9492-63610e489a10)
如题，在[Furigana](https://github.com/MuttonString/Furigana)中的设置如下：
![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/68961cc9-f873-47c5-9f2e-4703ffea82ba)
打开歌词页面后开启音译模式，显示如下：
![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/021bb38e-a9ad-4be3-b519-91957cf7cf39)
疑似可视化问题，卸除可视化后仍无法正常显示：
![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/169c5cd1-aeea-4d4f-af81-b95fec2f1c53)
最后试图卸载RefinedNowPlaying但是发现是两个插件的依赖项作罢（大概下周末会补传卸除RefinedNowPlaying之后的显示效果截图）

### 复现步骤

1. 下载‘Furigana与’RefinedNowPlaying'插件
2. 打开播放页面
4. 看到错误
（3被我吃了）

### 期望行为

应当正确的显示被Furigana更改过后的歌词。

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

3c65ae6

### 已安装插件

如图（ListScrollFix没有截全）

**Comment by MicroCBer** [comment]
[Furigana](https://github.com/MuttonString/Furigana) 中写了不兼容 RNP
