### ISSUE TITLE
插件解压失败

### ISSUE THREAD

**Issue by Gasolcloudteam** [MicroCBer/BetterNCM#47]
安装了官方版本2.10.3和2.10.4以及第三方绿化版均无法正常加载，只加载了一个BetterNCM版本出来

**Comment by Gasolcloudteam** [comment]
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-aba66bd1-03ea-482d-811b-4ea202c3baf2/8d2d07f7-7323-4a5e-aadc-d0d2ccdcbdad.png](url)

**Comment by Gasolcloudteam** [comment]
[图片]https://vkceyugu.cdn.bspapp.com/VKCEYUGU-aba66bd1-03ea-482d-811b-4ea202c3baf2/8d2d07f7-7323-4a5e-aadc-d0d2ccdcbdad.pngl)

**Comment by LLLisheng** [comment]
![GZNX3%O%NUO7(8X41B3R97](https://user-images.githubusercontent.com/115356048/194709637-371844c2-da75-4773-aaba-775e654a1d51.png)
遇到了一样的问题

**Comment by LLLisheng** [comment]
![GZNX3%O%NUO7(8X41B3R97](htt
![DUXJEIDG ~@R$}X{`MLW$ES](https://user-images.githubusercontent.com/115356048/194709705-0af3a2b7-f8e1-43ae-83f2-ce15cadd8b88.png)
ps://user-images.githubusercontent.com/115356048/194709654-f6e19d63-3327-4dde-9a50-d61cc3803bcc.png)
遇到了一样的问题，网易云音乐是2.10.4，插件版本是0.2.3

**Comment by Gasolcloudteam** [comment]
> ![图片](https://user-images.githubusercontent.com/54032212/194708429-c01a6d49-1798-4125-81c1-c360e92efa3a.png) 试一试重装（？ 你可以按F12然后在控制台上将报错截图
![Snipaste_2022-10-08_23-49-16](https://user-images.githubusercontent.com/77867479/194716041-c9b98870-2e01-448d-ace3-fa708ebeebac.png)
如图

**Comment by LLLisheng** [comment]
网易云和插件均重装了
![1MKBXNRNFEHV` 5M5R8Y}O](https://user-images.githubusercontent.com/115356048/194734863-c6d70b38-08b4-4576-8801-4ce032d5576e.png)

![J~5(PZXWY{ G2FTXEL2 0UT](https://user-images.githubusercontent.com/115356048/194734874-55365bcc-4c54-4ad1-bd7e-cce17cec51dd.png)

![%18{OFF~EKXONUW`2A4%AFM](https://user-images.githubusercontent.com/115356048/194734894-b6540660-052f-4e8e-953d-1f50134588dc.png)

依旧不能使用

**Comment by vosoland** [comment]
我也是这个问题，0.22和0.21都可以，就0.23不行

**Comment by vosoland** [comment]
0.22崩溃。。目前只有0.21可以加载出插件列表pluginmarket

**Comment by MicroCBer** [comment]
用户名是否为中文？

**Comment by LLLisheng** [comment]
抱歉没有看消息提示，之前用户名是 倾念丶 ，但是我目前名字改为 Twi_ 卸载重新安装网易云和插件后也是只加载出图标。会不会是中文路径的问题？我的网易云安装路径是中文的。

**Comment by MicroCBer** [comment]
已知中文用户名和路径在BetterNCM`^0.2.2`下会出问题 具体原因不清楚 可能是字符集那一块的东西 目前最好的解决办法是不要有中文

**Comment by LLLisheng** [comment]
坐等修复再用，那为什么我把名字改掉之后还会出现这个问题呢

**Comment by MicroCBer** [comment]
尝试`0.2.4`是否可用，更换了编译
字符集

**Comment by LLLisheng** [comment]
![error](https://user-images.githubusercontent.com/115356048/201456093-e9b896e8-2c6c-4039-9515-d1fbdb0cdcc4.png)
![image](https://user-images.githubusercontent.com/115356048/201456120-9e1e7337-e6e9-4442-8c14-24de53fa6d8c.png)
好像还是不正常
