### ISSUE TITLE
Taskbar-Lyrics

### ISSUE THREAD

**Issue by SiYue04** [MicroCBer/BetterNCM#472]
### Bug 描述

更新BetterNCM插件后插件商城丢失Taskbar-Lyrics插件，我不清楚这是哪个的原因。

### 复现步骤

更新网易云版本到3.0.0
更新BetterNCM插件
插件商城找不到Taskbar-Lyrics插件

### 期望行为

希望能够修复

### BetterNCM 版本

3.0.5

### 网易云音乐版本

3.0.0.Beta

### 网易云音乐 Patch 版本

b64aabe

### 已安装插件

Taskbar-Lyrics

**Comment by MicroCBer** [comment]
该插件未支持网易云3.0.0，故不会加载
