### ISSUE TITLE
LibFrontendPlay 警告有一些 Hijack 没有成功生效

### ISSUE THREAD

**Issue by PLFJY** [MicroCBer/BetterNCM#473]
### Bug 描述

LibFrontendPlay 警告有一些 Hijack 没有成功生效
![293330833-d6f06559-af51-48f9-a068-296dc8954f10](https://github.com/MicroCBer/BetterNCM/assets/135627876/dfa8f4ff-326c-4d19-adcd-c55b4340addf)

### 复现步骤

在安装LibFrontendPlay插件后打开网易云出现了大量类似这样的错误

### 期望行为

希望得到解决方案和修复

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

eb9cf81

### 已安装插件

InfLink
LibEAPIRequest
RefinedNowPlaying
任务栏歌词
LibLyric
纯净分享链接
RoundConerNCM
LibFrontendPlay

**Comment by MicroCBer** [comment]
不用管他
