### ISSUE TITLE
[ Bug ] BetterNCM DevTools 无法显示插件的控制台输出信息和报错信息

### ISSUE THREAD

**Issue by MuttonString** [MicroCBer/BetterNCM#474]
### Bug 描述

开发插件时，console.log函数无法在BetterNCM的F12打开的DevTools中打印信息
此外，插件的任何error信息也无法在控制台显示
直接在控制台使用console.log和console.error等函数也无效，没有输出值，只有函数的返回值undefined
之前版本的BetterNCM（好像是1.2.x）是有效的，而现在只能使用alert函数替代

### 复现步骤

在插件的源代码中使用console.log(111111)，无作用
插件某条语句出错，控制台无显示
控制台使用console.log(111111)，无作用

### 期望行为

console.log等语句应当在BetterNCM DevTools的控制台当中打印内容
插件的error也应当在控制台中打印出来

### 屏幕截图

![{15B727EF-3667-49d5-A814-B6F121C21F4B}](https://github.com/MicroCBer/BetterNCM/assets/97750941/44ac6598-6ec3-427c-bc33-4bada4ec5404)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

eb9cf81

**Comment by MicroCBer** [comment]
你开logcleaner了
