### ISSUE TITLE
[ Bug ] 在3.0.0版本网易云使用降级插件后，网易云音乐打不开了

### ISSUE THREAD

**Issue by kituo** [MicroCBer/BetterNCM#476]
### Bug 描述

我在3.0.0版本网易云使用降级插件后，网易云音乐完全打不开了。
点击网易云音乐的时候会看到有窗口一闪而过，任务管理器里面也可以看到网易云音乐的后台，但是没有网易云的窗口。
后来我尝试了
1、重启系统，打开网易云无法启动；
2、将 betterncm，整个文件夹删除，打开网易云无法启动；
3、卸载插件，打开网易云无法启动；
4、卸载网易云音乐重新安装，打开网易云无法启动；
5、

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望网易云音乐可以正常启动

### BetterNCM 版本

1.3.2

### 网易云音乐版本

3.0.0

### 网易云音乐 Patch 版本

网易云页面打不开了，看不到具体信息

**Comment by WZdaze** [comment]
应该是网易云的问题，3.0.0有进程没窗口，用2.10正常

**Comment by Onsaki** [comment]
我不小心更新到3.0.0 beta版之后直接安装的插件，现在症状是能打开，但是卡在首页动不了。后台查看内存占用一直在1.2G，非常平稳。

**Comment by MicroCBer** [comment]
如果可以，在群内找我远程调试

**Comment by QWXL** [comment]
我也有这个问题

**Comment by copenwu** [comment]
怎么加入群聊
