### ISSUE TITLE
[ Bug ] 安装无缝切歌后，LibFrontendPlay禁用，导致Studio One音乐伴奏无声，麻烦技术大哥给想想办法，感谢!

### ISSUE THREAD

**Issue by maomao11588** [MicroCBer/BetterNCM#478]
### Bug 描述

LibFrontendPlay禁用

### 复现步骤

**例**:
1. 添加无缝切歌
2. 效果、静音恢复、输出设备，灰色，禁用

### 期望行为

希望技术大哥能帮忙给看看，感谢

### 屏幕截图

![优效截图20240205220357](https://github.com/MicroCBer/BetterNCM/assets/157939269/e9fb14c1-bafe-4b55-9123-f9127d9f5dc1)

### BetterNCM 版本

BetterNCM 1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:ebcf81

**Comment by MicroCBer** [comment]
无法解决
