### ISSUE TITLE
关于增加改变pc端界面字号的请求

### ISSUE THREAD

**Issue by UltramanJQK** [MicroCBer/BetterNCM#479]
### 描述你想要的功能

pc端网易云界面在大屏幕上面看太费眼睛了。网易云自带的设置里面只能更换字体，但是没有办法把字体放大。

### 描述你考虑过的替代方案

有一个Customize插件可以自己写CSS，但是奈何本人不会，只能求助

### 额外的背景

![3e8f3682e17f199e75919d384b0c713](https://github.com/MicroCBer/BetterNCM/assets/103574919/b278ea3f-4963-4176-9ba5-bcdf70849b08)

**Comment by MicroCBer** [comment]
请使用 stylesnippets
