### ISSUE TITLE
[适配请求][网易云更新]功能失效

### ISSUE THREAD

**Issue by whoisfancy** [MicroCBer/BetterNCM#48]
网易云音乐  2.10.4 (Build:200396) (Patch:1:0826571)
BNCM  0.2.3

#47

**Comment by XiaoMouz** [comment]
既然已有相关issue建议移步至相关的issue下comment以免带来不必要的时间浪费

**Comment by whoisfancy** [comment]
> 既然已有相关issue建议移步至相关的issue下comment以免带来不必要的时间浪费

好的，对不起
