### ISSUE TITLE
前两天还能用商店，昨天就打不开了failed to fetch

### ISSUE THREAD

**Issue by young7s** [MicroCBer/BetterNCM#480]
### Bug 描述

打不开商店

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

怎么解决

### 屏幕截图

![屏幕截图(2219)](https://github.com/MicroCBer/BetterNCM/assets/160811888/1565436f-5c71-4c34-8be9-d841a7b6f27c)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

eb9cf81

### 已安装插件

![image](https://github.com/MicroCBer/BetterNCM/assets/160811888/2ade8e62-3ec5-491f-8ad0-d2692966baf3)

**Comment by MicroCBer** [comment]
换源，叉掉由插件添加的源

**Comment by young7s** [comment]
> 换源，叉掉由插件添加的源
好了，谢谢

**Comment by youensChen** [comment]
> 换源，叉掉由插件添加的源

请问新源的连接是什么
