### ISSUE TITLE
[ Plugin Bug ] Furigana报错:"Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by ConCose** [MicroCBer/BetterNCM#481]
### Bug 描述

Furigana无法正使用

### 复现步骤

1.下载Furigana
2.播放任意日文歌曲
3.看到报错框闪现

### 期望行为

能正常使用Furigana

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/0138cc10-3824-4220-b335-8cca8279776b)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

3c65ae6

### 已安装插件

如图：
![image](https://github.com/MicroCBer/BetterNCM/assets/119386507/c52a44bc-afd3-4620-99c1-e307b8a985dc)

**Comment by MicroCBer** [comment]
真心希望你看到了创建issue时的

# 粗体提示
