### ISSUE TITLE
[ Bug ] 加载失败

### ISSUE THREAD

**Issue by ESTTSE0841** [MicroCBer/BetterNCM#482]
### Bug 描述

pluginmarket 加载失败

### 复现步骤

每次打开都加载失败，重启没用重载也没用

### 期望行为

一打开就是加载失败

### 屏幕截图

<img width="786" alt="屏幕截图 2024-02-25 150849" src="https://github.com/MicroCBer/BetterNCM/assets/161250990/6589653e-c2f1-42b6-a037-a74eadd3b628">

### BetterNCM 版本

1.3.2

### 网易云音乐版本

3.0.0

### 网易云音乐 Patch 版本

aae5544

**Comment by MicroCBer** [comment]
选择其他源
