### ISSUE TITLE
[ FR ] 请教一下 BetterNCM  项目的实现原理

### ISSUE THREAD

**Issue by MMMMMoris** [MicroCBer/BetterNCM#484]
### 描述你想要的功能

BetterNCM 是如何实现 dll 注入的？最近也有一个基于 electron 的软件，开发很久没有实现深色模式，看的我头疼
想问一下BetterNCM 实现 dll 注入的原理，我去学习一下，后面自己改一改那些不重视用户体验的软件
Google 了一下，提到了一个 [node-ffi](https://github.com/node-ffi/node-ffi)
不知道这个是不是 BetterNCM 的实现原理
诚心请教，感谢帮助

**Comment by MicroCBer** [comment]
https://t.me/csmb_channel/4728

**Comment by MicroCBer** [comment]
另外，一般 electron 应用建议参考 betterdiscord 而不是 betterncm

**Comment by s12mmm3** [comment]
> https://t.me/csmb_channel/4728

还有相关文档吗？这个链接打不开了
