### ISSUE TITLE
[ Bug ] 网易云卡住，只能通过任务管理器强制关闭

### ISSUE THREAD

**Issue by lsjg292** [MicroCBer/BetterNCM#485]
### Bug 描述

具体情况是在边开游戏边听歌时，过一会（大概两首歌时间）后，网易云会卡住，很久之后再继续播放一小会儿，之后循环（听几秒卡好久），同时网易云不能做任何交互包括没法关闭（除非任务管理器强制关闭）

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

希望大佬解决或给出建议，感谢

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1：c652906

**Comment by MicroCBer** [comment]
duplicated https://github.com/MicroCBer/BetterNCM/issues/470#issuecomment-1978460971
