### ISSUE TITLE
安装InfLink后电脑无法读取音乐播放进度

### ISSUE THREAD

**Issue by fanfan040109** [MicroCBer/BetterNCM#489]
### Bug 描述

系统的播放进度无法读取音乐，一直显示Loading

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

能正常读取

### 屏幕截图

<img width="1141" alt="8e8e415309400f561f6983ebf4c92ac" src="https://github.com/MicroCBer/BetterNCM/assets/165706855/70ddf96f-37fb-486c-b433-d2954b1beb3f">
![54f8272c1067b23bd27b5a532965c0d](https://github.com/MicroCBer/BetterNCM/assets/165706855/3fb96687-1f95-48ad-9792-cf1f724a606f)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

3.0.0.Beta

### 网易云音乐 Patch 版本

c130ebd

### 已安装插件

InfLink
StyleSnippet
TinyNCM
RevivedSource

**Comment by mangofanfan** [comment]
我想，也许该插件不兼容网易云3.0.x的版本
我使用插件库里的那个插件降级到2.10.x之后，又折腾了几下，现在可以显示了。
![image](https://github.com/MicroCBer/BetterNCM/assets/81764833/772e5f10-6a02-4cd6-83d1-590234d1616f)
