### ISSUE TITLE
[功能请求]希望增加last.fm同步插件

### ISSUE THREAD

**Issue by HRxiaohu** [MicroCBer/BetterNCM#49]
希望增加last.fm同步插件

**Comment by MicroCBer** [comment]
具体是怎么同步

**Comment by HRxiaohu** [comment]
用last.fm的api接口将听歌记录同步到last.fm上

**Comment by HRxiaohu** [comment]
https://www.last.fm/api

**Comment by HRxiaohu** [comment]
这里有一个Web端的插件仓库，希望能帮到您https://github.com/web-scrobbler/web-scrobbler/

**Comment by MicroCBer** [comment]
看了下api 太麻烦了 不太想做……
