### ISSUE TITLE
[ Bug ] 无法加载插件商店

### ISSUE THREAD

**Issue by rong6** [MicroCBer/BetterNCM#491]
### Bug 描述

之前重装了一下系统（保留数据），安装网易云3.0版本后尝试安装betterncm，发现插件商店无法打开，一片空白，多次卸载、重装均无效，多次重载插件无效，使用他人的“PluginMarket.plugin”文件无效。

### 复现步骤

你们恐怕无法复现，但我可以把我的betterncm目录传给你。
[betterncm.zip](https://github.com/MicroCBer/BetterNCM/files/14892779/betterncm.zip)

### 期望行为

正常打开插件商店。

### 屏幕截图

已是最新版本：
![image](https://github.com/MicroCBer/BetterNCM/assets/109727098/f7270838-32ae-4923-b813-cfde76a7e1d2)
打开一片空白：
![image](https://github.com/MicroCBer/BetterNCM/assets/109727098/c2fba53a-baa7-43f0-9ed7-d1a79b640ce3)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

[Installer显示]3.0.10(x64) [网易云关于界面]3.0.0(Build:202691)

### 网易云音乐 Patch 版本

c130ebd

**Comment by lsjg292** [comment]
我是重载了一下好了

**Comment by 579486** [comment]
+1

**Comment by luyuhang5201** [comment]
+1

**Comment by MicroCBer** [comment]
请重载插件再试

**Comment by rong6** [comment]
> 请重载插件再试

仍然不行，我已使用最新版本的betterncm_installer，最新版本的betterncm，最新版本的网易云客户端，但仍无法加载。
![betterncm_installer](https://github.com/MicroCBer/BetterNCM/assets/109727098/886ae654-a34c-4646-9930-59b5b74a1c3c)

![无法加载插件商店](https://github.com/MicroCBer/BetterNCM/assets/109727098/579c87f3-63e5-4fb1-b36d-7061ef576360)

```PluginMarket.plugin```文件内的```manifest.json```文件中插件商店版本为0.7.2：
![manifest.json文件内容](https://github.com/MicroCBer/BetterNCM/assets/109727098/a1e5fd45-11da-42f8-b536-ac4383050cfd)

**Comment by MicroCBer** [comment]
是否更改过数据地址 若有 点击安装器中间按钮还原

**Comment by rong6** [comment]
> 是否更改过数据地址 若有 点击安装器中间按钮还原

未修改过

**Comment by 579486** [comment]
是不是因为是beta版本所以才有问题

**Comment by rong6** [comment]
> 是不是因为是beta版本所以才有问题

应该不是，我正式版和测试版都试过，都不行

**Comment by MicroCBer** [comment]
> > 是否更改过数据地址 若有 点击安装器中间按钮还原
> 
> 未修改过

点击“打开插件文件夹”看看打开的是什么文件夹

**Comment by BYH404** [comment]
现在的插件支持3.0.x的网易云版本了？我也是升级网易云3.0版本之后重载插件无法运行 只能降级网易云版本为2.10.12

**Comment by MicroCBer** [comment]
3.0.x在一年前就支持了

**Comment by BYH404** [comment]
> 3.0.x在一年前就支持了

谢谢回复，请问我在通过installer安装程序安装插件到3.0.x版本时，为什么在设置旁边不会出现betterNCM的插件图标？即使出现插件图标，列表内也不会显示插件市场，这是网易云音乐的版本不兼容吗？使用的网易云版本是3.0.0，WINDOWS 11 22H2

**Comment by rong6** [comment]
> > > 是否更改过数据地址 若有 点击安装器中间按钮还原
> > 
> > 未修改过
> 
> 点击“打开插件文件夹”看看打开的是什么文件夹

网易云安装目录下下betterncm文件夹

**Comment by CellerX** [comment]
我也是同样的问题

**Comment by MicroCBer** [comment]
> > > > 是否更改过数据地址 若有 点击安装器中间按钮还原
> > > 
> > > 
> > > 未修改过
> > 
> > 
> > 点击“打开插件文件夹”看看打开的是什么文件夹
> 
> 网易云安装目录下下betterncm文件夹

你修改过数据地址，自己去点击安装器中间按钮还原
