### ISSUE TITLE
启动 UnblockMusic 服务失败

### ISSUE THREAD

**Issue by Yui1st** [MicroCBer/BetterNCM#492]
### 复现步骤

打开网易云就跳出这个错误

### 期望行为

I can use this plugin.

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/166216516/b52ce491-8ad0-434a-8296-82a52878a37e)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:c652906

### 已安装插件

Revived UnblockMusic

**Comment by jiuguiyuejie** [comment]
我也是这种情况

**Comment by jiuguiyuejie** [comment]
你解决了吗

**Comment by Yui1st** [comment]
> 你解决了吗

我解决了，我把音源里的JOOK,YOUTUBE(JS),yt-download取消勾选就可以使用了

**Comment by MicroCBer** [comment]
请在对应插件 repo 下发送相关 issue；主仓库作者不是插件作者，无法解决你的问题

**Comment by yx476000** [comment]
实测有效

**Comment by yx476000** [comment]
> > 你解决了吗
> 
> 我解决了，我把音源里的JOOK,YOUTUBE(JS),yt-download取消勾选就可以使用了

实测有效
