### ISSUE TITLE
[ Plugin Bug ] 关于系统盘非C盘导致的无法使用

### ISSUE THREAD

**Issue by BestGreed** [MicroCBer/BetterNCM#493]
### Bug 描述

目前自动使用的保存目录强制为C盘，当系统盘非C盘会直接报错

### 复现步骤

手动安装和自动安装均报错

### 期望行为

目前我所用系统盘为H盘，无法使用本插件，希望可以修复此问题，允许指定数据保存位置或者通过变量保存到用户目录AppDate也行啊

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

12f60b8

### 已安装插件

no

**Comment by MicroCBer** [comment]
[?](https://github.com/MicroCBer/BetterNCM/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E4%BF%AE%E6%94%B9%E6%8F%92%E4%BB%B6%E6%95%B0%E6%8D%AE%E4%BD%8D%E7%BD%AE)

**Comment by MicroCBer** [comment]
甚至installer里都有 我尬住了

**Comment by BestGreed** [comment]
> 甚至installer里都有 我尬住了
如果你不信邪可以按我的情况复现一下
installer修改数据地址这个按钮重新指定目录后没有生效
插件初始化直接报错找不到C盘
然后网易云纯净启动

**Comment by MicroCBer** [comment]
他喵的 有这个功能啊 有啊 甚至做了ui啊

**Comment by MicroCBer** [comment]
看文档啊

> [链接都在这里了](https://github.com/MicroCBer/BetterNCM/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E4%BF%AE%E6%94%B9%E6%8F%92%E4%BB%B6%E6%95%B0%E6%8D%AE%E4%BD%8D%E7%BD%AE)
