### ISSUE TITLE
使用BGEnhanced插件后右上角关闭图标消失不见

### ISSUE THREAD

**Issue by yedepengyouquan** [MicroCBer/BetterNCM#495]
### Bug 描述

使用BGEnhanced插件后右上角关闭图标消失不见

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

解决问题

### 屏幕截图

![微信图片_20240517103646](https://github.com/MicroCBer/BetterNCM/assets/125645162/3b16c3d4-ed9d-4a02-84af-82bb7e9551f8)

### BetterNCM 版本

1.32

### 网易云音乐版本

3.00

### 网易云音乐 Patch 版本

7d52eec

### 已安装插件

**例**:
- StylesheetLoader
- ActionEnhancement

**Comment by FishCMD** [comment]
我也遇到同样的问题，即使不加任何插件，右上角的叉也会消失，可能是betterncm按钮把别的元素往右挤了？
