### ISSUE TITLE
LogCleaner 插件安装后 类苹果歌词 黑屏

### ISSUE THREAD

**Issue by Lormited** [MicroCBer/BetterNCM#496]
### Bug 描述

已安装类苹果歌词，安装 LogCleaner 后重载，网易云歌词页面黑屏

### 复现步骤

1. 安装类苹果歌词
2. 安装LogCleaner
3. 打开歌词页面
4. 看到黑屏错误

### 期望行为

兼容插件，或注明两个不兼容

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

1:12f60b8

### 已安装插件

Matrtial You
类苹果歌词
ListScrollFix

**Comment by MicroCBer** [comment]
请在对应插件 repo 下发送相关 issue；主仓库作者不是插件作者，无法解决你的问题
