### ISSUE TITLE
[ Bug ] BetterNCM图标导致本体窗口关闭键消失异常

### ISSUE THREAD

**Issue by TMKIA** [MicroCBer/BetterNCM#498]
### Bug 描述

最新网易云3.0，关闭按钮被挤出界面

### 复现步骤

1. 网易云PC端更新最新3.0版本
2. 打开主页面
3. 右上角关闭按钮缺失

### 期望行为

右上角功能图标布局调整，关闭按钮能正常显示并操作

### 屏幕截图

![QQ截图20240522091044](https://github.com/MicroCBer/BetterNCM/assets/53467250/f73d6fbb-2504-4727-9f6e-67f9449ab56d)

### BetterNCM 版本

1.3.2

### 网易云音乐版本

3.0.0

### 网易云音乐 Patch 版本

dcedbae

**Comment by mutudu95** [comment]
屏蔽mini模式把
![image](https://github.com/MicroCBer/BetterNCM/assets/33865570/0345f545-9215-40e2-86b9-06d0e3236fa5)

**Comment by jiuguiyuejie** [comment]
3.0版本那些插件能用吗？unlockmusic能用吗
