### ISSUE TITLE
是否没给更换背景配置确定按钮？

### ISSUE THREAD

**Issue by Pengugo** [MicroCBer/BetterNCM#5]
打开一看只有Simlyfy下面有确定，而Microrange下面则没有，按回车也没有变化，点击确定则直接没有了背景。
<img width="251" alt="屏幕截图 2022-08-04 234754" src="https://user-images.githubusercontent.com/110621816/182890585-b3732296-1017-48ee-b547-fdee2625a8e0.png">

**Comment by MicroCBer** [comment]
那个确定是确定全部）

黑屏原因应该是你打的https://，但是这个本地只支持http，把s删掉就好了

**Comment by Pengugo** [comment]
是我铸币了（，抄错了
