### ISSUE TITLE
[Crash] 停止播放后，程序在后台一段时间后，直接崩溃。或听歌中途崩溃。

### ISSUE THREAD

**Issue by IASUI** [MicroCBer/BetterNCM#50]
本次崩溃前，从最小化窗口点开，界面全白，可操作，操作几下后崩溃

![image](https://user-images.githubusercontent.com/66980246/194761043-6b816616-71c0-482a-a9f7-b9dc641779ab.png)

**Comment by MicroCBer** [comment]
f12看看有无报错

**Comment by IASUI** [comment]
@MicroCBer  
有的时候用一段时间就崩溃。不是每次打开就崩溃。
而且就两次崩溃是全白。其中只有一次是全白但可以操作。
其他情况都是弹窗说崩溃（有的情况还能继续放歌）
所以我现在也F12不了。崩溃了可以继续操作然后F12的可能性也不大

**Comment by MicroCBer** [comment]
因为这种崩溃可能是因为后台报错多了造成的 看下有无报错

**Comment by MicroCBer** [comment]
umm 看不出什么问题 我先升级了然后自己看看能不能复现

**Comment by IASUI** [comment]
@MicroCBer  ok👍

**Comment by MicroCBer** [comment]
复现不了，考虑是UCMInstaller的问题？先卸载看看

**Comment by IASUI** [comment]
@MicroCBer  
先开F12 Console，一直挂后台，一直等到崩溃。这时console界面是全黑的，所以错误耶还是看不了。
要不出个崩溃时输出日志的功能。这样就能看见错误了？

还有就是F12后直接关闭窗口整个网易云也跟着关闭。 按F12后继续按F12只会打开更多的console窗口。
![image](https://user-images.githubusercontent.com/66980246/196705903-4f2ced9d-215b-4b49-ae6d-05ec373a8026.png)

**Comment by IASUI** [comment]
@MicroCBer 
这次崩溃时的控制台
![1](https://user-images.githubusercontent.com/66980246/197248268-a55c8b3d-7a76-4559-a9e7-972484980e15.png)
![2](https://user-images.githubusercontent.com/66980246/197248293-e0ed2e49-5f1b-4e22-a4f5-0f985ecc364d.png)
![3](https://user-images.githubusercontent.com/66980246/197248306-e7cb9e06-0943-45ae-a8d4-d81f92b89d5e.png)

**Comment by MicroCBer** [comment]
使用
https://microblock.lanzouy.com/iMwxT13j0kze
