### ISSUE TITLE
[ Plugin Bug ] InfLink插件导致网易云卡死

### ISSUE THREAD

**Issue by DreammStill** [MicroCBer/BetterNCM#501]
### Bug 描述

启用InfLink插件后，网易云卡死

### 复现步骤

1. 启用InkLink插件
2. 重启网易云
3.网易云开启后几秒钟卡死，无法操作

### 期望行为

网易云正常运行

### BetterNCM 版本

1.3.3

### 网易云音乐版本

3.0.0Beta(build 202859)

### 网易云音乐 Patch 版本

5f51f20

### 已安装插件

- InkLink
- Stylesnippet

**Comment by DreammStill** [comment]
目前发现，如果你手速够快的话，在网易云卡死之前可以进入inklink设置中将信息源改为DOM（默认原生但显示3.0不可用，不知道是不是因为我从2.0更新3.0的问题），但是改完后wallpaper和win自带的音乐播放均显示Loading无法显示歌曲信息

**Comment by Speetania** [comment]
我也出现同样问题，手贱点了另外一种原生信息源，每次开网易云就会卡死。
删除插件包，betterNCM，重新安装BetterNCM和Inflink插件后，还是会卡死。不知道是否和注册表有关？还是哪里没删除干净。是否能修改文件将inflink的信息源设置改掉？

**Comment by Lukoning** [comment]
> 我也出现同样问题，手贱点了另外一种原生信息源，每次开网易云就会卡死。 删除插件包，betterNCM，重新安装BetterNCM和Inflink插件后，还是会卡死。不知道是否和注册表有关？还是哪里没删除干净。是否能修改文件将inflink的信息源设置改掉？

按F12 -> Application -> LocalStorage -> orpheus://orpheus
搜索框（Filter）输入inf
Key值为cc.microblock.inflink.info-provider的项就是InfLink保存的设置

![image](https://github.com/user-attachments/assets/b437acb4-dae5-4ed2-9cd6-cb50cbdfd0a8)

双击这个项的Value值，将其改为  "dom"  （一个符号都不能错）

![image](https://github.com/user-attachments/assets/89cb210a-4de8-455d-af7c-7fcef971d616)


顺便提一句，在这里你可以找到几乎所有你装过的插件的设置

**Comment by DreammStill** [comment]
> 我也出现同样问题，手贱点了另外一种原生信息源，每次开网易云就会卡死。 删除插件包，betterNCM，重新安装BetterNCM和Inflink插件后，还是会卡死。不知道是否和注册表有关？还是哪里没删除干净。是否能修改文件将inflink的信息源设置改掉？

手速够快的话，在它卡死之前可以进设置改成DOM
