### ISSUE TITLE
[ Plugin Bug ] 插件无法加载封面

### ISSUE THREAD

**Issue by eamon2003** [MicroCBer/BetterNCM#507]
### Bug 描述

[ 这首歌的封面是什么? ] 此插件在使用的过程中常发生无法加载出封面的情况 且卸载重装无法解决此问题 电脑可以正常上网 并非网络问题

### 复现步骤

大部分时候在打开网易云时就已经出现加载不出的情况

### 期望行为

期望可以正常显示封面 

### 屏幕截图

![image](https://github.com/user-attachments/assets/6f692df1-8a24-4c59-aa63-d261be698a39)

### BetterNCM 版本

1.3.3

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

1:12f60b8

### 已安装插件

PluginMarket 
ArtistAllSongs 
GPT Trans 
明/暗主题切换器 
Material You 
MikuPlugin 
Refined NowPlaying 
Revised Secondary Windows
StylesheetLoader 
StyleSnippet 
TinyNCM 
ActionEnhancement 
CrossFade LFP 
FluentProgressBar 
ListScrollFix 
纯净分享链接 
RoundCorner NCM 
这首歌的封面是什么？

**Comment by MicroCBer** [comment]
> 注意：
我们建议您尽可能地在插件 repo 下提交与插件相关的问题报告。
但是，如果一个插件没有自己的插件 repo，或您不清楚是哪个插件出了问题，您可以在此提交。

你看不到吗？
