### ISSUE TITLE
[ Bug ] 不统计听歌数据

### ISSUE THREAD

**Issue by WMH2024** [MicroCBer/BetterNCM#509]
### Bug 描述

在安装BetterNCM插件后，PC端数据不纳入任何统计。而卸载后，各项功能均正常使用。

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

 .

### BetterNCM 版本

1.3.3

### 网易云音乐版本

3.0.16(x64)

### 网易云音乐 Patch 版本

411cb23

**Comment by MicroCBer** [comment]
无法复现
