### ISSUE TITLE
网易云自动更新后,启动崩溃

### ISSUE THREAD

**Issue by icerain9247** [MicroCBer/BetterNCM#51]
debug.log :
?8))?|
^挦裏罀h觵h??h恋,觵駂?<<?)^犮9h觵h>?h?觵駂睜9h,xh憛)8))?|
O挦裏罀h觵h??h恋,觵駂?<<?)^犮9h觵h>?h?觵駂睜9h,xh憛)8))?||m8挦裏罀h觵h??h恋,觵駂?<<?)^犮9h觵h>?h?觵駂睜9h,xh憛)8))?||m挦裏罀h觵h??h恋,觵駂?<<?)^犮9h觵h>?h?觵駂睜9h,xh?

**Comment by MicroCBer** [comment]
这是人类可以理解的东西吗

貌似是新版本的问题 我先看看别的issue
