### ISSUE TITLE
新版本网易云音乐无法启动bncm

### ISSUE THREAD

**Issue by yugossotos** [MicroCBer/BetterNCM#513]
### Bug 描述

网易云更新后bncm没了，重新下载bncm无法正确识别网易云音乐版本，指定网易云位置无法选择

### 复现步骤

![屏幕截图 2024-09-10 135142](https://github.com/user-attachments/assets/ae376969-a967-4618-ba3b-71741ca248e1)

### 期望行为

更新适配新版网易云

### BetterNCM 版本

1.12

### 网易云音乐版本

3.0.2

### 网易云音乐 Patch 版本

3f4c7a9

**Comment by MicroCBer** [comment]
bncm在一年前就适配新版本网易云了
