### ISSUE TITLE
BGEEnhanced这一个插件使用本地jpg作为壁纸会报错

### ISSUE THREAD

**Issue by 7-one** [MicroCBer/BetterNCM#514]
### Bug 描述

使用jpg作为背景时会报错添加背景失败

### 复现步骤

1.进入插件
2.进入插件BGEnhanced，点图片
3.选择本地jpg格式的图片设为背景
4.报错

### 期望行为

完善

### 屏幕截图

![Uploading 微信截图_20240912112249.png…]()

### BetterNCM 版本

1.3.2

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

12f60b8

### 已安装插件

PluginMarket
BGEnhanced
InfLink
Material You
RefinedNowPlaying
StyleSnippet
TinyNCM
DowngradeOK
ListScrollFix
RoundCornerNCM

**Comment by MicroCBer** [comment]
你能不能认真看一眼报错内容
