### ISSUE TITLE
[功能请求]希望增加一个改写网易云随机播放算法的插件

### ISSUE THREAD

**Issue by CavDev** [MicroCBer/BetterNCM#58]
sb网易云，随机播放结果就循环常听的那几首歌
哪个畜生想出来的这么脑瘫的算法，能简单伪随机实现出来的功能硬是要恶心人

**Comment by MicroCBer** [comment]
我这边没遇到过这种情况呢

**Comment by MicroCBer** [comment]
暂时没有发现这样做的必要性，以及不建议在issues骂人
