### ISSUE TITLE
插件不能使用了

### ISSUE THREAD

**Issue by fuzipei** [MicroCBer/BetterNCM#59]
今天打开发现没有插件的入口了 主题变回来了

**Comment by MicroCBer** [comment]
网易云版本？

**Comment by fuzipei** [comment]
> 网易云版本？

![image](https://user-images.githubusercontent.com/96692326/199919324-28d765f2-dfb5-4d2c-ab60-f6572736c538.png)

**Comment by MicroCBer** [comment]
重新安装可以吗

**Comment by fuzipei** [comment]
> 重新安装可以吗

是要重装网易云吗

**Comment by MicroCBer** [comment]
重装插件

**Comment by MicroCBer** [comment]
可以吗？

**Comment by fuzipei** [comment]
> 可以吗？

重装网易云也不行

**Comment by fuzipei** [comment]
> 可以吗？

我清除了一下本地数据 又重装了一下 现在好了
