### ISSUE TITLE
当我按键盘上的p键时,出现如下报错

### ISSUE THREAD

**Issue by RainbowSUCK** [MicroCBer/BetterNCM#6]
- > 
HTML.# > 
BODY.mq-default.mq-yahei.f-fs0.mq-anioff#music-163-com > 
DIV.#x-g-mn > 
SECTION.g-mn.one#auto-id-cFIAkeNVw8pnqAVX > 
DIV.#auto-id-5t9tADXLw75xOtpZ > 
SECTION.g-setHd.j-flag.n-set# > 
DIV.u-header.header#

**Comment by MicroCBer** [comment]
这不是报错）

这是我在debugger插件里面制作的一个功能，按p可以复制当前鼠标下的元素路径

卸载debugger即可
