### ISSUE TITLE
[插件BUG] 修复使用BGEnhanced有概率导致整个界面上移

### ISSUE THREAD

**Issue by mo-jinran** [MicroCBer/BetterNCM#60]
在评论区内下一页会导致整个界面上移
在云村内查看动态图片有概率会导致
效果图：
![ARUGAQJHP)KIHUZS N$87DX](https://user-images.githubusercontent.com/66980784/200116399-e24dc362-d87f-4c5c-9f6d-664fff4935c7.png)
解决办法：
修改div#BGEnhanced_Background标签样式，把position: absolute;改为position: fixed;

**Comment by MicroCBer** [comment]
fixed in `0.1.2
`
