### ISSUE TITLE
解灰插件能否在安装的时候使用随机高范围端口

### ISSUE THREAD

**Issue by AdoShan** [MicroCBer/BetterNCM#62]
8080是常用端口，容易占用呢

**Comment by AdoShan** [comment]
而且发现安装了解灰插件之后一旦占用8080端口，BetterNCM貌似直接无法工作了。把端口占用解除或者把解灰插件卸载之后一切正常

**Comment by MicroCBer** [comment]
Unblock Installer `0.1.7` 现在会在`10000-20000`之间随机挑一个

![image](https://user-images.githubusercontent.com/66859419/201411144-ae7c2607-7b3c-44f6-9e64-6c8eaa61c7b2.png)

也可以通过更改如图所示部分来更改服务器端口

**Comment by AdoShan** [comment]
> Unblock Installer `0.1.7` 现在会在`10000-20000`之间随机挑一个
> 
> ![image](https://user-images.githubusercontent.com/66859419/201411144-ae7c2607-7b3c-44f6-9e64-6c8eaa61c7b2.png)
> 
> 也可以通过更改如图所示部分来更改服务器端口

可以直接修改云音乐代理端口不需要修改解灰插件的端口吗？

**Comment by MicroCBer** [comment]
> 可以直接修改云音乐代理端口不需要修改解灰插件的端口吗？

现在UNM Installer会直接启动你代理设置对应端口的服务

**Comment by AdoShan** [comment]
> > 可以直接修改云音乐代理端口不需要修改解灰插件的端口吗？
> 
> 现在UNM Installer会直接启动你代理设置对应端口的服务

好多。多谢
