### ISSUE TITLE
使用主题之后没有心动模式

### ISSUE THREAD

**Issue by TIANTITNT** [MicroCBer/BetterNCM#65]
想随机听歌的时候习惯用心动模式，但主题把它去掉了，希望可以保留，毕竟只是一种播放模式，并没有造成不好的影响

**Comment by Yuelioi** [comment]
> 想随机听歌的时候习惯用心动模式，但主题把它去掉了，希望可以保留，毕竟只是一种播放模式，并没有造成不好的影响

哪个主题啊 我用是有心动的
