### ISSUE TITLE
NeteaseCloudMusicBN显示错误问题

### ISSUE THREAD

**Issue by Administrator-cmd** [MicroCBer/BetterNCM#68]
在NeteaseCloudMusicBN v10.2.3里，当系统中屏幕显示缩放大小调至非100%时，显示会发生位移。如图所示：https://www.aliyundrive.com/s/TQ56VeMUxem

**Comment by MicroCBer** [comment]
似乎是不使用gpu运行带来的问题，我这没法复现

**Comment by MicroCBer** [comment]
你的配置是？

**Comment by Administrator-cmd** [comment]
> 你的配置是？

i5-3317U，使用HD4000核显，电脑是Surface Pro初代

**Comment by MicroCBer** [comment]
#25 已取消强制禁止CPU渲染

**Comment by MicroCBer** [comment]
![ZSSOZ~2LV9U~T~TH_I9{@MU](https://user-images.githubusercontent.com/66859419/222940402-878b6b37-7238-41a6-b5b8-3d00f1cd6c73.jpg)

**Comment by Administrator-cmd** [comment]
> ![ZSSOZ2LV9UT~TH_I9{@MU](https://user-images.githubusercontent.com/66859419/222940402-878b6b37-7238-41a6-b5b8-3d00f1cd6c73.jpg)

win32转制版无法进行这个操作
