### ISSUE TITLE
[功能请求] 字體顔色更改的建議，以及音樂雲盤相關優化（？）

### ISSUE THREAD

**Issue by CreeperTCD** [MicroCBer/BetterNCM#70]
希望插件可以支持更改選中的字體的顔色，以及按鈕等的主題色，在原版網易雲的皮膚功能是可以直接根據主題改變的，插件之後好像只能是紅色，視選擇的背景可能有些突兀。
另外有一個小功能比較感興趣，就是雲盤裏的音樂能否手動添加封面和歌詞 不知道能不能實現。

**Comment by MicroCBer** [comment]
![~}809)$ODLR50$LFJWZEMRR](https://user-images.githubusercontent.com/66859419/205436322-db088717-592a-47f6-9ef4-7c4651692423.jpg)
![I3F9`{)U2XIKT0R6}B}8944](https://user-images.githubusercontent.com/66859419/205436331-56356c90-6547-4b95-b0df-5180b89824e5.png)

基于 #106 实现，将会和下一个版本的BetterNCM一起发布

**Comment by MicroCBer** [comment]
https://github.com/BetterNCM/CustomSongInfo
