### ISSUE TITLE
为什么总是无法联网

### ISSUE THREAD

**Issue by fbstorm** [MicroCBer/BetterNCM#72]
加载完插件后再次进入网易云，总是会显示无法联网，插件无法生效，绑定的账号也会不显示，搜索不了，能放歌

**Comment by Euclid-Jie** [comment]
我也是遇到了同样的问题

**Comment by GuityOrange** [comment]
the same

**Comment by GuityOrange** [comment]
具体一些的信息，BetterNCM-Installer-0.1.4，安装后下载一键解灰插件，到现在为止还没有问题，一旦启用解灰插件，所有内容显示无法联网，所有别的插件也无法生效。
用Installer卸载重装后又能恢复正常（只要不启动解灰插件）

**Comment by Euclid-Jie** [comment]
> 

我重装了一次网易云，这次没有发生无法联网的情况，你也可以尝试重装一次

**Comment by fbstorm** [comment]
重装了一次，大概确认是解灰插件的问题，没启动之前所有插件都试了，也关闭了好几次，都没有问题。

**Comment by MicroCBer** [comment]
不解决解灰问题
