### ISSUE TITLE
[功能请求] 支持Win10/Win11 System Media Transport Control 显示和控制播放

### ISSUE THREAD

**Issue by hv0905** [MicroCBer/BetterNCM#73]
# 效果
System Media Transport Control是win10/11附带的系统级媒体控制接口，它可以在控制中心和锁屏界面显示类似如下的效果：
![image](https://user-images.githubusercontent.com/29349119/201574159-ab020165-2286-473b-b325-6b8a90d6da8c.png)

# 相关资料
Microsoft Docs: https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/system-media-transport-controls
参考项目: https://github.com/Microsoft/Windows-universal-samples/tree/dev/Samples/SystemMediaTransportControls
参考项目2 (MPV扩展): https://github.com/datasone/MPVMediaControl

大概思路是用C#写一个后端与系统通信, 与插件使用websocket/匿名管道进行交互, 发送封面信息与指令

**Comment by MicroCBer** [comment]
对C#不是很熟悉，先搁置一下，优先实现一下webplaying

**Comment by Steve-xmh** [comment]
另外补一下说明，SMTC 支持 WinRT 调用，可以用支持 WinRT 的编程语言来写（应该会方便一些？）

比如 [Windows Rust](https://microsoft.github.io/windows-docs-rs/doc/windows/Media/struct.SystemMediaTransportControls.html)

**Comment by MicroCBer** [comment]
rust推销员史蒂夫（x

如果方便的话 大概确实会用rust

**Comment by Steve-xmh** [comment]
> rust推销员史蒂夫（x
> 
> 如果方便的话 大概确实会用rust

只要你愿意，我可以帮你折腾出 CEF 的 API（研究一下 Bindgen 之类的）

~~然后 BetterNCM 全体重构到 Rust（逃）~~

然后 BetterNCM 可以考虑支持 DLL 的载入，就能和各种语言原生对接了。

**Comment by MicroCBer** [comment]
关于dll加载 既然想把这个咕了很久的issue捡起来 肯定是要做的 不过我是在想是做成api的形式还是直接在manifest里加 然后调用固定入口函数

**Comment by MicroCBer** [comment]
![L07YCS5RW`Q50 @1WMB74T](https://user-images.githubusercontent.com/66859419/211396078-e16799f8-af7c-42b0-a103-92696c70f7eb.png)
![image](https://user-images.githubusercontent.com/66859419/211396110-cb774919-578d-4390-b207-d99a22ed1806.png)

**Comment by MicroCBer** [comment]
![}%GC `IIQLVPL6V7~X5~9WM](https://user-images.githubusercontent.com/66859419/211397864-1a9cbf86-0865-431e-988b-515e3c8be1cc.png)

![image](https://user-images.githubusercontent.com/66859419/211398274-8d745893-53a0-40fb-bf5d-3167098e6672.png)


Thumbnail支持
