### ISSUE TITLE
[功能请求] 支持深色模式自动切换与 Mica 主题

### ISSUE THREAD

**Issue by Hsnico** [MicroCBer/BetterNCM#74]
# 效果
![主题切换](https://user-images.githubusercontent.com/59398077/201583869-cee9f772-72b6-4154-9eb1-d49cf4f955aa.jpg)
根据系统设置动态切换颜色模式以及使用 Win 11 的 Mica 主题作为应用背景

**Comment by MicroCBer** [comment]
mica主题感觉比较难实现，可能只有自己写一套，有时间试试看

**Comment by MicroCBer** [comment]
![_DL_M%N$G09_O$GZM{8IM58](https://user-images.githubusercontent.com/66859419/202846334-32af1e91-c728-476d-a33b-d2e3a9be5edb.png)
![image](https://user-images.githubusercontent.com/66859419/202846410-e30d4aa1-0154-415a-afd1-b424fa419493.png)

**Comment by Junsang2000** [comment]
跟随系统的自动更换深色浅色模式可以实现吗？非常想要这个功能。主界面背景能够自动更换成播放歌曲的封面，我觉得也蛮不错的

**Comment by MicroCBer** [comment]
> 跟随系统的自动更换深色浅色模式可以实现吗？非常想要这个功能。主界面背景能够自动更换成播放歌曲的封面，我觉得也蛮不错的

API已经备好了，但是在有背景的情况下不太好切换深浅，我考虑一下怎么做

**Comment by Junsang2000** [comment]
我觉得 深色浅色的切换就是 ”字体颜色、不透明度与模糊度中应用中的底色“ 的不同方案，浅色模式就是深色字体＋模糊底色为白色，深色模式就是白色字体＋模糊底色为黑色，具体效果可以参考yesplaymusic中暗色模式切换对于不同歌曲封面背景的处理，背景图片的不同完全不影响显示效果。但如果不加模糊底色的话，暗色模式的切换效果和体验会非常糟糕，毕竟背景图片杂乱无章明暗不一，喜欢用纯图片作背景的用户大概是用不上的。

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/207602152-52b271d7-150f-472f-be34-3c3d7c314a03.png)
![image](https://user-images.githubusercontent.com/66859419/207602362-5db1f496-8129-4070-a863-6f3ab6a444d5.png)
确实好像还行

**Comment by Junsang2000** [comment]
![image](https://user-images.githubusercontent.com/95688805/207608040-0d9a45d1-2c41-4d4c-9cdb-89ee28072916.png)
![image](https://user-images.githubusercontent.com/95688805/207608205-5bd998c5-18f3-4215-b2f1-b1ea4e72c3de.png)

**Comment by MicroCBer** [comment]
> 跟随系统的自动更换深色浅色模式可以实现吗？非常想要这个功能。主界面背景能够自动更换成播放歌曲的封面，我觉得也蛮不错的

![image](https://user-images.githubusercontent.com/66859419/207758085-9a1f14a3-2e16-48eb-a7fa-c3ea130dfc49.png)

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/229214250-42cba473-1924-4da0-bbc2-896e0d5abeae.png)
