### ISSUE TITLE
v0.2.4 安装后网易云音乐弹窗：网易云音乐崩溃，请重启云音乐重试

### ISSUE THREAD

**Issue by shyshao** [MicroCBer/BetterNCM#75]
Win11，如题

无论网易云音乐在安装时有没有打开，在不在后台，installer是否管理员运行，都会弹窗 内容相同
关闭installer后可以正常打开网易云音乐 但没有安装上插件

曾经安装过v0.1.4 但已经在0.1.4的installer里卸载过了

**Comment by pxxchhh** [comment]
> Win11，如题
> 
> 无论网易云音乐在安装时有没有打开，在不在后台，installer是否管理员运行，都会弹窗 内容相同 关闭installer后可以正常打开网易云音乐 但没有安装上插件
> 
> 曾经安装过v0.1.4 但已经在0.1.4的installer里卸载过了

我也是这个问题

**Comment by MicroCBer** [comment]
版本是否高于2.10.2?
