### ISSUE TITLE
【BUG】没有插件商店

### ISSUE THREAD

**Issue by Arcsion** [MicroCBer/BetterNCM#77]
使用网易云音乐 2.10.5(Build:200451)(Patch.1:bc9f526) + BetterNCM 0.2.4，安装后无插件商店。
![Snipaste_2022-11-14_18-13-44](https://user-images.githubusercontent.com/40288853/201634706-b16ba113-8795-4200-8161-bde2c01b6f5f.png)

已使用以下方法，仍无法解决：
1. 重启网易云音乐
2. 打开/关闭代理
3. 使用 BetterNCM Installer 安装
4. 手动安装 msimg32.dll
5. 网易云音乐 > 设置 > 关于网易云音乐 > 有新版本时提醒我

**Comment by ppx007** [comment]
2.10.2-2.10.5均没有插件商店，问题不能稳定复现在其他电脑上。部分电脑1.10.5可用。

**Comment by kikozz** [comment]
same

**Comment by kikozz** [comment]
已找到问题，我的网络运营商是移动。移动进不去Gitee我也不知道为什么，换了DNS什么的全都没用，甚至挂全局都进不去。插件似乎要加载存在Gitee的配置才能拉取插件列表。所以插件列表不显示...

**Comment by MicroCBer** [comment]
> 已找到问题，我的网络运营商是移动。移动进不去Gitee我也不知道为什么，换了DNS什么的全都没用，甚至挂全局都进不去。插件似乎要加载存在Gitee的配置才能拉取插件列表。所以插件列表不显示...

插件商店就是挂在gitee上的

**Comment by MicroCBer** [comment]
> 使用网易云音乐 2.10.5(Build:200451)(Patch.1:bc9f526) + BetterNCM 0.2.4，安装后无插件商店。 ![Snipaste_2022-11-14_18-13-44](https://user-images.githubusercontent.com/40288853/201634706-b16ba113-8795-4200-8161-bde2c01b6f5f.png)
> 
> 已使用以下方法，仍无法解决：
> 
> 1. 重启网易云音乐
> 2. 打开/关闭代理
> 3. 使用 BetterNCM Installer 安装
> 4. 手动安装 msimg32.dll
> 5. 网易云音乐 > 设置 > 关于网易云音乐 > 有新版本时提醒我

尝试新pre-release

**Comment by kikozz** [comment]
> > 已找到问题，我的网络运营商是移动。移动进不去Gitee我也不知道为什么，换了DNS什么的全都没用，甚至挂全局都进不去。插件似乎要加载存在Gitee的配置才能拉取插件列表。所以插件列表不显示...
> 
> 插件商店就是挂在gitee上的

希望可以增加其他源，可以放到你们自己的服务器上？

**Comment by kikozz** [comment]
> > > > 已找到问题，我的网络运营商是移动。移动进不去Gitee我也不知道为什么，换了DNS什么的全都没用，甚至挂全局都进不去。插件似乎要加载存在Gitee的配置才能拉取插件列表。所以插件列表不显示...
> > > 
> > > 
> > > 插件商店就是挂在gitee上的
> > 
> > 
> > 希望可以增加其他源，可以放到你们自己的服务器上？
> 
> 实际上大多数情况gitee都比自己服务器快

建议添加备用

**Comment by Arcsion** [comment]
> 
> 尝试新pre-release

![image](https://user-images.githubusercontent.com/40288853/202881194-c7843c6f-3e83-4abb-a51a-171233144738.png)
pre-release版本可行
