### ISSUE TITLE
关于unblockneteasemusic的兼容

### ISSUE THREAD

**Issue by RealSeek** [MicroCBer/BetterNCM#8]
使用了本地web服务器会强制替换网易云的http代理
但是unblockneteasemusic也需要用http代理

有什么办法可以兼容(或把unblockneteasemusic以插件的形式加载?

**Comment by MicroCBer** [comment]
我已经在重启`BetterNCM-v2`了，到时候换个原理，就不挡unblock的路了
卡顿那些应该也会减少，所以，等我消息罢
