### ISSUE TITLE
{问题} 我该如何自己修改主题

### ISSUE THREAD

**Issue by lingtian152** [MicroCBer/BetterNCM#80]
我该如何自己修改主题

**Comment by fbstorm** [comment]
插件列表里安装一个主题插件，有一些能自定义，一共就几个，你自己看看就好了

**Comment by lingtian152** [comment]
> 插件列表里安装一个主题插件，有一些能自定义，一共就几个，你自己看看就好了

我有试过了一个 但我自己改了css代码文件 重启网易云后就会恢复原本的代码 这个是不可避免的吗

**Comment by fbstorm** [comment]
这个得问插件作者了，可能是启动时有检测，跟源文件不一样就改回来了吧

**Comment by lingtian152** [comment]
> 这个得问插件作者了，可能是启动时有检测，跟源文件不一样就改回来了吧

哦哦 好的

**Comment by MicroCBer** [comment]
> 这个得问插件作者了，可能是启动时有检测，跟源文件不一样就改回来了吧

启动时会重新解压，具体看文档
