### ISSUE TITLE
希望可以给视频背景增加自定义蒙版

### ISSUE THREAD

**Issue by Amhertx** [MicroCBer/BetterNCM#81]
有的视频部分区域比较亮，会导致字体看不清楚，希望能像静态壁纸那样可以调节亮度

**Comment by fbstorm** [comment]
支持

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/202848473-816b6c62-4679-4772-ac85-cc67691b7f63.png)
