### ISSUE TITLE
歌曲播放页希望加入永久隐藏右边的播放来源、推荐与下方评论区功能

### ISSUE THREAD

**Issue by sSkieri** [MicroCBer/BetterNCM#85]
同时发现某些歌手可能是因为在直播 所以在歌单页面中 名字后会有“live”字样还在，还有就是希望加入首次启动固定定位于某一页 如 每日推荐页 喜欢的音乐页的功能

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/202724654-172d764a-37f6-4af6-a938-62cee7edf35a.png)
小岩喵的`miku-plugin`应该能满足需求
