### ISSUE TITLE
网易云音乐新版本2.10.6无法使用BetterNCM

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#88]
![image](https://user-images.githubusercontent.com/104675168/202739627-64748d6f-8576-4e6f-92b7-59cec9167873.png)

**Comment by kikozz** [comment]
#77  检查能否可以链接到 gitee.com

**Comment by Ds1nk** [comment]
安装后没有BetterNCM标识 可以链接到Gitee

**Comment by MicroCBer** [comment]
F12切出devtools, 切network一栏，刷新
