### ISSUE TITLE
[BUG]TinyMCN勾删除直播后只会删标题

### ISSUE THREAD

**Issue by Marce1ek** [MicroCBer/BetterNCM#89]
TinyMCN勾删除直播后只会删标题，底下的视频还在
勾之前
![before](https://user-images.githubusercontent.com/99329516/202743983-349fb5ed-84f5-4996-8eb1-a7ad009e90c9.jpg)
勾之后
![after](https://user-images.githubusercontent.com/99329516/202744029-c5fe9911-3572-46e8-9a1f-e873ba493903.jpg)
![QQ截图20221118233840](https://user-images.githubusercontent.com/99329516/202744191-3b342ba7-59e2-4b59-87b7-95b2be5f7158.jpg)

**Comment by MicroCBer** [comment]
建议直接使用miku-plugin
（开摆！
