### ISSUE TITLE
新版解灰怎么没了啊

### ISSUE THREAD

**Issue by wentlwr** [MicroCBer/BetterNCM#92]
新版本没看到解灰插件了，是去掉了吗

**Comment by ForeverInfinity** [comment]
更新找不着了

**Comment by zhuzixuan2019241** [comment]
[UnblockCloudMusic_0.1.7.zip](https://github.com/MicroCBer/BetterNCM/files/10399277/UnblockCloudMusic_0.1.7.zip)
