### ISSUE TITLE
BGEnhanced透明材质的几个问题

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#93]
能修吗

**Comment by Ds1nk** [comment]
第二个是这样的
![image](https://user-images.githubusercontent.com/104675168/202896788-0fc1950a-6fea-4bbd-a215-909025440d02.png)

**Comment by Ds1nk** [comment]
第三个
![image](https://user-images.githubusercontent.com/104675168/202896913-7e644fde-28e5-4d9b-85c1-c412e627e657.png)

**Comment by Ds1nk** [comment]
第一个
![image](https://user-images.githubusercontent.com/104675168/202896945-c1e8f7cf-544b-4ebe-b0b7-4cb2b620af3f.png)

**Comment by Ds1nk** [comment]
第二个
![image](https://user-images.githubusercontent.com/104675168/202897113-61aca2bb-7fd4-4209-81cf-8c8e02ec53bb.png)
透明材质这么多问题，干脆移除了吧（bushi

**Comment by Ds1nk** [comment]
快修

**Comment by Ds1nk** [comment]
第一个是在移动窗口或者点按一些按钮时背景会变成底色
第二个是将一个覆盖网易云音乐窗口的窗口最小化后会留下较深的残影
第三个是拖动窗口后模糊断层
第四个是在最小化网易云音乐窗口后面的一个窗口会留下较浅的残影

**Comment by Ds1nk** [comment]
![image](https://user-images.githubusercontent.com/104675168/202965837-dfe50d10-7848-4fae-b5fd-1ddb2a38601a.png)

**Comment by Ds1nk** [comment]
![image](https://user-images.githubusercontent.com/104675168/202966577-ddbaff8a-89ed-45dc-ad1a-b2d975ea614e.png)

**Comment by MicroCBer** [comment]
透明材质本来就是写着玩的，已知bug很多
