### ISSUE TITLE
MoTheme圆角有瑕疵

### ISSUE THREAD

**Issue by Ds1nk** [MicroCBer/BetterNCM#96]
![image](https://user-images.githubusercontent.com/104675168/202971433-18b03e92-74b2-474f-ba72-5d00be841bcd.png)

**Comment by mo-jinran** [comment]
看起来挺正常的，瑕疵是指边缘有锯齿？

**Comment by Ds1nk** [comment]
![image](https://user-images.githubusercontent.com/104675168/203253996-d7542f8e-4a89-49a8-b668-64ebf2ddeb4e.png)
仔细看边缘，圆角有点不园

**Comment by MicroCBer** [comment]
我没看出来？

**Comment by Ds1nk** [comment]
e
