### ISSUE TITLE
没有网络网易云会崩溃

### ISSUE THREAD

**Issue by zhurens** [MicroCBer/BetterNCM#98]
没网络的时候登不了网易云，而且一断网网易云就什么也点不了，音乐也暂停播放了。
这个能个修复吗，网易云版本是2.10.4的

**Comment by Ds1nk** [comment]
《没网络的时候登不了网易云》没网当然登录不了啊
《而且一断网网易云就什么也点不了》《音乐也暂停播放了》插件需要网络运行
《这个能修复吗》大概率wontfix

**Comment by zhurens** [comment]
这样嘛...那是否可以没网的时候让插件失效，网易云照常运行呢，不然一旦断网就用不了网易云了挺麻烦的。

**Comment by Ds1nk** [comment]
+1

**Comment by Similarityoung** [comment]
我这好像有网 网易云上也显示没有网

**Comment by MicroCBer** [comment]
这个是解灰相关问题，解灰问题不修
