### ISSUE TITLE
桌面歌词

### ISSUE THREAD

**Issue by zhurens** [MicroCBer/BetterNCM#99]
能写一个桌面歌词功能嘛，感谢。
就像这样的，多行歌词显示，网易云自带的两行歌词太鸡肋了。
![image](https://user-images.githubusercontent.com/83685766/203220357-e1f59463-f9bd-45b6-97c5-417fb2b8798a.png)

**Comment by Ds1nk** [comment]
+1

**Comment by CheongSzesuen** [comment]
+1

**Comment by fon11731** [comment]
+1

**Comment by MicroCBer** [comment]
https://github.com/BetterNCM/CppLyrics
